ariel-os/ariel-os

.github/workflows/main.yml
Work around [this Ninja bug](https://github.com/ninja-build/ninja/issues/2052). Thanks @wca!
=> ci: work around ninja pipe bug

laze-project.yml, src/riot-rs-boards/Cargo.toml, src/riot-rs-boards/microbit-v2/Cargo.toml, src/riot-rs-boards/microbit-v2/src/lib.rs
Works out of the box once the minimal declarations are added, and is an easy-access board until I figure out how to do boards with bootloaders :-)
=> boards: Add microbit-v2

Cargo.lock, Cargo.toml
This also bumps embassy-net to 0.3.0.
=> bump embassy

Cargo.lock, examples/application/src/main.rs, examples/benchmark/Cargo.toml, examples/core-sizes/Cargo.toml, examples/embassy-http-server/src/main.rs, examples/embassy-net-tcp/src/main.rs, examples/embassy-net-udp/src/main.rs, examples/embassy/Cargo.toml, examples/hello-world/Cargo.toml, src/riot-rs-embassy/Cargo.toml, src/riot-rs-embassy/src/lib.rs, src/riot-rs-rt/Cargo.toml, src/riot-rs-rt/src/lib.rs, src/riot-rs/Cargo.toml, src/riot-rs/src/lib.rs
This PR makes threading optional.
=> make threading optional

README.md
=> doc: some README.md updates

Cargo.lock, examples/embassy-http-server/Cargo.toml, examples/embassy-http-server/laze.yml, examples/embassy-http-server/src/main.rs
picoserve now seems to require a larger stack.
=> deps: update picoserve to 0.8.0

examples/application/src/main.rs, examples/embassy-http-server/src/main.rs, examples/embassy-net-tcp/src/main.rs, examples/embassy-net-udp/src/main.rs, src/riot-rs-embassy/src/lib.rs
=> refactor: drop initialization args

examples/embassy-http-server/src/main.rs, examples/embassy-net-tcp/src/main.rs, examples/embassy-net-udp/src/main.rs, src/riot-rs-embassy/src/lib.rs, src/riot-rs-embassy/src/network.rs, src/riot-rs-embassy/src/sendcell.rs
=> feat: introduce `SendCell`

book/src/SUMMARY.md
This splits the book into sections for users (Developers working on their own applications using RIOT-rs) and developers (Those working on RIOT-rs). See also the [mdbook book](https://rust-lang.github.io/mdBook/index.html) for how this works.
=> book: Split into user and developer sections

README.md
I messed up in the previous PR and the reviewer didn't spot the issue :cry:
=> README: fix link to build system docs

README.md, laze-project.yml
=> laze: add "flash-erase-all" task for nrf52*

Cargo.toml, src/riot-rs-boards/Cargo.toml, src/riot-rs-buildinfo/Cargo.toml, src/riot-rs-chips/Cargo.toml, src/riot-rs-core/Cargo.toml, src/riot-rs-embassy/Cargo.toml, src/riot-rs-macros/Cargo.toml, src/riot-rs-rt/Cargo.toml, src/riot-rs-runqueue/Cargo.toml, src/riot-rs-threads/Cargo.toml, src/riot-rs-timers/Cargo.toml, src/riot-rs-utils/Cargo.toml, src/riot-rs/Cargo.toml
The ones at warn level are meant to be set at deny level as soon as we fix the associated issues.
=> test(lints): add a few workspace lints

README.md
a somewhat less "experimental" readme
=> README: updated text

src/riot-rs-threads/src/channel.rs
1. use `ptr.write(*something)` instead of `*ptr = *something`. This prevents dropping `*(ptr)`
~~2. wrap `recv()` and `try_recv()` result `MaybeUninit` in `UnsafeCell`~~
3. add `fence()` after `recv()` and `try_recv()` critical sections
Fixes #136.
=> riot-rs-threads: fix channel returning wrong values

laze-project.yml
=> build: make `install-toolchain also install thumbv8m.main-none-eabi

examples/README.md, examples/embassy-http-server/README.md, examples/embassy-net-tcp/README.md, examples/embassy-net-udp/README.md
Closes https://github.com/future-proof-iot/RIOT-rs/issues/199.
*edit* not all examples are listed, those that are not will be moved to `tests/` once #189 is in.
=> doc: a note about networking in `examples/README.md`

.github/workflows/dependencies-action.yml
See https://github.com/gregsdennis/dependencies-action.
=> ci: add action enforcing PR dependencies

src/riot-rs-runqueue/src/runqueue.rs, src/riot-rs-threads/src/channel.rs, src/riot-rs-threads/src/lock.rs, src/riot-rs-threads/src/threadlist.rs
This makes clippy much happier.
*edited to trigger PR dep check*
=> feat: provide Default impls where relevant

Cargo.toml
=> chore(clippy): deny indexing at workspace-level

doc/add_board_support.md
This updates the board support doc. Could be more exhaustive but at least it is not horribly outdated anymore.
=> doc: update add_board_support.md

Cargo.lock, Cargo.toml
Temporary workaround as suggested in #295.
=> deps: pin cortex-m-rt to 0.7.3

Cargo.lock, examples/hello-world-async/Cargo.toml, examples/hello-world-async/README.md, examples/hello-world-async/laze.yml, examples/hello-world-async/src/main.rs, examples/laze.yml
I realized that I was longing for a simple async tester. So here it is.
=> examples: introduce `hello-world-async`

.github/workflows/main.yml, Cargo.lock, laze-project.yml, src/riot-rs-boards/Cargo.toml, src/riot-rs-boards/espressif-esp32-c6-devkitc-1/Cargo.toml, src/riot-rs-boards/espressif-esp32-c6-devkitc-1/src/lib.rs, src/riot-rs-boards/src/lib.rs
Fix vendor name. Spotted by @ROMemories.
=> fix: `s/expressif/espressif/g`

.github/workflows/hax.yml
Specify the used hax reference. We might have to temporarily use an older version.
=> feat(CI): be explicit on the used hax branch

book/src/tooling/defmt.md
Correct laze command in the shell example in `book/tooling.md`.
Noticed while testing #255.
=> fix(book/tooling): fix shell example

src/riot-rs-bench/src/cortexm.rs
small comment addition as it popped up.
=> fix(doc): add comment regarding downcounting systick

Cargo.toml, src/riot-rs-rt/Cargo.toml
Tries to clarify how and why we select [`portable-atomic`](https://docs.rs/portable-atomic/latest/portable_atomic/)'s atomic implementations via its Cargo features.
N/A
None
=> fix(atomics): clarify how we select portable-atomic's atomic implementations

.github/workflows/build-deploy-docs.yml, .github/workflows/main.yml
Some features have been previously introduced, but were missing from the docs generated in CI; this PR enables them.
It also re-orders the lists of features in alphabetical order, for consistency.
=> ci(docs): enable missing features that should appear in the docs

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/enhancement.yml, .github/ISSUE_TEMPLATE/feature-request.yml, .github/workflows/dependencies-action.yml, .github/workflows/main.yml, .yamllint.yml, laze-project.yml, src/riot-rs-core/laze.yml, src/riot-rs-rt/laze.yml
- Set up YAML linting as we add more and more YAML files.
- Fix the linting errors found.
None
=> ci: set up yamllint checking

book/src/support_matrix.html, doc/support_matrix.yml
=> docs(esp): mark User USB as not currently supported

Cargo.toml, src/lib/coapcore/src/lib.rs, src/lib/coapcore/src/seccontext.rs
These lints prevent us from forgetting to make some items public and make sure intra-doc links are valid.
=> chore(lints): set more documentation-related lints to `deny`

GOVERNANCE.md
Add first version of GOVERNANCE.md document. Describing current leadership- and decision making processes of RIOT-rs.
Please check the references:
- Are they correctly issued?
- Is the template sufficiently mentioned? (I linked to the web page of the template, not to the actual template on GitHub. I've used both pages for reference)
- Are the creative commons description and links correctly mentioned?
=> docs(governance): create governance doc

.github/workflows/matrix-bot.yml
This PR makes the PR bot notify of `ready_for_review` events as well.
=> ci(matrix-bot): notify of `ready_for_review` events

src/riot-rs-runqueue/src/runqueue.rs
=> refactor(runqueue): use `Option::map` as hax now supports it

_typos.toml, src/riot-rs-runqueue/proofs/fstar/extraction/Makefile
=> chore(hax): update the Makefile with upstream

Cargo.lock, laze-project.yml, src/riot-rs-boards/microbit-v2/Cargo.toml, src/riot-rs-boards/nrf52/Cargo.toml, src/riot-rs-boards/nrf52/build.rs, src/riot-rs-nrf/Cargo.toml
This sets the microbit-v2 to use the right MCU, which in particular fixes flashing issues.
The `hello-world` and `gpio` examples were successfully tested.
=> fix(nrf52): fix support for the microbit-v2 board

Cargo.toml
These lints have been introduced in version 1.82.
=> chore(clippy): enforce two new lints at workspace level

Cargo.lock
=> chore(build): update Cargo.lock

examples/coap/Cargo.toml, examples/coap/src/main.rs, examples/coap/src/udp_nal/mod.rs, examples/coap/src/udp_nal/util.rs
These are simple fixes taken out of https://github.com/future-proof-iot/RIOT-rs/pull/348 – that PR is going back a few steps because I took a wrong turn, and this now I'm consolidating things into manageable changes.
This does introduce one FIXME, but the need for getting that piece of information was already there and just hidden by the broken code.
=> fix(examples/coap): Various fixes

Cargo.lock, examples/blinky/Cargo.toml, examples/coap/Cargo.toml, examples/embassy-http-server/Cargo.toml, examples/embassy-net-tcp/Cargo.toml, examples/embassy-net-udp/Cargo.toml, examples/embassy-usb-keyboard/Cargo.toml, examples/gpio/Cargo.toml, examples/hello-world/Cargo.toml, examples/log/Cargo.toml, examples/storage/Cargo.toml, examples/usb-serial/Cargo.toml, src/riot-rs-macros/src/task.rs, tests/gpio-interrupt-nrf/Cargo.toml, tests/gpio-interrupt-stm32/Cargo.toml, tests/gpio/Cargo.toml, tests/i2c-controller/Cargo.toml, tests/spi-loopback/Cargo.toml, tests/spi-main/Cargo.toml, tests/threading-lock/Cargo.toml
- bumps our embassy fork. now includes https://github.com/kaspar030/embassy/commit/4bd90029705618ddecfa812c795af82603ad70a3
- adapts our task macro to use new override
- drops now obsolete imports
The corresponding `embassy-executor-macro` change has been [PR'ed upstream](https://github.com/embassy-rs/embassy/pull/3503).
=> feat(macros): make `task` override `embassy-executor` crate path

Cargo.lock, src/riot-rs-threads/Cargo.toml, src/riot-rs-threads/src/lib.rs
... I kept wondering if this is enabled or not. which is good, it means there was not trouble. ;)
=> feat(threads): add debug message when using SMP

src/riot-rs-arch/src/dummy/usb.rs, src/riot-rs-embassy/src/usb.rs
This focuses on documentation that's quickly accessed from the homepage.
=> docs(usb): complete and slightly improve USB docs

examples/minimal/README.md
This PR collects all manual fixes found while reviewing #549.
Depends on #549.
=> renaming PR manual fixes

.github/workflows/main.yml
This is intended to catch leftover occurences of the old project name in in-flight PRs, following #549.
=> ci: check for leftover occurrences of the old project name

src/ariel-os-esp/src/gpio.rs, src/ariel-os-esp/src/i2c/controller/mod.rs, src/ariel-os-esp/src/i2c/mod.rs, src/ariel-os-esp/src/lib.rs, src/ariel-os-esp/src/spi/main/mod.rs, src/ariel-os-esp/src/spi/mod.rs
This documents items relevant for users, and hides the others from documentation, to prepare for them being rendered in #531. 
Documentation for the `ariel-os-esp` crate can be rendered locally using the following:
https://github.com/ariel-os/ariel-os/blob/17735f3525a6cb5e911634eac34a50ea5cd83fd9/.github/workflows/main.yml#L396-L405
Depends on #545.
=>  docs(esp-hal): document the `ariel-os-esp` HAL crate

Cargo.lock, Cargo.toml, deny.toml, examples/embassy-http-server/Cargo.toml
@kaspar030 Can you transfer the repos to our organization and then mark this PR as ready for review?
=> chore: update the URLs pointing to our forks

src/ariel-os-stm32/src/gpio.rs, src/ariel-os-stm32/src/i2c/controller/mod.rs, src/ariel-os-stm32/src/i2c/mod.rs, src/ariel-os-stm32/src/lib.rs, src/ariel-os-stm32/src/spi/main/mod.rs, src/ariel-os-stm32/src/spi/mod.rs
This documents items relevant for users, and hides the others from documentation, to prepare for them being rendered in #531. 
Documentation for the `ariel-os-stm32` crate can be rendered locally using the following:
https://github.com/ariel-os/ariel-os/blob/17735f3525a6cb5e911634eac34a50ea5cd83fd9/.github/workflows/main.yml#L431-L438
Depends on #550.
=>  docs(stm32-hal): document the `ariel-os-stm32` HAL crate

README.md
This adds an overview of all contributors to the readme. Image is from https://contrib.rocks (proxied by github).
See #574
=> docs(README): add contributors overview

README.md
Especially now that the name is changed, this sentence only adds confusion
None
=> docs(README): remove crossed out RIOT linking mention

Cargo.lock, Cargo.toml, examples/embassy-http-server/Cargo.toml, src/ariel-os-boards/nrf52/Cargo.toml, src/ariel-os-nrf/src/i2c/controller/mod.rs, src/ariel-os-nrf/src/lib.rs, src/ariel-os-nrf/src/usb.rs
This includes the smoltcp bump to 0.12.
=> chore(deps): bump embassy

examples/README.md, examples/usb-serial/Cargo.toml, examples/usb-serial/README.md, examples/usb-serial/src/main.rs
As part of #410, this PR mostly moves items around for consistency with other examples, and introduce a constant to remove a couple of magic numbers.
Tested successfully on nrf52840dk, rpi-pico-w, st-nucleo-h755zi-q, and st-nucleo-wb55.
=> docs(usb-serial-example): clean up the `usb-serial` example

src/ariel-os-embassy/Cargo.toml, src/ariel-os/Cargo.toml
Introduces the `dns` and `mdns` Cargo features, and simply passes them to `embassy-net`.
This will be useful for the upcoming HTTP client example.
=> feat(dns): add support for DNS and mDNS, through `embassy-net`

Cargo.lock, examples/http-server/Cargo.toml, examples/http-server/src/main.rs
upstream supports the new embassy-net 0.5.0 API changes now.
=> feat(deps): switch to picoserve 0.13.1 upstream

examples/README.md, examples/gpio/README.md
And another #410:
- Added to the examples readme
- Extended the example readme.
=> docs(gpio): clean up gpio example

examples/README.md, examples/threading-channel/README.md, examples/threading-channel/src/main.rs
Another #410, this PR:
- Extends the Readme,
- cleans up the logging a tad
- Adds an exit to the example.
=> docs(threading-channel): Clean up the threading-channel example

src/ariel-os-embassy/src/thread_executor.rs
[`raw::Executor` now has an `unsafe` `initialize()` function](https://github.com/embassy-rs/embassy/blob/main/embassy-executor/CHANGELOG.md) that needs to be called. Do it.
=> chore(embassy): ensure we call the embassy `raw::Executor::initialize()`

src/ariel-os-threads/src/arch/cortex_m.rs
... somehow didn't get caught by CI ...
=> cleanup(threads): drop unused `asm` import

examples/threading/README.md
As part of https://github.com/ariel-os/ariel-os/issues/410, this PR:
- Extend the readme with some clarification
=> docs(threading): clean up the threading example

laze-project.yml
This PR makes use of the (newly available in laze 0.1.28) option to define tasks in modules.
Fixes #624 and #623.
=> feat(laze): define flashing tasks in corresponding modules

examples/usb-serial/src/main.rs, laze-project.yml, src/ariel-os-bench/src/cortexm.rs, src/ariel-os-debug/src/lib.rs, src/ariel-os-embassy-common/src/identity.rs, src/ariel-os-embassy/src/lib.rs, src/ariel-os-embassy/src/thread_executor.rs, src/ariel-os-rt/src/cortexm.rs, src/ariel-os-threads/src/arch/cortex_m.rs, tests/coap/src/main.rs
This PR adds a laze `clippy` task.
Try with `laze -Cexamples/hello-world -b nrf52840dk clippy`.
(It piggybacks some clippy suggested fixes.)
=> feat(build): add laze `clippy` target

src/ariel-os-threads/src/lib.rs, src/ariel-os-threads/src/thread.rs, src/ariel-os-threads/src/thread_flags.rs
This uses a convention that's more commonly used and matches English syntax more closely.
There is no remaining occurrences for `numof` when grepped for case insensitively.
=> refactor(threading)!: rename `*_NUMOF` to `*_COUNT`

.github/workflows/build-deploy-docs.yml, .github/workflows/main.yml, src/ariel-os-threads/src/smp/mod.rs
The docs currently show the dummy type for `CoreAffinity`.
Depends on #662.
=> docs(thread): enable the rendering of the `core-affinity` feature

doc/build_system.md, laze-project.yml
Removes references to riotboot until it's usable again.
=> chore: remove riotboot-related configuration

src/ariel-os-threads/src/lib.rs
The `threading` example runs as expected on nRF52840-DK.
=> feat(thread): provide as many priority levels as the max thread count

src/lib/coapcore/Cargo.toml, src/lib/coapcore/src/ace.rs, src/lib/coapcore/src/lib.rs, src/lib/coapcore/src/seccfg.rs, src/lib/coapcore/src/seccontext.rs
This contains minor enhancements to logging of errors in coapcore, the Debug derives necessary for that, and documentation around it.
This may need updating when https://github.com/ariel-os/ariel-os/issues/679 concludes.
Comments already indicate how to improve it once https://github.com/knurling-rs/defmt/pull/916 lands (but that is currently bloc_k__ed by https://github.com/knurling-rs/defmt/pull/922), and when https://codeberg.org/chrysn/minicbor-adapters/pulls/1 is available.
=> fix(coap): logging and documentation fixes

laze-project.yml
This PR adds a laze target that simply lists all selected modules for an application.
(This should have some laze-native equivalent, but not yet ...)
=> feat(build): add `info-modules` laze target

.github/workflows/matrix-bot.yml
Fix following #692.
Documentation:
https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables#using-the-env-context-to-access-environment-variable-values
=> ci(chatbot): fix the chatbot message string

book/src/support_matrix.html, doc/support_matrix.yml
Fixes the documentation of ESP32-C6 and documents support for ESP32-S3-WROOM-1.
=> docs(support-matrix): document support for ESP32-S3-WROOM-1

book/src/introduction.md
=> docs(book): intro rewrite

book/src/coding-conventions.md, examples/coap-client/src/main.rs, examples/coap-server/src/main.rs, examples/http-server/src/main.rs, examples/tcp-echo/src/main.rs, examples/udp-echo/src/main.rs, examples/usb-keyboard/src/main.rs, examples/usb-serial/src/main.rs, tests/coap-blinky/src/main.rs, tests/coap/src/main.rs
This documents the new policy and updates the examples and tests to comply with it.
=> docs: split the re-exports imports

Cargo.lock, src/ariel-os-utils/src/env.rs, src/ariel-os/Cargo.toml, src/ariel-os/src/lib.rs
These macros were restricted for internal use, this exposes some of these for use by applications.
Will be used in #627.
=> feat(config): export macros providing var env access

book/src/SUMMARY.md, book/src/testing.md
Adds a chapter about Ariel's embedded-test integration.
Depends on #697.
=> docs(book): add chapter about `embedded-test` integration

examples/tcp-echo/laze.yml, examples/udp-echo/laze.yml
Fine-grained control over the stack size as proposed by #706 would be better, but this allows to run these examples for now.
=> docs(examples): increase the ISR stack to avoid HardFaults on RPi Pico W

src/ariel-os-embassy-common/src/gpio.rs
These were not part of the initial GPIO PR #322, this impls these traits now that we have a better idea of our debug logging story.
=> feat(gpio): impl formatting traits on common GPIO types

Cargo.lock
This adds commit [3d9f77e](https://github.com/ariel-os/embassy/commit/3d9f77ee05cdb18f1cd676233bcda9b6f7be3369), which makes `embassy-net` print out configured IP addresses at `info` level (instead of `debug`).
=> chore(deps): bump our embassy-net fork

.github/workflows/build-deploy-docs.yml, .github/workflows/preview-docs.yml
=> ci: preview docs if they changed in a PR

examples/thread-async-interop/laze.yml
=> fix(examples): re-enable `examples/thread-async-interop` for esp

.github/workflows/preview-docs.yml
Fixes `The workflow is not valid. .github/workflows/preview-docs.yml (Line: 12, Col: 3): The workflow must contain at least one job with no dependencies.` [(failed workflow run)](https://github.com/ariel-os/ariel-os/actions/runs/12931564996/workflow)
=> ci: drop unneeded `needs` from preview-docs.yml

.github/workflows/preview-docs.yml
=> ci: add some debug output to preview-docs

.github/workflows/build-deploy-docs.yml, .github/workflows/preview-docs.yml
=> ci: pass pr number to "Preview docs" workflow via artifact

.github/workflows/build-deploy-docs.yml
... why do we have to test this on main ...
=> ci: fix build-deploy-docs.yml run_id variable

.github/workflows/build-deploy-docs.yml, .github/workflows/preview-docs.yml
=> ci: align workflow run ids for "Preview docs"

Cargo.lock, Cargo.toml, deny.toml, src/ariel-os-debug/Cargo.toml, src/ariel-os-utils/Cargo.toml, src/ariel-os-utils/src/env.rs, src/ariel-os-utils/src/lib.rs, src/ariel-os/src/lib.rs
=> feat(config): introduce macros to obtain IP addresses at compile time

.github/workflows/preview-docs.yml
=> ci: don't download pr-number into path

.github/workflows/preview-docs.yml
=> ci: set run-id in preview-docs artfact download step

.github/workflows/preview-docs.yml
=> ci: fix outputs variable

book/src/introduction.md
=> docs(book-intro): polish the book introduction

README.md
=> docs(README): add a short security section

.github/workflows/build-deploy-docs.yml, .github/workflows/preview-docs.yml
... and fix the docs build and deploy "concurrency" value so PR builds don't cancel main build, and change the hash comparison to not fail the whole job on failure.
=> ci: correctly set "Preview docs" comment PR number

.github/workflows/preview-docs.yml
=> ci: add "pull-requests: write" to preview-docs.yml

.github/workflows/build-deploy-docs.yml
=> ci: fix docs for PR preview upload step

README.md
=> docs(README): polish the README

examples/README.md, examples/storage/README.md, examples/storage/src/main.rs
The storage example pr for #410
This:
- cleans up and adds extra info prints to the example.
- Adds the example to the index
- Extends the readme with extra info
Part of #410
=>  docs(storage): Clean up the storage example

book/src/getting_started.md
This asks new users to install fewer build dependencies.
The set of required build dependencies can be verified using the following `Containerfile`:
```containerfile
FROM docker.io/debian:testing-slim
ENV PATH="$PATH:/root/bin"
RUN apt-get update \
&& apt-get install -y \
git \
rustup \
ninja-build \
pkg-config \
libudev-dev \
clang \
gcc-arm-none-eabi \
&& rm -rf /var/lib/apt/lists/*
RUN rustup install stable
RUN cargo install --root=/root laze
RUN cargo install --root=/root --locked probe-rs-tools
RUN git clone https://github.com/ariel-os/ariel-os.git \
&& cd ariel-os \
&& laze build install-toolchain
RUN cd ariel-os \
&& laze -C examples/coap-server build -b nrf52840dk
```
(This takes about 6 minutes to build on my machine, YMMV.)
This `Containerfile` could be used in CI later or for …
=> docs(getting-started): reduce the set of build dependencies

book/src/support_matrix.html, doc/gen_support_matrix_html.rs
This did not look good on mobile, as the table was cropped on the left hand side.
The table was centered as part of #716.
=> docs(support-matrix): uncenter the support matrix

_typos.toml
The upstream crate (which we were not using yet) has been fixed.
=> chore(typos): remove an exception

Cargo.lock, ariel-os-cargo.toml, src/ariel-os-rp/src/i2c/controller/mod.rs
A version bump including some atomic fixes for the rp235x.
=> chore(deps): bump embassy-rp to 0.3.1

Cargo.lock, src/ariel-os-coap/Cargo.toml, src/ariel-os-embassy/Cargo.toml, src/ariel-os-embassy/src/asynch.rs, tests/coap/Cargo.toml
Exposes an async function which can be useful but is sometimes a bit difficult to find in the ecosystem.
=>  feat(async): expose `yield_now()`

.github/workflows/build.yml
Some of the steps take significant time (e.g., >1min for the xtensa toolchain) even when not needed.
=> ci: enable result-cache for more steps

FAQ.md, README.md
This PR adds an FAQ.
Closes #610.
Closes #345.
=> docs(FAQ): add FAQ.md

.github/workflows/pr-title.yml
This adds a check for the PR title, ensuring it is formatted according to our `committed` settings. (As discussed on this week's weekly meeting, preparing for enabling squash merges.)
*This check is not required, yet*. I suggest letting it run for a couple of commits to see how it behaves.
I actually think that we have to enable the regular committed check also for `merge_queue` builds, b/c this one might have a race - 1. correct title, 2. check runs, 3. title changes, 4. click "merge when ready", 5. check goes stale, but status still green -> might merge bad title. Let's see ...
=> ci: lint PR commit titles

book/src/tooling/coap.md
This updates the book chapter on CoAP to reflect the current state.
Depends on #803.
(there are fixups in #803 but not this one)
=> docs(book/coap): update

book/src/testing.md
=> fix(book): Update testing.md with current `embedded-test` version

doc/support_matrix.yml
This introduces an intermediate support level between "supported" and "available in hardware but not supported", for cases where only testing in hardware is required, so that potential users are not put off by a big red cross.
Depends on #716.
Depends on #767.
=> docs(support-matrix): add an intermediate support level

.github/workflows/build.yml
=> ci: build.yml only limit build if actually building something

.github/workflows/main.yml, src/lib/coapcore/src/seccfg.rs
Lint coapcore docs so it cannot fail later when actually generating the docs for publishing.
=> ci(lint): lint coapcore docs

laze-project.yml
#826 exposes a weirdness in laze's task escaping. No idea what it is but here is a workaround.
#826
=> fix(build): add fallback `CARGO_PRESHELL`

examples/device-metadata/laze.yml, examples/device-metadata/src/main.rs
I don't think there was a reason to use a thread in this example, and #410 said to default to async.
=> docs(device-metadata-example): use a task instead of a thread

laze-project.yml
=> refactor: drop `riot_binary` variable

laze-project.yml, src/ariel-os-boards/st-nucleo-wba55/Cargo.toml
Align the enabled features with the actual MCU support.
[STM32WBA55CG datasheet](https://www.st.com/resource/en/datasheet/stm32wba55cg.pdf)
=> fix(smt32): correct STM32WBA55CG support

laze-project.yml
... these should all be covered by `BOARDS: ${builder}`.
=> build: remove unneeded BOARD assignments

book/src/adding_board_support.md, laze-project.yml
This completes what was started in #764, now that laze 0.1.30 makes it possible.
=> refactor(laze): replace `depends` with `selects`

src/ariel-os-runqueue/src/lib.rs, src/ariel-os-runqueue/src/runqueue.rs
=> docs(runqueue): document the remaining items

src/ariel-os-threads/src/lib.rs, src/ariel-os-threads/src/sync/channel.rs, src/ariel-os-threads/src/thread_flags.rs
Documents the items from `ariel_os_threads` that were not documented yet.
=> docs(threads): document the remaining items

README.md, book/src/figures/ariel-hexacube-orange-rounded.svg
=> docs(README): add current logo

src/ariel-os-embassy/src/delegate.rs, src/ariel-os-embassy/src/gpio.rs, src/ariel-os-embassy/src/lib.rs, src/ariel-os-embassy/src/net.rs
=> refactor(embassy): enforce Clippy's `pedantic` lint group

book/src/figures/ariel-hexacube-orange-rounded.svg
This updates the logo to the latest version of the logo repo.
None
- Please check if the logo renders correctly on multiple browsers, both desktop and mobile
=> docs(logo): Update logo to latest SVG variant

book/src/storage.md
=> docs: update storage.md

Cargo.lock, Cargo.toml, ariel-os-cargo.toml, src/ariel-os-rp/Cargo.toml
Just version bumping. Quickly tested the `http-client` example on `rpi-pico-w`.
=> chore(deps): bump to embassy-rp 0.4.0+ariel-os, cyw43-pio 0.4.0

book/src/getting-started.md
=> docs(book): mention probe-rs udev docs in getting started chapter

src/ariel-os-embassy/src/lib.rs
... was added by #993, doesn't really fit.
=> chore(embassy): cleanup debug message

.github/workflows/build.yml
This bumps the relevant caching actions following the [decommissioning of the old GHA caching service](https://github.blog/changelog/2025-03-20-notification-of-upcoming-breaking-changes-in-github-actions).
=> ci: bump GHA caching actions

.github/workflows/build.yml
Since building both nightly and stable, workers ran out of disk space: https://github.com/ariel-os/ariel-os/actions/runs/14769393217.
So, rm build directory before starting nightly toolchain build.
=> ci: for nightly build, cleanup previous build artifacts

laze-project.yml
As Ariel Os makes extensive use of macros it can be helpful to see what the code looks like after macro expansion.
Therefore I added an `expand` task which runs `cargo expand`.
=> build(laze): add a `cargo-expand` task

Cargo.lock, Cargo.toml, ariel-os-cargo.toml
[embedded-test v0.6.1](https://github.com/probe-rs/embedded-test/releases/tag/v0.6.1) includes our Ariel OS support patches, so use that.
=> chore(deps): switch to `embedded-test` from crates.io

laze-project.yml
This adds a new task that just echoes the builder.
Useful in combination with `-m` for listing the boards that an application can be built for, e.g., `laze build -m info-boards | grep -v ^laze:`.
(laze needs a better story for machine parsing of task output. starting already here with reducing noise: https://github.com/kaspar030/laze/pull/716. I kept free-coding "info-boards` more than once, so maybe it already usefule as is.)
=> build(laze): add `info-boards` task

.github/workflows/build.yml, .github/workflows/main.yml
This makes sure that the Cargo lockfile is up to date, even for in-tree examples and tests.
Fixes #890.
=> ci(cargo): pass `--locked` to Cargo through `laze build` 

.github/pull_request_template.md
This clarifies the DCO mention in the current pull request template.
follow-up to #946
=> docs: Add DCO clarification to PR template

.github/workflows/main.yml, book/cmdrun-check.sh, book/src/hardware-functionality-support.md, doc/gen_support_matrix_html.rs, doc/support_matrix.yml
Add the concept of boards support tiers (similar to the [Rust toolchains](https://doc.rust-lang.org/nightly/rustc/platform-support.html)) to the support matrix in the documentation.
The support matrix script now has a new option `--tier <tier>` to render the support matrix for that support tier.
Closes #1056.
=> docs(support-matrix): add board support tiers

doc/support_matrix.yml, examples/blinky/laze.yml, examples/blinky/src/pins.rs, examples/gpio/laze.yml, examples/gpio/src/pins.rs
Add the nRF52-DK board (and its MCU nRF52832) to the support matrix.
=> docs(nrf): add nRF52-DK in the support matrix

README.md
We have obtained the OpenSSF best practices badge! This pr adds the badge to the README.md.
Please check if the links are correct and the badge is visible correctly.
=> docs: Add OpenSSF best practices badge to README.md

laze-project.yml, src/ariel-os-storage/build.rs, src/ariel-os-storage/src/lib.rs, tests/gpio-interrupt-nrf/laze.yml
1. disable usb (no peripheral)
2. config storage
3. disable storage (tests fail)
4. disable tests/gpio-interrupt-nrf (no config)
Signed-off-by: Kaspar Schleiser <kaspar@schleiser.de>
=> fix(nrf): fix build for nrf5340-net

CHANGELOG.md
This PR cherry-picks the changelog commit from our 0.2.1 release.
=> chore: add changelog for v0.2.1

src/ariel-os-random/src/lib.rs
Adds `crypto_rng_send()` and `fast_rng_send()` functions, this allows to get a random number generator that can be shared between threads, this is needed for the nRF BLE driver (SDC).
The need was discovered in #1074
=> feat(random): add RNG that can be shared between threads

Cargo.lock, examples/README.md, examples/ble-advertiser/Cargo.toml, examples/ble-advertiser/README.md, examples/ble-advertiser/laze.yml, examples/ble-advertiser/src/main.rs, examples/ble-scanner/Cargo.toml, examples/ble-scanner/README.md, examples/ble-scanner/laze.yml, examples/ble-scanner/src/main.rs, examples/laze.yml
This PR adds examples for using the Ariel OS BLE stack.
See also #560.
- Depends on #1069.
- Depends on #1074.
- Depends on #1118.
=> docs(ble): BLE examples

.github/workflows/main.yml, src/ariel-os-runqueue/README.md
Update the `typos` GIthub Action to version 1.34.0, and fix a typo it found.
=> chore(ci): bump `typos` action to 1.34.0

book/src/multithreading.md, src/ariel-os-macros/src/thread.rs
This explains how to actually pin threads, which wasn't exactly documented, and I don't believe this was an undocumented feature on purpose.
Depends on #1130 (doesn't actually depend on it semantically, this is just to test the `ci-build:skip` PR label on that PR)
=> docs(thread-macro): document the `affinity` macro parameter 

src/ariel-os-utils/src/env.rs
This slightly reworks the docs of config env macros, by introducing a dedicated "Errors" section.
This prepares for a more interesting PR I'll open soon.
The doc preview should come in handy.
=> docs(config): use a dedicated "Errors" section in macro docs

book/src/getting-started.md
This matches the installation instructions from the espflash readme
See https://github.com/esp-rs/espflash/pull/719#issuecomment-2586482474
=> docs(book): update the installation command for espflash

.github/workflows/build.yml, Cargo.lock, Cargo.toml, ariel-os-cargo.toml, examples/testing/laze.yml, laze-project.yml, src/ariel-os-alloc/src/lib.rs, src/ariel-os-bench/src/lib.rs, src/ariel-os-bench/src/native.rs, src/ariel-os-debug/Cargo.toml, src/ariel-os-debug/src/lib.rs, src/ariel-os-hal/Cargo.toml, src/ariel-os-hal/src/dummy/mod.rs, src/ariel-os-hal/src/lib.rs, src/ariel-os-native/Cargo.toml, src/ariel-os-native/src/lib.rs, src/ariel-os-power/src/lib.rs, src/ariel-os-rt/src/lib.rs, src/ariel-os-rt/src/native.rs, src/ariel-os-runqueue/src/lib.rs, src/ariel-os-threads/Cargo.toml, src/ariel-os-threads/src/arch/mod.rs, src/ariel-os-threads/src/arch/native.rs, src/ariel-os-threads/src/arch/native/critical_section.rs, src/ariel-os-threads/src/arch/native/critical_section/upstream.rs, src/ariel-os-threads/src/lib.rs, src/ariel-os/Cargo.toml, tests/gpio/laze.yml, tests/threading-lock/laze.yml
This PR provides an initial implementation of an infini-core scheduler, and a native board.
Try `laze -Cexamples/hello-world build -b native run`.
The scheduler implementation basically just removes the runqueue, and priorities are ignored. Each thread gets an `std::thread::Thread`.
The most tricky thing, (apart from enabling std for just some parts of the system), was to keep the isr based stopping of threads, where a call to `schedule()` pends an ISR, which triggers right at the end of a critical section. If that ISR de-schedules a thread into a non-Running state, that thread needs to stop. All our IPC logic depends on this behavior.
As std mutexes can only be unlocked from the thread that locked them, I used [`atomic-wait`](https://github.com/m-ou-se/atomic-wait) futexes, and provide a …
=> feat: native board

laze-project.yml, src/ariel-os-hal/Cargo.toml, src/ariel-os-native/Cargo.toml, src/ariel-os-native/src/hwrng.rs, src/ariel-os-native/src/lib.rs
This adds hwrng to the native board.
Signed-off-by: Kaspar Schleiser <kaspar@schleiser.de>
Depends on #647.
=> feat(native): wire up hwrng

.github/workflows/build.yml
Following #1153, this introduces a `ci-build:*` label for every HAL we support, and for the new native builder introduced by #647.
Check the CI logs for the `LAZE_BUILDERS` value, and the set of builders actually built for, for each relevant CI run.
Depends on #1159.
=> ci(build-pr-labels): introduce even more build labels

book/src/networking.md
Updates the list of boards that have the CYW43 chip that we support for Wi-Fi, following #940.
=> docs(wifi-book): update the list of boards having the CYW43 chip

.github/workflows/main.yml
PR #1057 introduced the concept of board tiers, this PR adds a missing lint check to make sure tier 3 renders correctly.
=> ci(support-matrix): check the rendering of tier 3 boards

src/ariel-os-sensors/src/measurement_unit.rs
Without this the units do not get pretty printed when using `defmt`.
---
`ci-build:skip` is enough because there is currently no implementors and Clippy and rustdoc make sure the rest is fine.
Extracted from #1191.
Depends on #1224.
=> fix(sensors): provide a custom `defmt::Format` impl for `MeasurementUnit`

book/src/development-processes.md
This PR introduces documentation for the steps required to cut a new release of `ariel-os`.
I had a look at [RIOT's guide](https://github.com/RIOT-OS/RIOT/tree/216ef04ae729c28eab57d2fe9c1692307492016c/doc/guides/managing-a-release), but few things seemed applicable to us.
=> docs(book): document the process for creating a release of `ariel-os`

src/ariel-os-storage/Cargo.toml
=> fix: pin sequential-storage to v4.0.1 to avoid v4.0.2 regression and v4.0.3 MSRV

README.md
Added the 'social: Mastodon' badge to README.md, so that users can find our Mastodon account easily.
=> docs: Add Mastodon badge to README.md

.github/workflows/main.yml, .github/workflows/vetting.yml, supply-chain/audits.toml, supply-chain/config.toml, supply-chain/imports.lock
This PR initializes [`cargo-vet`](https://mozilla.github.io/cargo-vet/index.html) for our repository and adds a CI workflow to check the our dependencies are properly vetted.
Currently, running `cargo (+nightly) vet` against our repo tells us that we have 237 fully audited dependencies (either because they were audited by trusted third parties, _e.g._ google and or because their publisher is trusted by trusted third parties _e.g_ `libm` is considered fully audited because it's published by `rust-lang-owner`) and 308 exempted ones. running `cargo (+nightly) vet suggest` shows which dependencies are yet to be audited and how many lines it amounts to. 
The CI file is adapted from [the  `cargo vet` docs](https://mozilla.github.io/cargo-vet/configuring-ci.html). 
Linked to #856
=> ci: add `cargo-vet` to the CI process

book/src/development-processes.md
As discussed in #1296, this documents our expected process for vetting Rust dependencies through `cargo-vet`.
Depends on #1296.
I expect this to require quite some discussion and refinements before merging.
=> docs(book): document our current dependency vetting process

src/ariel-os-sensors/src/category.rs, src/ariel-os-sensors/src/label.rs, src/ariel-os-sensors/src/measurement_unit.rs
This omits the time measurement labels and units, that will be added in a future PR.
Started as #1345
=> feat: add units, categories and labels for GNSS

README.md, ROADMAP.md
We lack a high-level overview of our motivations and our roadmap. This document addresses this lack.
=> docs: add ROADMAP.md

book/book.toml
This PR adds the option to fold book sub-chapters in the left menu.
Linked to #1327.
=> feat(book): add option to fold book sub-chapters

src/ariel-os-macros/src/define_count_adjusted_sensor_enums.rs
Reformats the `include!`d files from `ariel-os-macros`. Generated using:
```sh
cargo +nightly fmt -- src/ariel-os-macros/src/*.rs
```
This PR is better reviewed by hiding whitespace.
=> style: format `ariel-os-macros` `include!`d files

src/laze.yml, src/sensors/laze.yml
This lays out the structure the sensor drivers will go into. This is a separate PR so we're not forced to land future sensor driver PRs in a specific order.
=> chore(sensor-drivers): introduce a subdirectory for sensor drivers

book/src/randomness.md, src/ariel-os/Cargo.toml
Following #1339 this documents the newly added support for the `getrandom` crate.
Depends on #1339.
=> docs(random): document support for the `getrandom` crate
