ariel-os/ariel-os

laze-project.yml
src/riot-rs-boards/lm3s6965evb/Cargo.toml
src/riot-rs-boards/nrf52/Cargo.toml
src/riot-rs-core/Cargo.toml
src/riot-rs-rt/Cargo.toml
src/riot-rs-rt/src/debug.rs
src/riot-rs-rt/src/lib.rs
src/riot-rs/Cargo.toml

This introduces multiple backends for `riot-rs-rt::debug`.
Currently there are:
- a dummy backend
- semihosting (which supports printing through qemu)
- rtt_target (to be used with probe-run)

feat: initial probe-run support

---

Cargo.lock
Cargo.toml
examples/embassy-net/Cargo.toml
examples/embassy-net/src/main.rs
linkme.x
src/riot-rs-embassy/src/lib.rs

This PR:
- introduces EMBASSY_TASKS, a distributed slice of async functions that get called after riot-rs-embassy has finished it's initialization.
- TaskArgs, a structure that contains references that get passed to EMBASSY_TASKS
- adds the initialized network stack reference to TaskArgs (if available)
- updates `examples/embassy-net` with a simple tcp echo example
fixes #17.

Expose network stack to user tasks

---

examples/embassy-net-tcp/README.md
examples/embassy-net-udp/README.md

Docs say 10.0.42.61, `src/riot-rs-embassy/src/lib.rs` says `10, 42, 0, 61`.
I didn't test the TCP version, but given it doesn't have its own setup, I trust it's the same issue.
May this be the last code I'm doing IPv4 fixes for in a long time ;-)

doc: Fix hardcoded IP address

---

src/riot-rs-embassy/src/lib.rs

We want to be able to have multiple network stacks at the same time in the future.
We will need to rename the `stack` field of `TaskArgs` to be more specific, but this is a breaking change left for a future change.

refactor(riot-rs-embassy): make net feature gates more targeted

---

src/riot-rs-embassy/src/assign_resources.rs
src/riot-rs-embassy/src/lib.rs
src/riot-rs/src/lib.rs

We need our own peripheral-extraction macro compatible with `OptionalPeripherals`.

feat: define our own `assign_resources` macro

---

Cargo.lock
examples/application/Cargo.toml
examples/application/README.md
examples/application/laze.yml
examples/application/src/main.rs
examples/embassy-net-tcp/src/main.rs
examples/embassy-net-udp/src/main.rs
examples/laze.yml
src/riot-rs-embassy/src/assign_resources.rs
src/riot-rs-embassy/src/lib.rs

*Not to be merged, for discussion only*

introduce `Application` trait

---

src/riot-rs-embassy/Cargo.toml
src/riot-rs-embassy/src/lib.rs

This PR adds a mechanism for providing custom USB configuration, similar to how it is implemented for network configuration.

feat: allow overriding  the usb configuration

---

src/riot-rs-embassy/src/lib.rs

We're not Sillicon Laboratories, don't [claim](https://maclookup.app/search/result?mac=CC:CC:CC) to be a device from them

riot-rs-embassy: Use locally admin MAC addresses

---

examples/embassy-net-tcp/README.md

This extends the README.md of the embassy-net-tcp example with a line or two about the running telnet server, which seems to be *the feature* of this example.

examples/embassy-net-tcp: document tcp echo server access via telnet

---

Cargo.lock
src/lib/rbi/src/lib.rs

Small bug I noticed while viewing the code.
Currently, the `rbi::RingBufferIndex` panics if the more than `u8::MAX`-times elements have been added and removed again. 
The reason for this is that in `RingBufferIndex::available` the `writes` counter has wrapped over, but the `reads` counter hasn't and thus an overflow occurs in the subtraction.
The `counter_overflow_size*` tests didn't catch this because it only occurs if the `writes` counter is already 1 "ahead" of the `reads` counter and then `available` is called (either directly, of by `put`ting another element into the buffer).
This is fixed by simply using `wrapping_sub` as it is done in the other methods.
I added this check to the test, which panicked without this fix. The panic would alternatively also be visible if in said test per …

lib/rbi: use wrapping_sub to calculate available slots

---

examples/embassy-http-server/src/pins.rs
src/riot-rs-embassy/src/arch/nrf52.rs

This allows applications to not directly depend on the architecture Embassy crates to get access to peripherals.

feat(nrf-embassy): re-export the peripherals module

---

Cargo.toml

This bumps the embassy fork to today's upstream (14th Feb 2024). The "path" dependencies of modified crates are patched out now.

bump embassy

---

.github/workflows/main.yml
src/riot-rs-embassy/src/wifi/cyw43.rs
src/riot-rs-embassy/src/wifi/cyw43/rpi-pico-w.rs

We're using the released `cyw43`/`cyw43-pio`/`embassy_rp` now, adapt accordingly.

fix: rpi-pico-w cyw43 compile fix

---

examples/application/src/main.rs
examples/embassy-http-server/src/main.rs
examples/embassy-net-tcp/src/main.rs
examples/embassy-net-udp/src/main.rs
src/riot-rs-embassy/src/lib.rs

cleanup: drop `Drivers`

---

.github/workflows/main.yml

This shouldn't be needed anymore since #95.

ci: don't build in riot.rs-build container

---

.github/workflows/main.yml

So currently, a branch gets built at lest three times: first on the PR, second in the merge queue and third for the master push event.
This PR adds result caching to the "CI build step" that caches positive build results.

ci: cache PR build results based on git tree hash

---

src/riot-rs-embassy/src/lib.rs
src/riot-rs-embassy/src/wifi/cyw43.rs
src/riot-rs-rt/src/lib.rs
src/riot-rs-utils/src/env.rs

docs(env-macros): add an extra param for documentation

---

src/riot-rs-boards/Cargo.toml
src/riot-rs-boards/src/lib.rs
src/riot-rs/Cargo.toml

This allows to run rustdoc and clippy on the top-level `riot-rs` crate.
Not sure whether we want to use a Cargo feature for this eventually, but requiring to have a board selected is currently preventing us for using quite a few tools.

build(boards): allow to have no boards selected

---

src/riot-rs-embassy/src/arch/dummy.rs
src/riot-rs-embassy/src/arch/nrf52.rs
src/riot-rs-embassy/src/arch/rp2040.rs
src/riot-rs-embassy/src/lib.rs

feat(embassy-arch): return OptionalPeripherals from init()

---

.github/workflows/main.yml

We need to select no boards to allow for platform-independent doc generation.

ci(docs): check doc generation for the riot-rs crate

---

Cargo.toml
src/riot-rs-rt/Cargo.toml
src/riot-rs-rt/src/lib.rs
src/riot-rs/Cargo.toml

This is useful to be able to compile the riot-rs-rt crate with std, otherwise the panic_impls conflict.

feat(rt): make the custom panic handler optional

---

src/riot-rs-threads/src/thread_flags.rs

I believe the line should check for all bits in the mask? :slightly_smiling_face:

threads: fix `flag_wait_all`

---

src/riot-rs-macros/src/thread.rs
src/riot-rs-threads/src/lib.rs

This PR makes the thread macro use `thread_create_raw()` instead of `thread_create()`.
While `thread_create_raw()` is unsafe, this drops the need for the trampoline function.
IMO that makes debugging more natural, as e.g., thread function `module::fn_name()` ends up called like that in the linker output, and not `module::__start_thread_fn_name::trampoline()`.

riot-rs-macros: use `thread_create_noarg()` in thread macro

---

src/riot-rs-runqueue/src/runqueue.rs

Extracted from #133. 
Improve API documentation in `riot-rs-runqueue`.

riot-rs-runqueue: improve API documentation

---

src/riot-rs-threads/src/arch/cortex_m.rs
src/riot-rs-threads/src/channel.rs
src/riot-rs-threads/src/ensure_once.rs
src/riot-rs-threads/src/lib.rs
src/riot-rs-threads/src/lock.rs
src/riot-rs-threads/src/thread.rs
src/riot-rs-threads/src/thread_flags.rs
src/riot-rs-threads/src/threadlist.rs

Extracted from #133. 
Improve API documentation in `riot-rs-threads`.

riot-rs-threads: improve API documentation

---

src/riot-rs-rt/src/cortexm.rs

With embassy taking over the cortexm Peripherals,  `benchmark()` cannot take them anymore.
Let's see if it gets away with `steal()`ing them.

riot-rs-rt: make `cortexm::benchmark()` `steal()` Peripherals

---

laze-project.yml

Previously, the laze contexts were stacked by architecture:
- default -> riot-rs -> cortex-m -> thumbv6m-none-eabi -> nrf51 -> microbit
- default -> riot-rs -> cortex-m -> thumbv6m-none-eabi -> rp2040 -> rpi-pico
- default -> riot-rs -> cortex-m -> thumbv7m-none-eabi -> nrf52 -> nrf52832 -> nrf52dk
That only makes limited sense when looking at how we integrate embassy support, where e.g. the nrf51 & nrf52 have more in common than the nrf51 and the rp2040.
So this PR reorganizes this context tree like this:
- default -> riot-rs -> nrf -> nrf51 -> microbit
- default -> riot-rs -> nrf -> nrf52 -> nrf52832 -> nrf52dk
- default -> riot-rs -> rp -> rp2040 -> rpi-pico
The rustc targets are now provided by modules that are "select"ed where appropriate.

laze-project.yml: build context tree by embassy arch, not rust target

---

.github/workflows/main.yml

This adds a scheduled full build to 3:17am.
"full build" compared to the just-some-boards build that is done for PRs for speed reasons.

ci: add nightly build

---

src/riot-rs-threads/src/arch/cortex_m.rs
src/riot-rs-threads/src/arch/mod.rs
src/riot-rs-threads/src/lib.rs
src/riot-rs-threads/src/thread.rs
src/riot-rs-threads/src/thread_flags.rs
src/riot-rs-threads/src/threadlist.rs

Part of #157.
This PR:
- introduces an `Arch` trait for arch-specific logic in the scheduler 
- extracts the arch-independent scheduling logic out of the `cortex_m` module.
Details of the new `Arch` trait will probably still change once a second arch is added, but I think this is already a useful first step.
Wdyt?
Reviewing by commit might be easier; I tried to split it up a bit.

threads: extract arch-independent scheduling logic

---

Cargo.lock
examples/embassy-http-server/Cargo.toml
examples/embassy-http-server/src/main.rs
examples/embassy-net-tcp/src/main.rs
examples/embassy-net-udp/src/main.rs
examples/embassy-usb-keyboard/Cargo.toml
examples/embassy-usb-keyboard/src/main.rs
laze-project.yml
src/riot-rs-embassy/src/lib.rs
src/riot-rs-embassy/src/network.rs
src/riot-rs-embassy/src/usb.rs
src/riot-rs-macros/Cargo.toml
src/riot-rs-macros/src/config.rs
src/riot-rs-macros/src/lib.rs
src/riot-rs-macros/tests/macro_errors.rs
src/riot-rs-macros/tests/ui/config_conflicting_config_kind.rs
src/riot-rs-macros/tests/ui/config_conflicting_config_kind.stderr
src/riot-rs-macros/tests/ui/config_misspelled_config_kind.rs
src/riot-rs-macros/tests/ui/config_misspelled_config_kind.stderr
src/riot-rs-macros/tests/ui/config_no_parameters.rs
src/riot-rs-macros/tests/ui/config_no_parameters.stderr
src/riot-rs/src/lib.rs

This attribute macro allows to register specific functions for customizing the initial driver setup.

feat(config): add a `config` attribute macro

---

Cargo.lock
src/riot-rs-embassy/Cargo.toml
src/riot-rs-embassy/src/blocker.rs

riot-rs-embassy's `blocker` module depended on `riot-rs-core`, just to use it's re-export of `riot-rs-threads`. This PR makes it depend directly on `riot-rs-threads`.

riot-rs-embassy: switch from `riot-rs-core` to `riot-rs-threads`

---

CODE_OF_CONDUCT.md
book/src/COC_reporting.md
book/src/CODE_OF_CONDUCT.md
book/src/SUMMARY.md

This adds a code of conduct based on Django's to the project. It is using a symlink for the COC file for the mdbook as mdbook doesn't seem to handle mdfiles in parent directories

Add Code of Conduct

---

.github/workflows/main.yml
rust-toolchain

Prevents this nightly breakage:
```
error: concrete type differs from previous defining opaque type use
--> src/riot-rs-embassy/src/usb.rs:23:5
|                                                                                                                                                           
23 |     #[embassy_executor::task]
|     ^^^^^^^^^^^^^^^^^^^^^^^^^ expected `usb_ncm_task::Fut`, got `impl Future<Output = !>`
|                                                                           
note: previous use here                                                                                                                                          --> src/riot-rs-embassy/src/usb.rs:23:5 …
```

pin toolchain to nightly-2024-03-11

---

.github/workflows/main.yml

ci: nightly report only for catchall job

---

.github/workflows/main.yml
Cargo.lock
laze-project.yml
src/riot-rs-boards/Cargo.toml
src/riot-rs-boards/nrf5340/Cargo.toml
src/riot-rs-boards/nrf5340/build.rs
src/riot-rs-boards/nrf5340/src/lib.rs
src/riot-rs-boards/nrf5340dk/Cargo.toml
src/riot-rs-boards/nrf5340dk/src/lib.rs
src/riot-rs-boards/src/lib.rs
src/riot-rs-embassy/Cargo.toml
src/riot-rs-embassy/src/arch/nrf52.rs
src/riot-rs-embassy/src/lib.rs
src/riot-rs-threads/src/arch/cortex_m.rs

This PR adds initial nrf5340 support.
~~- [ ] rename to nrf5340-app, support nrf5340-net~~ postponed
~~(darn, needs laze release & update)~~ (fixed)
Closes #167.
(includes #170)

initial Nordic nrf5340 / nrf5340dk support

---

src/riot-rs-threads/src/arch/cortex_m.rs

I stumbled over this when adding the nrf5340 (armv8), which silently failed at runtime.

riot-rs-threads: bail out on unspecified ARM variant

---

Cargo.lock
Cargo.toml

Workspace crates should be listed explicitly instead.

build(workspace): don't include all directories in `src`

---

src/riot-rs-threads/src/arch/cortex_m.rs
src/riot-rs-threads/src/lib.rs

These fixes the remaining warnings that I get on riot-rs-threads.

riot-rs-rt: add some `unsafe` to silence some `unsafe-op-in-unsafe-fn`

---

Cargo.lock
Cargo.toml
examples/benchmark/laze.yml
laze-project.yml
tests/README.md
tests/benchmarks/bench_sched_yield/Cargo.toml
tests/benchmarks/bench_sched_yield/README.md
tests/benchmarks/bench_sched_yield/laze.yml
tests/benchmarks/bench_sched_yield/src/main.rs
tests/benchmarks/laze.yml
tests/laze.yml

This PR adds a new folder hierarchy `tests/`, with `tests/benchmarks`, and a first benchmark that I probably ad-hoc coded 5 times already.

tests/benchmarks/bench_sched_yield: initial commit

---

examples/benchmark/src/main.rs

feat(benchmark-example): print benchmark errors if any

---

CODE_OF_CONDUCT.md

This commit changes the link to the Reporting Guidelines to the correct location in the CODE_OF_CONDUCT.md file. 
The old link was incorrect, it referred to a non-existent location.
Test the link, check if it is redirecting to the correct location.

COC: fix broken link to Reporting Guidelines

---

.github/workflows/rustdoc.yml

As GitHub Pages now support [deploying from Actions](https://github.blog/2022-08-10-github-pages-now-uses-actions-by-default/), this uses the [deploy-pages](https://github.com/actions/deploy-pages) Action instead of the strategy currently used for the book.

ci: build and publish rustdoc

---

.github/workflows/build-deploy-docs.yml

`$default-branch` can only be used in workflow templates, not in workflows, see
https://docs.github.com/en/actions/using-workflows/creating-starter-workflows-for-your-organization

ci(docs): fix the workflow trigger conditions

---

.github/workflows/build-deploy-docs.yml
.github/workflows/main.yml
src/riot-rs/src/lib.rs

docs(riot-rs): show the `thread` module in docs

---

Cargo.lock
Cargo.toml

This includes stm32 `OptionalPeripherals` re-export.

bump embassy to for-riot-rs-100424

---

.github/workflows/build-deploy-docs.yml
.github/workflows/main.yml
Cargo.lock
Cargo.toml
examples/laze.yml
examples/random/Cargo.toml
examples/random/README.md
examples/random/laze.yml
examples/random/src/main.rs
laze-project.yml
src/riot-rs-embassy/Cargo.toml
src/riot-rs-embassy/src/arch/nrf52.rs
src/riot-rs-embassy/src/lib.rs
src/riot-rs-random/Cargo.toml
src/riot-rs-random/src/lib.rs
src/riot-rs/Cargo.toml
src/riot-rs/src/lib.rs

This is <del>a first jab at</del> supporting OS level RNG, <del>based on the CoAP branch</del> because that needs it.
<del>For a first coarse review please consider the latest two commits; if that first stage is passed, I'll rebase it to be usable without CoAP.</del>
Closes: https://github.com/future-proof-iot/RIOT-rs/issues/231

Add random number generator infrastructure

---

src/riot-rs-random/src/lib.rs
src/riot-rs/Cargo.toml

The second parameter of `*fill*()` functions has to be named `dest` because the documentation of these is provided on the trait and names that parameter that.
depends on #257

docs(random): fix a few typos and minor docs issues

---

.github/workflows/main.yml

`cargo rustdoc` only generates docs for the root crate, not its dependencies, `cargo doc` does.
depends on #257

ci(rustdoc): lint all crates for rustdoc errors

---

src/riot-rs-threads/src/arch/cortex_m.rs
src/riot-rs-threads/src/lib.rs

This is taken from #182: 
```
Setting threads.current_id to the very first running thread is now done within sched when the thread actually starts running. Before, this was done already in start_threading, but it caused some problems in the RISC-V implementation because then we couldn't differentiate between the thread running for the first time and current_id == next_id. I've tested on both arch'es and it still works with this change, so I think it should be alright?
```
This changes makes the number of cycles needed for one context switch go up from 254 to 259 (according to tests/benchmarks/bench_sched_yield on nrf52840dk). With the added line in `sched()` *after* the loop (instead of putting it in both cases), it'd go up to 261 cycles.
Fixes #148.

riot-rs-threads: always set `threads.current_thread` in `sched()`

---

src/riot-rs-threads/src/arch/cortex_m.rs
src/riot-rs-threads/src/arch/mod.rs
src/riot-rs-threads/src/lib.rs

This PR moves reading of PSP into `sched()`, and drops the need for the SVCall dance for `start_threading()`.
PendSV / sched now just handle the no-thread case properly.
This change seems a bit more intrusive ... It does, for some reason, reduce cycle count for `bench_sched_yield` (on nrf52840dk) from 259 to 229 (and from 90 to 75 in if there's only one thread).
Fixes #148. (next try. :) )

riot-rs-threads: cortex-m: make `sched()` deal with no previous thread

---

Cargo.lock
Cargo.toml

Not needed anymore since the switch to embassy.

cleanup: drop use of patched nrf-pacs

---

laze-project.yml

As builders are contexts, it makes sense to expose them as such as well.
We'll need this for the board setup file, so we don't have to treat the builder (i.e., the board name) separately.

feat(laze): expose `builder` as cfg context

---

src/riot-rs-embassy/src/lib.rs

This constructs is a bit longer, but it makes it more obvious what needs to be done when adding a new arch module.
It also provides a better error message if the architecture is not supported.

refactor(arch): use `cfg_if` to select the arch module

---

src/riot-rs-embassy/src/arch/dummy/gpio.rs
src/riot-rs-embassy/src/arch/dummy/mod.rs
src/riot-rs-embassy/src/arch/esp/gpio.rs
src/riot-rs-embassy/src/arch/esp/mod.rs
src/riot-rs-embassy/src/arch/nrf/gpio.rs
src/riot-rs-embassy/src/arch/nrf/mod.rs
src/riot-rs-embassy/src/arch/rp2040/gpio.rs
src/riot-rs-embassy/src/arch/rp2040/mod.rs
src/riot-rs-embassy/src/lib.rs

The gpio modules need to be re-exported under `arch`, so that we can access the relevant one when codegening sensor initialization.

feat(arch): re-export Embassy gpio modules

---

examples/embassy-usb-keyboard/laze.yml
examples/embassy-usb-keyboard/src/pins.rs

Pinout taken from the board's back side.
---
I appreciate the choice of keystrokes sent. I may submit a patch later to s/t/u/ -- after all, we're in constrained environments here.

examples/usb-keyboard: Add nrf5340dk support

---

laze-project.yml

`-Ctarget-cpu=cortex-m4` actually enables hard floats [1], which should not be enabled on the `thumbv7m-none-eabi` target.
[1]: https://github.com/rust-lang/rust/blob/6acb9e75ebc936df737381a9d0b7a7bccd6f0b2f/compiler/rustc_target/src/spec/targets/thumbv7em_none_eabi.rs#L9
---
Tested only on nRF52840, not sure whether we should replace this with something else.

fix(floats): disable hard floats on thumbv7m-none-eabi

---

.github/workflows/main.yml

As we get ready to have Python scripts in the repo, this introduces ruff, a fast linter for Python written in Rust.

ci(lints): use ruff to check Python formatting

---

.github/workflows/main.yml
Cargo.lock
Cargo.toml
examples/coap/Cargo.toml
examples/coap/README.md
examples/coap/fauxhoc.py
examples/coap/laze.yml
examples/coap/src/main.rs
examples/coap/src/seccontext.rs
examples/coap/src/udp_nal/mod.rs
examples/coap/src/udp_nal/util.rs
examples/laze.yml

As part of the [detailed CoAP road map](https://github.com/future-proof-iot/RIOT-rs/issues/226), I'd like to establish an in-tree example of CoAP use.
This is a draft PR until it does anything CoAP related; as soon as that is the case, I'd like to keep it close to main by extending that example continuously through small PRs rather than working on a long-lived branch.
<del>Currently this is based on #224, because that's the hardware I test on.</del>
```
$ ./laze build -b particle-xenon -s probe-rs-run --disable silent-panic run &
$ python3 fauxhoc.py
Received MSG2 with c_r=3 id_cred_r=b'\n' ead_2=None
[lib/src/edhoc.rs:644:5] &id_cred_i = [
161,
4,
65,
43,
]
Derived master_secret=b'gi\x16\x9d\x80j\xf7\xd9\xcehE\x9e\x87\xa0s\xb0' master_salt=b'\x1a\x9a\x0f\x8dv"|\xf2' …
```

Establish CoAP playground

---

src/riot-rs-debug/src/lib.rs

This still silently truncates prints, but during printf debugging, those are still understood more easily than skipped lines.
---
We're probably migrating to something more defmt anyway, but this fixes a repeated issue I've been running into when I thought my code is in weird branches just because the printf("Stage 1 {:?}", ...) silently didn't do anything at all.
(At some point we'll probably have similar high-level stdio discussions as in riot-c regarding whether to block and what to do in ISRs, but this is just a small step here and shouldn't touch the controversial topics).

stdio/rtt: Don't silently drop println statements

---

Cargo.lock
Cargo.toml

This bumps embassy to `56a7b10064b830b1be1933085a5845d0d6be5f2e` from Apr. 29th, plus our embassy patches.
Let's see what CI says.

deps: bump embassy

---

src/riot-rs-threads/src/arch/cortex_m.rs

This moves the previusly manual critical section into `sched()`, and uses a "u128" to pass our values to the assembly.
(this adds an instruction or two, but on nrf52840dk, this is barely measurable).

riot-rs-threads: cortex_m: make `sched()` less hacky

---

examples/core-sizes/src/main.rs
src/riot-rs-threads/src/lib.rs
src/riot-rs-threads/src/thread.rs

Make internal types in `riot-rs-threads` private.
Especially `THREADS`/ `Threads` doesn't need to be public

threads: restrict visibility

---

Cargo.lock
examples/laze.yml
examples/threading-channel/Cargo.toml
examples/threading-channel/README.md
examples/threading-channel/laze.yml
examples/threading-channel/src/main.rs

Demonstrate the usage of a channel for message passing between threads.
See https://github.com/future-proof-iot/RIOT-rs/pull/183#issuecomment-1999231583 and https://github.com/future-proof-iot/RIOT-rs/pull/152#discussion_r1537551699.

examples: add new `threading-channel` example

---

src/riot-rs-embassy/build.rs
src/riot-rs-embassy/src/arch/nrf/mod.rs
src/riot-rs-embassy/src/arch/rp2040/mod.rs
src/riot-rs-embassy/src/executor_swi.rs
src/riot-rs-embassy/src/lib.rs

This PR tries to make the incoming wave of different SWI choices more managable.
- add `executor_swi!(NAME)`-macro (reduces code duplication, see e.g., `arch/nrf/mod.rs`)
- adds logic to `build.rs` that, if set, generates a `swi.rs` that basically just contains `executor_swi!(NAME)` with `NAME` taken from the env variable `CONFIG_SWI`. This will be used in #237.

riot-rs-embassy: improve `SWI` selection

---

README.md
laze-project.yml
tests/benchmarks/bench_sched_yield/README.md

This PR intents to unify `laze run` across our devices.
it:
- removes the `silent-panic` dep from `release` (so panics are now shown by default)
- makes nrf & rp select `?probe-rs-run` (making it the default)
- renames `probe-rs-run` to just `probe-rs`, keeping an alias to `probe-rs-run`
- updates the docs to drop `-s probe-rs-run`
- *edit* also default to using the debug-console on esp32
*edit* I expect this to get another overhaul when [laze supports tasks defined by modules](https://github.com/kaspar030/laze/issues/420).
Fixes #200.

laze: change defaults around `run`

---

Cargo.lock
src/riot-rs-threads/Cargo.toml
src/riot-rs-threads/src/arch/cortex_m.rs
src/riot-rs-threads/src/arch/mod.rs
src/riot-rs-threads/src/arch/riscv.rs
src/riot-rs-threads/src/lib.rs

Initial support for threading on RISCV.
For now this only supports the `esp32c3` and `esp32c6` boards since we depend on specific features from `esp-hal`.
Adding support for other esp boards can be done in follow up PRs. 
Most of the changes are only within the new `riscv` module, but one general change I'd like to mention:
- Setting `threads.current_id` to the very first running thread is now done within `sched` when the thread actually starts running. Before, this was done already in `start_threading`, but it caused some problems in the RISC-V implementation because then we couldn't differentiate between the thread running for the first time and `current_id == next_id`. I've tested on both arch'es and it still works with this change, so I think it should be alright?
Note: I have not …

threads: add support for RISC-V (esp32 only)

---

Cargo.lock
Cargo.toml
src/riot-rs-embassy/Cargo.toml
src/riot-rs-embassy/src/arch/esp/mod.rs
src/riot-rs-threads/src/arch/riscv.rs

This bumps the esp crates to the latest released version (plus our `OptionalPeripherals` patch).

deps: update to esp-hal 0.17, esp-wifi 0.51

---

Cargo.lock
Cargo.toml

The upstream usbd-hid repo is now depending on byteorder 1.5.0, but has not released a release yet.

deps: switch to the upstream usbd-hid repo

---

src/riot-rs-embassy/src/arch/dummy/mod.rs
src/riot-rs-embassy/src/arch/esp/mod.rs
src/riot-rs-embassy/src/arch/nrf/mod.rs
src/riot-rs-embassy/src/arch/rp2040/mod.rs
src/riot-rs-embassy/src/lib.rs

This PR drops the `config` argument from the architecture's `init()` function, and moves it in there where needed.
The reason is that we passed `default()` anyways, esp doesn't use it at all, (dummy neither), and [stm32](#237) will actually need per-MCU Config handling.

riot-rs-embassy: move `Config` handling into arch modules

---

src/riot-rs-macros/src/thread.rs
src/riot-rs-macros/src/utils.rs

... that allows using the macro from a crate that is used as dependency of `riot-rs`, e.g., most riot-rs internal crates.

riot-rs-macros: make `thread` macro support both `riot-rs` and `riot-rs-threads` as deps

---

src/riot-rs-threads/src/arch/cortex_m.rs

Fixes Cortex-M `sched()` not seeing changes to the runqueue.
See https://github.com/future-proof-iot/RIOT-rs/issues/310#issuecomment-2150039448.
As to why the fence is necessary, I cannot explain. The critical section should actually imply a fence. In this case, the runqueue accesses are heavily inlined, so maybe something is off with the optimizer. Or, we're doing something wrong with how we access `THREADS`, which is a lot more likely than a compiler bug. :smirk:

riot-rs-threads: cortex-m: add compiler fence around `wfi` dance

---

Cargo.lock
Cargo.toml
src/riot-rs-embassy/Cargo.toml
src/riot-rs-embassy/src/arch/esp/mod.rs

Upstream has changed their repo setup.
- `esp-wifi` is now part of `esp-hal`
- embassy support has been factored out into `esp-hal-embassy`
- some API changes: https://github.com/esp-rs/esp-hal/releases/tag/v0.18.0

build(deps): bump to esp-hal 0.18+ monorepo

---

src/riot-rs-embassy/src/arch/esp/mod.rs

Fixes:
```
warning: unused import: `systimer::SystemTimer`
--> src/riot-rs-embassy/src/arch/esp/mod.rs:6:13                                                                                                              
|                                                                                                                                                            
6 |     timer::{systimer::SystemTimer, timg::TimerGroup},                                                                                                      
|             ^^^^^^^^^^^^^^^^^^^^^                                                                                                                          
|
= note: `#[warn(unused_imports)]` on by default
```
... which I caused with #318.

riot-rs-embassy: arch/esp: shuffle uses, fix warning

---

.github/pull_request_template.md
.github/workflows/ISSUE_TEMPLATE/bug_report.yml
.github/workflows/ISSUE_TEMPLATE/config.yml
.github/workflows/ISSUE_TEMPLATE/enhancement.yml
.github/workflows/ISSUE_TEMPLATE/feature-request.yml

Add Issue and PR templates to help contributors.
I've used the [beta issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms) for the issue templates, but I can change it back to traditional markdown if you prefer that.
I drafted the templates based on what I saw in other projects, feel free to suggestion changes.

.github: Add templates for PRs and Issues

---

Cargo.lock
examples/benchmark/laze.yml
examples/core-sizes/laze.yml
examples/embassy/laze.yml
examples/hello-world/laze.yml
examples/random/laze.yml
examples/threading-channel/laze.yml
examples/threading/laze.yml
laze-project.yml
src/riot-rs-embassy/Cargo.toml
src/riot-rs-embassy/src/arch/esp/mod.rs
src/riot-rs-embassy/src/arch/nrf/mod.rs
src/riot-rs-embassy/src/arch/rp2040/mod.rs
src/riot-rs-embassy/src/lib.rs
src/riot-rs-embassy/src/thread_executor.rs
src/riot-rs-rt/src/lib.rs
src/riot-rs-utils/src/env.rs
src/riot-rs/Cargo.toml

This PR adds an `Executor` that runs inside of a `riot-rs-threads` thread.
It also introduces laze modules for selecting an executor (`executor-interrupt, -thread, -single-thread, -none`) and new capability `sw/threading`.
Marking as draft as some dependency PRs are missing and this need proper testing.
Depends on ~~#303~~, ~~#312~~, ~~#313~~.

riot-rs-embassy: introduce thread mode executor

---

Cargo.lock
Cargo.toml
book/src/SUMMARY.md
book/src/tooling/defmt.md
book/src/tooling/index.md
laze-project.yml
src/riot-rs-debug/Cargo.toml
src/riot-rs-debug/src/lib.rs
src/riot-rs-embassy/Cargo.toml
src/riot-rs/Cargo.toml

This PR adds initial defmt support.
On Cortex-M, this currently co-exists with `rtt-target` through `defmt-rtt-target`. Output is line-wise intermingled, seems like probe-rs gets data from the buffers in practically arbitrary order.
Depends on #294.
TODO:
~~This is in *very* early stages.~~
~~Currently, I'm trying to figure out if the previous `println!()` can be supported together with defmt, as defmt-rtt conflicts with rtt-target.~~

add defmt support

---

Cargo.lock
examples/laze.yml
examples/usb-serial/Cargo.toml
examples/usb-serial/README.md
examples/usb-serial/laze.yml
examples/usb-serial/src/main.rs

This adds a usb serial example.
It is basically a port of one of Embassy's [examples](https://github.com/embassy-rs/embassy/blob/main/examples/stm32h7/src/bin/usb_serial.rs).
I tested that it works, with Linux as host, on nrf52840dk, rpi-pico and two stm32 (which are not in main yet).

feat(examples): add `usb-serial` example

---

Cargo.lock
src/riot-rs-runqueue/Cargo.toml
src/riot-rs-runqueue/src/runqueue.rs
src/riot-rs-threads/Cargo.toml
src/riot-rs-threads/src/thread.rs
src/riot-rs-threads/src/thread_flags.rs
src/riot-rs/Cargo.toml

Derive `defmt::Format` for `ThreadId`, `RunqueueId` and `ThreadState` if the `defmt` feature is enabled.
Useful for debugging.
@kaspar030 why are we not using `defmt::println` when `defmt` is enabled? 
I noticed that it results in some chronologically incorrect logs when `println` from other backends is combined with `defmt`. If I remember correctly we had a discussion around this and decided to "all in" for defmt if the feature is enabled. Am I missing something? If not, I would do a follow up PR that switches to `defmt::println`.

feat(threads, runqueue): derive `defmt::Format` for some types

---

.github/workflows/main.yml

I noticed that `riot-rs-runqueue` is missing in the CI crate tests, and `riot-rs-runqueue` in the CI clippy check.
This PR adds them.
Was there are reason why the packages weren't added to the list in these two cases?

feat(CI): add some missing package checks

---

.github/workflows/main.yml
book/src/SUMMARY.md
book/src/hardware_functionality_support.md
book/src/support_matrix.html
doc/gen_support_matrix_html.rs
doc/support_matrix.yml

This introduces a structured data file encoding current hardware and functionality support across supported chips and boards, along with a [Cargo script](https://github.com/rust-lang/cargo/issues/12207) generating HTML from this structured data. The generated HTML is written to a file which is imported into the book, providing comprehensive support information for potential users. That HTML file must be re-generated when the structured data file is updated, but a CI lint check makes sure that this HTML file is always up to date.
This support table covers hardware support as well as software/configuration support.
This is mostly meant to bootstrap this compatibility table and support information definitely incomplete. It must still reflect the current state of support at the time of merge. …

docs(book): add an initial version of the support matrix

---

Cargo.lock
book/src/tooling/defmt.md
examples/laze.yml
examples/log/Cargo.toml
examples/log/README.md
examples/log/laze.yml
examples/log/src/main.rs
laze-project.yml

~~(I'd like to discuss this)~~
This PR adds handling of `DEFMT_LOG` with laze.
This allows adding filter clauses both in laze files and on the command line, e.g.,
```shell
```
and
```yaml
modules:
- name: usb-trace
env:
global:
LOG:
- riot_rs_embassy::usb=trace
- other_crate::some_module=trace
```

handle log level with laze, enable defmt with info log level by default

---

src/riot-rs-macros/src/task.rs

The pool size was always specified in the Embassy `task` macro, in the generation code, but when the `autostart` and the `pool_size` parameters were not specified to the `riot_rs::task` macro, the pool size expression passed to that underlying Embassy task macro was a `None`, making the compilation fail with a syntax error in the generated code.
Fixes #352
None

fix(task-macro): make the `riot_rs::task` macro work with no parameters

---

.github/workflows/main.yml

STM32 builds would only be tested as part of the nightly CI, this enables testing some of the boards on each PR.
N/A
None

ci(stm32): enable testing for some STM32 boards when making PRs

---

laze-project.yml

All supported stm32 are Cortex-M, so they also support the SysTick based benchmark implementation.

fix(laze): add `stm32` to the implementors of `sw/benchmark`

---

src/riot-rs-threads/src/arch/cortex_m.rs

Adds a workaround for a nasty stm32 silicon bug.
See https://cliffle.com/blog/stm32-wfi-bug/ for more info.

fix(threads): add stm32 wfi bug workaround

---

examples/benchmark/Cargo.toml
examples/coap/Cargo.toml
examples/core-sizes/Cargo.toml
examples/embassy-http-server/Cargo.toml
examples/embassy-net-tcp/Cargo.toml
examples/embassy-net-udp/Cargo.toml
examples/embassy-usb-keyboard/Cargo.toml
examples/embassy/Cargo.toml
examples/hello-world-async/Cargo.toml
examples/hello-world/Cargo.toml
examples/log/Cargo.toml
examples/minimal/Cargo.toml
examples/random/Cargo.toml
examples/threading-channel/Cargo.toml
examples/threading/Cargo.toml
examples/usb-serial/Cargo.toml
src/lib/clist/Cargo.toml
src/lib/coapcore/Cargo.toml
src/lib/coapcore/src/seccontext.rs
src/lib/rbi/Cargo.toml
src/lib/ringbuffer/Cargo.toml
src/riot-rs-random/Cargo.toml
tests/benchmarks/bench_sched_yield/Cargo.toml

- This should avoid mistakes which are supposed to be prevented by
workspace lints.
- Fix one lint error found.
**Not all crates are currently checked by clippy, later PRs will add other crates to the list of crates checked by clippy and fix the lint errors found.**
None

chore: inherit workspace lints in every crate

---

.github/workflows/hax.yml

Update the pinned hax version in our CI to the most recent hax main (ref 533f87048f68705e8884ff9516db1371e8a2773d). 
Since d10f891a19f96bcafa9e31b1d78763e4f3cf30b4 some features have been added, among them support for the `let else` pattern that is used in #370.
See https://github.com/future-proof-iot/RIOT-rs/pull/370#issuecomment-2268565127.
Unblocks #370.

chore(ci/hax): update github action to hax ref 533f870

---

examples/blinky/src/main.rs
examples/blinky/src/pins.rs
examples/coap/src/main.rs
examples/embassy-http-server/src/main.rs
examples/embassy-http-server/src/pins.rs
examples/embassy-net-tcp/src/main.rs
examples/embassy-net-udp/src/main.rs
examples/embassy-usb-keyboard/src/main.rs
examples/embassy/src/main.rs
examples/gpio/src/main.rs
examples/gpio/src/pins.rs
examples/usb-serial/src/main.rs
src/riot-rs-macros/src/config.rs
src/riot-rs-macros/src/spawner.rs
src/riot-rs-macros/src/task.rs
src/riot-rs-macros/tests/ui/config/conflicting_config_kind.rs
src/riot-rs-macros/tests/ui/config/misspelled_config_kind.rs
src/riot-rs-macros/tests/ui/config/no_parameters.rs
src/riot-rs-macros/tests/ui/spawner/async_fn.rs
src/riot-rs-macros/tests/ui/spawner/missing_peripherals_param.rs
src/riot-rs-macros/tests/ui/spawner/no_autostart_param.rs
src/riot-rs-macros/tests/ui/task/missing_autostart_param_for_hook.rs
src/riot-rs-macros/tests/ui/task/misspelled_hook_name.rs
src/riot-rs/src/lib.rs
tests/gpio-interrupt-nrf/src/main.rs
tests/gpio-interrupt-stm32/src/main.rs
tests/gpio/src/main.rs
tests/gpio/src/pins.rs

The first commits keeps the `embassy` module for backward compatibility, but hides it from documentation.
The second one removes all uses and removes the `embassy` module entirely.
~~Should we rewrite every uses of the `embassy` modules as part of this PR, or shall we do this gradually?~~ There were fewer uses than I anticipated, so I just went with it and removed them all.

refactor!: remove the embassy module and all its uses

---

examples/blinky/Cargo.toml

The `external-interrupts` Cargo feature was unnecessarily enabled for the `blinky` example. This PR disables it.

fix(blinky): blinky does not need `external-interrupts`

---

.github/workflows/main.yml

`cargo-deny` installation could fail in CI when the binary was restored from a previous run. Using `--force` forces the installation in that case.

ci(cargo-deny): force the installation when already restored from cache

---

src/riot-rs-macros/src/spawner.rs

The `peripherals` macro parameter is required so that the decorated function gets called with a second parameter, to be able to obtain peripherals.

docs(spawner-macro): add a missing parameter in a doc example

---

Cargo.toml

It is our opinion that the `release` profile should be reserved for production builds.
This makes the `dev` profile suitable for low-Flash targets we support, and will allow us to leverage `debug_assert!`s in debug builds.
Documentation of Cargo profiles can be found here: https://doc.rust-lang.org/cargo/reference/profiles.html

build(profiles): make the `dev` profile suitable for embedded

---

Cargo.lock
Cargo.toml
src/riot-rs-threads/src/threadlist.rs
tests/laze.yml
tests/threading-lock/Cargo.toml
tests/threading-lock/laze.yml
tests/threading-lock/src/main.rs

Insert new threads in `ThreadList` based on priorities, so that the highest priority thread is the head.
Within a priority the threads are ordered in FIFO.
This reduces priority inversions, and will facilitate proper priority inheritance in the future.
The drawback of this change is that inserting a new Id in the `ThreadList` is now more complex. Not sure if we can avoid this in any way.
Alternative to #371, which implements the `ThreadList` as pure FIFO.

feat(threads): sort `ThreadList` by priority

---

src/riot-rs-threads/src/arch/cortex_m.rs

I noticed that threading on the nrf5340 is currently broken/ hard faults.
Some debugging showed that the problem is that on run, the `PendSV` tries to stored the r4-r11 registers in a null pointer.
This didn't cause any problems on the rpi-pico or nrf54840, but apparently for the nrf5340/ CortexM33  it's problematic.
To fix this, we have to skip storing/ loading of r4-r11 if the pointer is zero, i.e. when there was no previously running thread whose context has to be saved.
An alternative would be to directly in the `sched` code when `current_pid.is_none()` return 0 so that no context save/ reload happens, but then the `psp` update would also be skipped and we'd manually have to do that before returning the `0`.
The PR also includes some small optimizations/ clean-ups in `sched`.
The bug …

fix(threads/cortex_m): don't save high regs on first schedule

---

Cargo.lock
Cargo.toml
deny.toml
examples/coap/Cargo.toml

Found in #413 when wiring up `random` for rp showed that `scroll-ring`, `static-alloc` and `try-lock` were depending on Atomic CAS for types the armv6 doesn't support.

fix(armv6): make `coap` example deps use portable atomics

---

.github/workflows/hax.yml
Cargo.lock
src/riot-rs-runqueue/Cargo.toml
src/riot-rs-runqueue/src/runqueue.rs

Support for `Default` has been added in https://github.com/hacspec/hax/pull/891

refactor(runqueue): implement `Default` now that hax supports it

---

Cargo.lock
Cargo.toml
examples/embassy-http-server/src/main.rs
rust-toolchain.toml
src/lib/coapcore/src/lib.rs
src/riot-rs-embassy/src/lib.rs
src/riot-rs-nrf/src/lib.rs
src/riot-rs-rp/src/lib.rs
src/riot-rs-runqueue/src/lib.rs
src/riot-rs-threads/src/lib.rs

This PR bumps the Rust toolchain to `nightly-2024-09-16`.
It points the `embassy-executor` tip to a commit updating some wakers API to above's nightly.
Also, all `#[feature(lint_reasons)]` are removed (that feature is now stable).

chore(build): bump Rust toolchain

---

Cargo.toml

`unsafe_op_in_unsafe_fn` is expected to be set to `warn` in the 2024 Rust edition [1], thus asserting that the previously accepted usage of the `unsafe` keyword on functions allowing the use of `unsafe` operations without `unsafe` blocks is deprecated.
We therefore enforce this by setting this lint to `deny` instead of `warn`.
[1]: https://doc.rust-lang.org/edition-guide/rust-2024/unsafe-op-in-unsafe-fn.html

chore(rustc-lint): set `unsafe_op_in_unsafe_fn` to `deny`

---

src/riot-rs-rt/linkme.x

Adds some missing `linkme.x` entries. This worked without before, but on toolchains >=nightly-2024-08-01, not anymore.
Fixes #422.

fix(rt): add missing linkme.x entries

---

laze-project.yml
src/riot-rs-embassy/Cargo.toml
src/riot-rs-stm32/build.rs
src/riot-rs-stm32/src/lib.rs

That mode has been broken during #392

fix(stm32): fix the executor-interrupt mode

---

Cargo.lock
examples/embassy-http-server/Cargo.toml
examples/embassy-http-server/src/main.rs
examples/embassy-http-server/src/routes/index.rs
examples/embassy-http-server/src/routes/mod.rs

Bumps the dependency. `File` doesn't impl `IntoResponse` anymore, so updating that was needed.

feat(examples): bump picoserve to 0.12.x

---

src/riot-rs-threads/src/channel.rs
src/riot-rs-threads/src/lib.rs
src/riot-rs-threads/src/lock.rs
src/riot-rs-threads/src/threadlist.rs

Add some missing documentation about possible panics in `riot-rs-threads` when a function is expected to be called only inside a thread context.
Avoid panics where possible through early returns. 
Also adds some documentation for `Channel`.
Extracted from https://github.com/future-proof-iot/RIOT-rs/pull/381#discussion_r1721324000.
- @ROMemories you proposed in https://github.com/future-proof-iot/RIOT-rs/pull/381#discussion_r1721324000 to use `NOTE(no-panic)`-style comments to document why an `unwrap` can't panic. I've instead used `expect`, because we a) don't know that it will never panic (it's the callers responsibility) and b) it prints the comment as part of the panic message. Wdyt?
- > Avoid panics where possible through early returns. 
This concerns the functions `yield_same` and …

refactor(threads): improve panic handling and docs

---

.github/workflows/main.yml

Now that CI is free of clippy warnings, we can forbid them in CI, so they don't creep in again.
This does seem to print every encountered warnings/errors when found in the same crate; however it does seem to return early when linting multiple crates at a time and encountering a warning/error.
See this [clippy discussion for details](https://github.com/rust-lang/rust-clippy/discussions/11942).

ci(clippy): fail the `lint` job on clippy warnings

---

Cargo.lock

It seems that #421 didn't update the `Cargo.lock` completely, this PR fixes that.

chore(i2c): update the `Cargo.lock` file

---

examples/coap/laze.yml

A clang stable update broke `liboscore`: https://gitlab.com/oscore/liboscore/-/issues/61
Temporarily disable `examples/coap` until fixed.
Potential fix: #443

chore(CI): temporarily disable `examples/coap`

---

.github/pull_request_template.md

I'm trying to be a good project citizen an occasionally read up on coding conventions even though I think that those would way better be enforced by clippy/cargo-fmt/some-other-tool (that provide a patch for me to merge rather than just complain) and read up on those from time to time.
Turned out the link was broken, this fixes it.
See the broken link on this issue in the checkboxes.

chore: Fix GitHub request template link to coding conventions

---

Cargo.lock
Cargo.toml
src/riot-rs-runqueue/src/lib.rs
src/riot-rs-runqueue/src/runqueue.rs
src/riot-rs-threads/src/lib.rs
tests/laze.yml
tests/threading-dynamic-prios/Cargo.toml
tests/threading-dynamic-prios/laze.yml
tests/threading-dynamic-prios/src/main.rs

Allow users to dynamically change thread priorities at runtime.
Fixes #320 
Depends on #437

feat(threads): dynamic thread priorities

---

src/riot-rs-embassy/src/delegate.rs

Add a previously missing lifetime bound on a `Delegate` method.

fix(delegate)!: add a required lifetime bound on `Delegate`

---

src/riot-rs-bench/src/cortexm.rs
src/riot-rs-bench/src/esp.rs
src/riot-rs-bench/src/lib.rs

Allow `FnMut` benchmark functions.

feat(bench): enable more benchmarks

---

examples/benchmark/Cargo.toml
examples/core-sizes/Cargo.toml
examples/embassy/Cargo.toml
examples/hello-world/Cargo.toml
examples/random/Cargo.toml
examples/threading-channel/Cargo.toml
examples/threading/Cargo.toml
laze-project.yml
tests/threading-dynamic-prios/Cargo.toml
tests/threading-lock/Cargo.toml

Enable the `riot-rs/threading` feature in the `sw/threading` laze module.
Users that select one will always want to select the other as well, so this avoids redundancy.
Extracted from #397

feat(laze): select `riot-rs/threading` in `sw/threading` module

---

Cargo.lock
Cargo.toml
tests/benchmarks/bench_sched_flags/Cargo.toml
tests/benchmarks/bench_sched_flags/README.md
tests/benchmarks/bench_sched_flags/laze.yml
tests/benchmarks/bench_sched_flags/src/main.rs
tests/benchmarks/laze.yml

Add new benchmark to test signaling between threads using `thread-flags`.
Compared to the existing benchmark `bench_sched_yield`, it involves IPC between the threads and one thread changing another thread's state.
Do we want this benchmark?

feat(tests/benchmarks): add `bench_sched_flags`

---

src/riot-rs-bench/Cargo.toml
src/riot-rs-debug/Cargo.toml

The `cortex-m` `critical-section-single-core` feature is enabled in `riot-rs-rt`, so no need to do it in other packages as well.

chore(*): remove redundant `critical-section` pick

---

src/riot-rs-runqueue/src/runqueue.rs
src/riot-rs-threads/src/lib.rs
src/riot-rs-threads/src/thread_flags.rs
src/riot-rs-threads/src/threadlist.rs

This PR implements some changes and checks to avoid unnecessary scheduler invocations:
- the scheduler is now triggered in `set_state` as a central point
- if a thread changes into `ThreadState::Running`, only trigger the scheduler if the thread has a higher priority than the currently running one (**new**)
- always trigger the scheduler when a thread changes from `ThreadState::Running` into another state because this only ever happens if a currently running thread gets blocked
- only trigger the scheduler in `yield_now` if the runqueue contains any other threads
(ticks **per iteration**)
`bench_sched_flags` is PR'd in #456
nRF52840dk: 
benchmark | main | this PR
| - | - | -
`bench_sched_yield` with two threads |  560 | 580
`bench_sched_yield` with one thread | 235 | …

refactor(threads): avoid unnecessary scheduler invocations

---

src/riot-rs-runqueue/src/lib.rs
src/riot-rs-runqueue/src/runqueue.rs

Add an iterator over the threads in `RunQueue`. The iterator can start from any thread and will then iterate over all succeeding threads in the same queue, and then all lower index queues one by one.
The motivation for this iterator is that then `Iterator::filter` + `Iterator::next` can be used to pick a thread from the runqueue that matches a certain condition. 
In the multicore PR #397 that's needed so that we can get the next thread from the runqueue that has the correct core-affinity.
Is there any simpler way to implement this?

feat(runqueue): add RunQueue iterator

---

src/riot-rs-nrf/src/i2c/controller/mod.rs
src/riot-rs-nrf/src/i2c/mod.rs
tests/i2c-controller/README.md
tests/i2c-controller/laze.yml
tests/i2c-controller/src/main.rs
tests/i2c-controller/src/pins.rs

Port the test for the micro:bit V2 board.
It just happens that the accelerometer found on the micro:bit V2 has the same `WHO_AM_I` register value than the other accelerometer we were using for testing I2C bus on other boards.
Depends on #463

feat(i2c-controller): add support for I2C controller on nrf52833

---

Cargo.lock
Cargo.toml
laze-project.yml
src/riot-rs-esp/Cargo.toml
src/riot-rs-esp/src/gpio.rs
src/riot-rs-esp/src/i2c/controller/mod.rs
src/riot-rs-esp/src/lib.rs
src/riot-rs-threads/src/arch/xtensa.rs
tests/threading-lock/Cargo.toml

Bumps esp-hal to `0.21.0` + our patches.
Depends on #399.

bump esp-hal to v0.21.0

---

src/riot-rs-esp/src/lib.rs
src/riot-rs-threads/src/arch/riscv.rs
src/riot-rs-threads/src/arch/xtensa.rs

Required for #397, because there the xtensa implementation is changed to use CPU Intr0 for single-core, and this should be unified for both RISC-V and Xtensa.
Required for #397.

refactor(threads): use CPU INTR0 for scheduler on esp

---

Cargo.lock
Cargo.toml
examples/laze.yml
examples/threading-multicore/Cargo.toml
examples/threading-multicore/README.md
examples/threading-multicore/laze.yml
examples/threading-multicore/src/main.rs
laze-project.yml
src/riot-rs-embassy/Cargo.toml
src/riot-rs-esp/Cargo.toml
src/riot-rs-esp/src/lib.rs
src/riot-rs-macros/src/thread.rs
src/riot-rs-rt/Cargo.toml
src/riot-rs-rt/src/cortexm.rs
src/riot-rs-rt/src/lib.rs
src/riot-rs-runqueue/src/runqueue.rs
src/riot-rs-threads/Cargo.toml
src/riot-rs-threads/src/arch/cortex_m.rs
src/riot-rs-threads/src/arch/mod.rs
src/riot-rs-threads/src/arch/riscv.rs
src/riot-rs-threads/src/arch/xtensa.rs
src/riot-rs-threads/src/autostart_thread.rs
src/riot-rs-threads/src/lib.rs
src/riot-rs-threads/src/smp/esp32s3.rs
src/riot-rs-threads/src/smp/mod.rs
src/riot-rs-threads/src/smp/rp2040.rs
src/riot-rs-threads/src/thread.rs
src/riot-rs/Cargo.toml
tests/threading-dynamic-prios/laze.yml

This PR adds support for symmetric multiprocessing (SMP) for `riot-rs-threads`. It's a refactor and continuation of #241.
Right now, only the RP2040 is supported. I am planning to also add support for esp32s3 in a follow-up PR.
The implementation follows a global scheduling approach where the highest _n_ ready threads are scheduled on the _n_ available cores. 
The main change in the scheduler logic is that it now removes the current thread from the runqueue, which is necessary so that a thread doesn't get picked twice. This also means that the thread has to be added to the runqueue again each time the scheduler is triggered (if it's still running). 
This introduces some overhead if the scheduler is triggered unnecessarily. The PR therefore also includes optimizations that make sure that …

feat(threads): multicore support 

---

book/book.toml
book/src/SUMMARY.md
book/src/tooling/coap.md

As per today's meeting, I've pulled ahead writing CoAP documentation to give all involved a better overview of how the security protocols interact.
Unlike what we otherwise do with the book, this is ahead of the implementation (covering some of the [roadmap](https://github.com/future-proof-iot/RIOT-rs/issues/226) but also some things not in there in the current iteration). As this matures, the annotation of "we don't have this yet" will move from page-wide into sections.
Should we aim for this to be merged with the disclaimer in, or do we rather keep it as a PR until most of it is implemented? I'm leaning toward the former, especially because the book is also a good reference for developers.

feat(docs): Add section on CoAP

---

.gitattributes

I noticed that github shows `book/src/support_matrix.html` diffs. That's not really helpful, it is fully generated and CI checked. So, add it to `.gitattributes` with some magic.
See [github docs](https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github) for background.

chore: mark `book/src/support_matrix.html` as generated

---

Cargo.lock
Cargo.toml

Fixes "RIOT-rs doesn't build for me anymore after running cargo update.
The reason is that it updates embassy-executor to v0.6.1, and that causes our patch to not be applied anymore because the version in the patch is v0.6.0."

chore(deps): update deps, add `embassy-executor-macros` patch

---

.github/workflows/main.yml

The approach in #491 to making Xtensa get off my lawn is to undo some of its environment tampering.
Instead, this goes a different route and makes the tampering less bad by ensuring that at least a clang-17 is installed. Turned out this needs nothing more than an Ubuntu update.

chore(CI): Update Ubuntu environment

---

.github/workflows/main.yml

The Xtensa toolchain sets a general `LIBCLANG_PATH`, which is part of what causes the clang troubles for libOSCORE (to be fixed in https://github.com/future-proof-iot/RIOT-rs/pull/443).
This approach <del>unsets it from the GitHub action environment</del>, and </del>will later set it specifically for the ESP builds on demand</del>.
[edit: added] Now we can't *unset* it from the GitHub actions because that just doesn't work, but we prepare a sourceable .profile style file that is then sourced by all relevant run scripts.
[edit, added:] … and it didn't even need that environment variable anywhere else 🤦
Yes: The alternative is to fork the Xtensa script and make it optional to export the variable.
Or fork GitHub runners and fix https://github.com/actions/runner/issues/1126 so that we can …

fix(CI): Keep Xtensa clang environment variables off the general system

---

.github/workflows/main.yml
Cargo.lock
examples/coap/laze.yml
src/lib/coapcore/Cargo.toml

This pulls in workarounds / fixes for clang-18, which would otherwise fail to define `uint8_t` & co in its stdint.h, causing bindgen failures.
Thanks @kaspar030 for noticing the issue and helping me reproduce it.
See-Also: https://gitlab.com/oscore/liboscore/-/issues/61
Depends on: https://github.com/future-proof-iot/RIOT-rs/pull/491
<del>Let's hope everyone can use clang-18 already: as the fix for using clang-18 requires a recent clang (didn't test -17, but -16 doesn't cut it), this may require updates here and there.</del>
<del> (Our documentation says to install clang on Ubuntu, but the latest Ubuntu LTS already has clang 18 by default, so that doesn't need an update.)</del>

fix(coapcore): Update liboscore dependency

---

.github/workflows/build-deploy-docs.yml

The `storage` feature was not enabled in CI by #277 so its docs were not rendered, this PR enables it.

ci(rustdoc): render the storage module docs

---

Cargo.lock
Cargo.toml

This bumps our `esp-hal` fork.
Mostly, this adds the extra GPIO support for esp32, needed for #467.
Also, changes the used branch name to not include a `+` anymore (see [cargo bug](https://github.com/rust-lang/cargo/issues/14779)).

feat(deps): bump `esp-hal` fork

---

src/riot-rs-macros/src/thread.rs

The `autostart` parameter was missing from the doc examples, this PR adds it back.

docs(thread-macro): add a missing param in the doc examples

---

src/riot-rs-esp/Cargo.toml

This propagates the `defmt` feature to the `esp-hal` crate; it's a follow-up to https://github.com/future-proof-iot/RIOT-rs/pull/392#discussion_r1738319808.
@kaspar030 Do you see a reason *not* to enable it?

fix(defmt-esp): enable `defmt` on `esp-hal` when requested

---

src/riot-rs-nrf/src/spi/main/mod.rs
src/riot-rs-nrf/src/spi/mod.rs
tests/spi-loopback/laze.yml
tests/spi-loopback/src/pins.rs

This adds support for SPI in main mode on the nRF52833, which we support since #463.
The `spi-loopback` test was successfully tested on a micro:bit V2. The `spi-main` test would later need to be updated when we get an easier access to the required pins on that board.

feat(spi-main): add support for SPI main on nRF52833

---

Cargo.lock
examples/blinky/Cargo.toml
examples/blinky/src/main.rs
examples/coap/Cargo.toml
examples/embassy-http-server/Cargo.toml
examples/embassy-http-server/src/main.rs
examples/embassy-net-tcp/Cargo.toml
examples/embassy-net-tcp/src/main.rs
examples/embassy-net-udp/Cargo.toml
examples/embassy-usb-keyboard/Cargo.toml
examples/embassy-usb-keyboard/src/main.rs
examples/gpio/Cargo.toml
examples/gpio/src/main.rs
examples/thread-async-interop/Cargo.toml
examples/thread-async-interop/src/main.rs
examples/usb-serial/Cargo.toml
src/riot-rs-embassy/src/lib.rs
src/riot-rs/Cargo.toml
tests/gpio-interrupt-nrf/Cargo.toml
tests/gpio-interrupt-stm32/Cargo.toml

Re-export the `embassy-time` crate in two different ways: as a blanket re-export in `riot_rs::reexports`, and as cherry-picked items in the newly created `riot_rs::time` module.
Extracted from https://github.com/future-proof-iot/RIOT-rs/pull/521#discussion_r1841260697.

feat(embassy-time): re-export the crate and relevant items

---

.github/workflows/main.yml
src/riot-rs-embassy/src/i2c/controller/mod.rs
src/riot-rs-embassy/src/lib.rs
src/riot-rs-embassy/src/usb.rs

Fix the few Clippy warnings that prevented enabling some more Cargo features on `riot-rs-embassy`, and enable them in CI.

ci(clippy): enable more Cargo features on `riot-rs-embassy`

---

Cargo.lock
examples/README.md
examples/laze.yml
examples/tcp-echo/Cargo.toml
examples/tcp-echo/README.md
examples/tcp-echo/laze.yml
examples/tcp-echo/src/main.rs

As part of https://github.com/future-proof-iot/RIOT-rs/issues/410, and similarly to #521, this PR:
- renames the `embassy-tcp-echo` example to `tcp-echo`, as agreed
- leverages `riot_rs::reexports`
- contains other minor cleanups.
Depends on #521.
Depends on #525.

docs(tcp-example): clean up the TCP example

---

examples/embassy-http-server/src/main.rs
examples/thread-async-interop/src/main.rs
src/riot-rs-embassy/src/asynch.rs
src/riot-rs-embassy/src/asynch/blocker.rs
src/riot-rs-embassy/src/lib.rs
src/riot-rs-macros/src/spawner.rs
src/riot-rs-macros/src/task.rs
src/riot-rs-macros/tests/ui/spawner/async_fn.rs
src/riot-rs-macros/tests/ui/spawner/missing_peripherals_param.rs
src/riot-rs-macros/tests/ui/spawner/no_autostart_param.rs

Previously, only when using the interrupt executor there was a way to get to a `Spawner` to spawn tasks from threads.
This PR makes the spawner available for all executors.
Also, refactors some previously global exports into `riot_rs::asynch`.
currently panics on dual core b/c the `spawner` is empty when the thread on the second core starts, thus draft.
Depends on #526.

feat(embassy): refactor async API, introduce `spawner()`

---

src/riot-rs-threads/src/arch/cortex_m.rs
src/riot-rs-threads/src/arch/riscv.rs
src/riot-rs-threads/src/arch/xtensa.rs
src/riot-rs-threads/src/lib.rs
src/riot-rs-threads/src/thread_flags.rs
src/riot-rs-threads/src/threadlist.rs

Rename the central  `Threads`/ `THREADS` structure in `riot_rs_threads` into `Scheduler`/ `SCHEDULER`.
IMO that's more intuitive given that the structure not just contains and implements the TCBs,  but instead all scheduling-related logic. And `threads` itself is again a property on this struct, so it  prevents confusion there (and having to write sth like `threads.threads`).
Any objections?

refactor(threads): rename `Threads` -> `Scheduler`

---

Cargo.lock
Cargo.toml
deny.toml
laze-project.yml
src/riot-rs-chips/stm32/Cargo.toml
src/riot-rs-debug/Cargo.toml
src/riot-rs-debug/src/lib.rs
src/riot-rs-rt/Cargo.toml
src/riot-rs/Cargo.toml

This PR overhauls `riot-rs-debug` a bit:
- make use of rtt-target's internal defmt support, drop use of our `defmt-rtt-target` fork
- use the semihosting crate instead of cortex-m::semihosting_syscall for `exit()`
Apart from dropping one self-managed fork, this enables `rtt-target` and `probe-rs` use on esp. This is a prerequisite for using `embedded-test`.
The previous `esp-println` backend is kept and still default on esp.

riot-rs-debug: bump rtt-target, drop defmt-rtt-target, make use of semihosting crate

---

src/riot-rs-random/src/lib.rs

Enforce `clippy::pedantic` on `riot-rs-random`.
Extracted from #279.

chore(pedantic): make Clippy happy with `riot-rs-random`

---

src/riot-rs-embassy-common/src/spi/main/mod.rs
src/riot-rs-rp/src/gpio.rs
src/riot-rs-rp/src/i2c/controller/mod.rs
src/riot-rs-rp/src/i2c/mod.rs
src/riot-rs-rp/src/lib.rs
src/riot-rs-rp/src/spi/main/mod.rs
src/riot-rs-rp/src/spi/mod.rs

This documents items relevant for users, and hides the others from documentation, to prepare for them being rendered in #531. 
Documentation for the `riot-rs-rp` crate can be rendered locally using the following:
https://github.com/future-proof-iot/RIOT-rs/blob/291e47ee2a3f66f3b167c2242255e812dff7582c/.github/workflows/main.yml#L405-L412
- PRs will follow to do the same for other HAL crates.
- **This PR hides the `OptionalPeripherals` type, and only exposes the `peripherals` module.** The documentation of the `define_peripherals!` macro will be updated in a future PR to not refer to `OptionalPeripherals` anymore, as it's not necessary and I think it would be better to treat it as an implementation detail.
- The relationship between the generic types (e.g., in `riot_rs::gpio`) and the …

 docs(rp-hal): document the `riot-rs-rp` HAL crate

---

Cargo.lock
laze-project.yml
src/riot-rs-boards/Cargo.toml
src/riot-rs-boards/espressif-esp32-wroom-32/Cargo.toml
src/riot-rs-boards/espressif-esp32-wroom-32/src/lib.rs
src/riot-rs-boards/src/lib.rs
src/riot-rs-debug/Cargo.toml
src/riot-rs-esp/Cargo.toml
src/riot-rs-esp/src/gpio.rs
src/riot-rs-esp/src/lib.rs
src/riot-rs-rt/Cargo.toml
src/riot-rs-threads/Cargo.toml
tests/gpio/src/pins.rs

This PR wires up the `espressif-esp32-wroom-32`.
Tested blinky, http-server, tests/gpio.
Depends on #442.

feat(esp): add support for esp32 & espressif-esp32-wroom-32

---

Cargo.lock
laze-project.yml
src/riot-rs-embassy/Cargo.toml
src/riot-rs-esp/Cargo.toml
src/riot-rs-esp/src/lib.rs
src/riot-rs-esp/src/usb/mod.rs
src/riot-rs-hal/Cargo.toml

This PR wires up USB support for the esp-hal based devices.
IIUC, only `esp32-s2` and `esp32-s3` have the needed peripheral, of which we only support the latter.
`usb-ethernet` is not working though. It is disabled via laze in this PR.
I tested `usb-serial`.

Wire up `ESP32-Sx` USB support

---

examples/README.md
examples/log/README.md
examples/log/src/main.rs

As part of https://github.com/future-proof-iot/RIOT-rs/issues/410, this PR:
- Adds the log example to the examples readme
- Extend the readme with some clarification
- Remove the `defmt` from the example
- Adds dashes to the printed logging to increase the distinction between the common RIOT-rs logging and the logging from the example
Part of #410

docs(log): Clean up the log example

---

.github/workflows/main.yml

This sets up cancelling previous CI runs. 
**Does this work for non-PR builds this way?**

ci: enable `cancel-in-progress` for PR builds

---

.github/workflows/build-deploy-docs.yml
src/ariel-os-hal/src/dummy/executor.rs
src/ariel-os-hal/src/dummy/mod.rs
src/ariel-os-hal/src/lib.rs

This generates the rustdoc docs for the manufacturer-specific crates (MSCs) that were extracted as part of #392.
The doc page of the `ariel_os::hal` module provides the user with a "manual redirect" to the items relevant for the target MCU, provided by the MSCs.
The current state of the generated docs can be seen on my fork: https://romemories.github.io/ariel-os/dev/docs/api/ariel_os/hal/index.html
**The documentation of the MSCs are currently rendered for one MCU only (and that MCU is not currently mentioned in the docs).** This is a significant limitation, but it's unclear how solve that in the general case (e.g., `ariel-os-stm32` may end supporting 1400 different MCUs).
E.g., the nRF5340 also supports 250 kHz as an I2C frequency, but [this does not currently appear in the …

ci(docs): render manufacturer-specific docs

---

Cargo.lock
examples/coap-client/Cargo.toml
examples/coap-client/src/main.rs
examples/coap-server/Cargo.toml
examples/coap-server/src/main.rs
src/lib/coapcore/Cargo.toml
src/lib/coapcore/src/seccontext.rs
tests/coap/Cargo.toml
tests/coap/src/main.rs

libOSCORE had bugs around the use of heap allocated prepared messages. With the updated version, we can drop the allocator from the examples.

feat(coap): Drop allocator

---

README.md

Back when we started the README, this made heavy use of nightly features.
Now we're down to type_alias_impl_trait / impl_trait_in_assoc_type from embassy (hopefully soon stable, or replacable with something stable in a pinch), used_with_arg (unclear), doc_auto_cfg (if all others are gone that can be cfg_attr'd), and naked_functions (unclear). "heavy use" is not the case any more.
A follow-up could codify the rough consensus that I think is not documented: That we only use features that can be either rolled back if need be, or are stable enough that we don't expect trouble (and there should be stabilization within like a year or two). But that's beyond scope -- having the README right is important for first impressions.

doc: Use of nightly features has been reduced

---

src/ariel-os-threads/src/arch/riscv.rs

Even though there is currently no SMP support for any RISC-V board, it is still possible to manually enable the riot-rs-threads `multi-core` Cargo feature for a RISC-V board (which doesn't bring any benefit, but it's may still be needed sometimes, e.g. for benchmarking). 
Thus this case needs to be handled in the RISC-V scheduler code. Concretely, this concerns the need to re-add the current thread to the runqueue when it is being preempted.

fix(threads): handle case RISC-V + multicore enabled

---

clippy.toml
src/ariel-os-hal/src/dummy/executor.rs
src/ariel-os-hal/src/dummy/gpio.rs
src/ariel-os-hal/src/dummy/i2c/controller.rs
src/ariel-os-hal/src/dummy/mod.rs
src/ariel-os-hal/src/dummy/usb.rs
src/ariel-os-hal/src/lib.rs

Enforce `clippy::pedantic` on `ariel-os-arch`.
Extracted from https://github.com/future-proof-iot/RIOT-rs/pull/279.

chore(pedantic): make Clippy happy with `ariel-os-hal`

---

src/ariel-os-hal/src/lib.rs

This adds a note to the `ariel_os::hal` module, attempting to discourage usage of the settings it provides, when possible for the application.
We unfortunately cannot have internal links between the generic items and the `hal` items because it would result in cyclic crate dependencies.

docs(hal): add a portability note regarding when to use `hal` items

---

src/ariel-os-embassy/src/define_peripherals.rs

#544, #545, #550, and #551 have hidden the `OptionalPeripherals` type (found in HAL crates) from users on purpose, making sure that the `peripherals` module was however visible. This PR removes mentions to that now-hidden type.

docs(macros): update the docs as `OptionalPeripherals` is now hidden

---

Cargo.lock
src/lib/coapcore/Cargo.toml

As libOSCORE is now fixed to also work from crates.io again, we can go to a released version. (We already were at the released code, using the tagged git rev, but it failed to build when checked out via crates.io).
Works around https://gitlab.com/oscore/liboscore/-/issues/62 on "there's a confusing git submodule skipped line in our build output" by not even using git.

chore: Update libOSCORE dependency to published version

---

.cargo/config.toml
Cargo.toml
laze-project.yml
patch.crates-io.toml

This moves the crates.io patches into another file that is then be parsed to Cargo via `--config`. This allows re-using the patches in out-of-tree builds.
For local tooling, the repo's `.cargo/config.toml` is modified to include the file via the unfortunately still unstable [config-include](https://github.com/rust-lang/cargo/issues/7723).
Fixes #524.

feat(build): pass `[patch.crates-io]` via extra cargo toml

---

Cargo.lock
Cargo.toml
src/ariel-os-threads/src/lib.rs
src/ariel-os-threads/src/sync/mod.rs
src/ariel-os-threads/src/sync/mutex.rs
src/ariel-os-threads/src/threadlist.rs
tests/laze.yml
tests/threading-mutex/Cargo.toml
tests/threading-mutex/laze.yml
tests/threading-mutex/src/main.rs

Add a mutex implementation analogous to the existing `Lock`, with additional priority inheritance.
Unfortunately I don't think we can directly reuse `Lock`, because we need access to the inner `ThreadList`.
The PR also moves all synchronization primitives into a new `sync` submodule. Any objections?
Issue: #321.
Depends on 
- #370 
- #381
- #452

feat(threads): add mutex with priority inheritance

---

src/ariel-os-embassy/src/gpio.rs
src/ariel-os-esp/src/gpio.rs
src/ariel-os-hal/src/dummy/gpio.rs
src/ariel-os-nrf/src/gpio.rs
src/ariel-os-nrf/src/i2c/controller/mod.rs
src/ariel-os-rp/src/gpio.rs
src/ariel-os-stm32/src/gpio.rs

This is for consistency with the generic `gpio` module, where `DriveStrength` and `Speed` are directly in the `gpio` module, not in `gpio::output`.
Tip for reviewing: using "Split Diff view" (instead of "Unified") and hiding whitespace changes makes this much nicer to review.

refactor(hal)!: move some GPIO HAL items for consistency

---

book/book.toml
book/src/SUMMARY.md
book/src/multithreading.md

Add chapter about multithreading in RIOT-rs to the book.
Depends on: 
- #397 
- #398 
Includes multicore features that are PR'd in #397, but not merged yet.

docs(threading): add multithreading book chapter

---

src/ariel-os-threads/src/sync/mod.rs
src/ariel-os-threads/src/sync/mutex.rs

`MutexGuard` is consistent with `std::sync::MutexGuard` and `embassy_sync::mutex::MutexGuard`.

refactor(threads)!: rename `Guard` to `MutexGuard` for consistency

---

Cargo.lock
examples/coap-client/src/main.rs
examples/coap-server/src/main.rs
examples/http-server/src/main.rs
examples/tcp-echo/src/main.rs
examples/udp-echo/src/main.rs
examples/usb-keyboard/src/main.rs
examples/usb-serial/src/main.rs
src/ariel-os-macros/src/config.rs
src/ariel-os-macros/tests/ui/config/conflicting_config_kind.rs
src/ariel-os-macros/tests/ui/config/conflicting_config_kind.stderr
src/ariel-os-macros/tests/ui/config/misspelled_config_kind.rs
src/ariel-os-macros/tests/ui/config/no_parameters.rs
tests/coap/src/main.rs

This changes the API of the `#[config]` macro to use a `const` instead of a function, making the intent and behavior clearer for users.
This modifies the macro, and updates the tests and examples that use it.
Depends on https://github.com/ariel-os/embassy/pull/1

refactor(config)!: use `const`s instead of fns for `#[ariel_os::config]`

---

src/ariel-os-threads/src/arch/cortex_m.rs
src/ariel-os-threads/src/arch/riscv.rs
src/ariel-os-threads/src/arch/xtensa.rs
src/ariel-os-threads/src/thread.rs

#476 broke our threading on Cortex-M, so our assumption on a specific u128 ABI behaviour was not reliably enough.
This PR solves this by:
1. moving SP into `ThreadData` for cortexm (it was populated but not used by neither xtensa nor riscv esp)
2. set the PSP from within `sched()`
3. simplify the "maybe skip context save/restore" logic, only requiring two values, which fit into the defined u64 return
4. use an `extern "C"` function, as the previous method was [not even supported](https://rust-lang.zulipchat.com/#narrow/channel/242906-t-compiler.2Farm/topic/.E2.9C.94.20u128.20now.20returned.20via.20stack.3F)
Quick testing shows slight performance improvement (1470ticks to 1450ticks on nrf52840dk).
#476

fix(cortex_m): don't rely on u128 ABI

---

rust-toolchain.toml
src/ariel-os-coap/src/udp_nal/mod.rs
src/ariel-os-embassy/src/network.rs
src/ariel-os-hal/src/dummy/mod.rs
src/ariel-os-hal/src/dummy/usb.rs
src/ariel-os-runqueue/src/runqueue.rs
src/ariel-os-threads/src/arch/cortex_m.rs
src/ariel-os-threads/src/sync/mutex.rs
src/lib/coapcore/src/seccontext.rs

Bump nightly to 2024-12-10

---

Cargo.lock
examples/device-metadata/README.md
examples/device-metadata/src/main.rs
src/ariel-os-embassy-common/Cargo.toml
src/ariel-os-embassy-common/src/identity.rs
src/ariel-os-embassy-common/src/lib.rs
src/ariel-os-embassy/src/lib.rs
src/ariel-os-identity/src/lib.rs

This adds generation of MAC addresses to the device identity, and uses them instead of our default 8a888888 addresses.
The addresses are random based on board name and device identity (a combination that should be unique, although we can't make hard guarantees for random numbers in a 48 bit space), and set the right bits required for a non-vendor MAC address (there's no space for random addresses, but administratively managed is the space commonly used for that).
Devices that have actually built-in MAC addresses can use the interface to provide the ones they have (but AIU, none of the chips we have right now have any burnt in).
SLAAC is coming up. I guess we should have some more proper MAC addresses by then.
* There's one FIXME in the code I'd like to have feedback on -- but unless …

feat(identity): generate MAC addresses from device identity

---

Cargo.lock
examples/usb-keyboard/src/main.rs
examples/usb-serial/src/main.rs
src/ariel-os-buildinfo/src/lib.rs
src/ariel-os-embassy/Cargo.toml
src/ariel-os-embassy/src/usb.rs

Now that `buildinfo` has been extracted as its own crate in #613, we can provide a constant with the OS name for use in examples and in our default USB configuration.

feat(buildinfo): introduce a `const` with the OS name

---

book/src/application.md
examples/blinky/src/pins.rs
examples/gpio/src/pins.rs
examples/http-server/src/pins.rs
examples/usb-keyboard/src/pins.rs
src/ariel-os-embassy/src/lib.rs
src/ariel-os-hal/src/define_peripherals.rs
src/ariel-os-hal/src/lib.rs
src/ariel-os-macros/src/spawner.rs
src/ariel-os-macros/src/task.rs
tests/gpio-interrupt-nrf/src/main.rs
tests/gpio-interrupt-stm32/src/main.rs
tests/gpio/src/pins.rs
tests/i2c-controller/src/pins.rs
tests/spi-loopback/src/pins.rs
tests/spi-main/src/pins.rs

This moves the `define_peripherals!` and `group_peripherals!` macros into the `ariel_os::hal` module so that they don't appear in the root of `ariel_os`.
- Generate the rustdoc docs: observe that the macros are not present in the root anymore, and that they are instead in the `ariel_os::hal` module, and that the `TakePeripherals` trait is now `doc(hidden)` on purpose (it's not meant to be user-visible).
- Generate the mdbook and observe that the macro paths are up to date, in the "Building an Application" chapter.

refactor(hal)!: move the peripheral-related macros

---

src/ariel-os-embassy/src/lib.rs
src/ariel-os/src/lib.rs

`ariel-os-rt` does not have to be accessed by users at all.
---
These were the last two root items that we needed to hide.

refactor!: stop re-exporting `ariel-os-rt` and hide another item

---

book/src/tooling/defmt.md

This extends the book documentation around `-D LOG`.
Reason we should do this explicitly is that we do comma-join LOG into DEFMT_LOG, so it's not immediately obvious to those who know defmt how this is done.

doc(book): point out how multiple log levels are done

---

laze-project.yml

Previously, there was a seperate cargo target dir per builder/application tuple.
This PR relaxes this to one target dir per builder.
This should increase re-using of build artifacts, reducing build times.
*edit* this PR's build [used](https://github.com/ariel-os/ariel-os/actions/runs/12435714450/usage) 2h:14m of CI builder time, the previous PR build [used](https://github.com/ariel-os/ariel-os/actions/runs/12434603555/usage) 3h:20m.

build: share cargo target dir per builder

---

Cargo.toml

Mitigates `warning: Patch `esp-storage v0.3.1 (https://github.com/ariel-os/esp-hal?branch=for-ariel-os-2024-10-16-0.21.1-pr2377-nousbquirk#57f8ab94)` was not used in the 
crate graph.`.
Let's re-add once we've bumped `esp-hal` and we actually need it.

build: don't specify esp-storage

---

.github/workflows/main.yml
laze-project.yml
src/ariel-os-embassy-common/Cargo.toml
src/ariel-os-embassy-common/laze.yml
src/ariel-os-embassy/Cargo.toml
src/ariel-os-embassy/laze.yml
src/ariel-os-identity/Cargo.toml
src/ariel-os-identity/laze.yml
src/ariel-os-macros/Cargo.toml
src/ariel-os-macros/laze.yml
src/ariel-os-nrf/Cargo.toml
src/ariel-os-nrf/laze.yml
src/ariel-os-rp/Cargo.toml
src/ariel-os-rp/laze.yml
src/ariel-os-runqueue/Cargo.toml
src/ariel-os-runqueue/laze.yml
src/ariel-os-stm32/Cargo.toml
src/ariel-os-stm32/laze.yml
src/ariel-os-threads/Cargo.toml
src/ariel-os-threads/laze.yml
src/ariel-os/Cargo.toml
src/ariel-os/laze.yml
src/laze.yml
src/lib/coapcore/Cargo.toml
src/lib/coapcore/laze.yml
src/lib/laze.yml
src/lib/rbi/Cargo.toml
src/lib/rbi/laze.yml
src/lib/ringbuffer/Cargo.toml
src/lib/ringbuffer/laze.yml

This PR:
- moves the necessary features for `cargo test`ing each crate into  `ci` features
- creates test-only `laze` "apps"
- creates a `host-test-only` laze module that runs `cargo test`
- makes CI use this
The main benefit is that users can now locally do `laze build -b host test`.

ci: use laze for `cargo-test`

---

Cargo.lock
Cargo.toml
ariel-os-cargo.toml
examples/laze.yml
examples/testing/Cargo.toml
examples/testing/README.md
examples/testing/laze.yml
examples/testing/tests/test.rs
laze-project.yml
src/ariel-os-identity/Cargo.toml
src/ariel-os-identity/laze.yml
src/ariel-os-identity/src/lib.rs
src/ariel-os-rt/Cargo.toml
src/ariel-os-rt/laze.yml
src/ariel-os-rt/src/lib.rs
src/laze.yml
tests/gpio-interrupt-nrf/src/main.rs
tests/gpio-interrupt-stm32/src/main.rs
tests/gpio/Cargo.toml
tests/gpio/laze.yml
tests/gpio/src/test.rs
tests/spi-main/src/main.rs
tests/threading-dynamic-prios/src/main.rs
tests/threading-lock/src/main.rs

This PR intents to provide a seamless integration of `embedded-test`.
~~This is very WIP, basically I'm in the experimentation phase.~~
~~This is taking shape. Still waiting on a probe-rs release, though.~~
This can be tested **with probe-rs-tools >=0.25.0** as follows:
The following steps can be followed to port existing tests from the `tests` directory to use `embedded-test`:
- Add `embedded-test` in `dev-dependencies`
- Add a `test` target (keep the `test` name for every test):
```toml
[[test]]
name = "test"
path = "src/test.rs"
harness = false
```
- Rename the existing `src/main.rs` to `src/test.rs`
- In the `laze.yml` file, add the following:
```yaml
selects:
- embedded-test
```
Fixes #331.
Depends on #506, #509, #549.
so, we need a way to re-use the system executor.

test: add `embedded-test` integration

---

examples/threading-channel/src/main.rs
examples/threading-event/src/main.rs
examples/threading-multicore/src/main.rs
src/ariel-os-embassy/src/asynch/blocker.rs
src/ariel-os-embassy/src/thread_executor.rs
src/ariel-os-runqueue/src/runqueue.rs
src/ariel-os-threads/src/arch/cortex_m.rs
src/ariel-os-threads/src/arch/riscv.rs
src/ariel-os-threads/src/arch/xtensa.rs
src/ariel-os-threads/src/lib.rs
src/ariel-os-threads/src/sync/mutex.rs
src/ariel-os-threads/src/thread.rs
src/ariel-os-threads/src/thread_flags.rs
src/ariel-os-threads/src/threadlist.rs
tests/benchmarks/bench_sched_flags/src/main.rs
tests/threading-dynamic-prios/src/main.rs
tests/threading-mutex/src/main.rs

PIDs are for processes, which of cours we don't have, so this PR replaces occurrences of "pid" with "tid" (thread ID).
The only remaining occurrences are in test files where "PID" comes from an external library, and from a configuration file which specifies an external symbol.

refactor(threading)!: use "TID" instead of "PID" for threads

---

examples/threading-event/README.md
examples/threading-event/src/main.rs

As part of #410, this PR:
- Extend the readme with some clarification
- Makes the logging more uniform

docs(threading-event): Clean up the threading-event example

---

book/src/SUMMARY.md
book/src/tooling/ferrocene.md
criticalup.toml
laze-project.yml

This is my draft branch for building with Ferrocene.
For our current nightly version, Ferrocene only seems to support thumbv7 from our set of toolchains.
Other than that, this was as drop-in as expected, cargo just needs to be started as `criticalup run cargo`.
To use / test this, get [criticalup](https://criticalup.ferrocene.dev/install.html), then build RIOT-rs as usual but select the `ferrocene` feature:
laze -Cexamples/hello-world build -b nrf52840dk -s ferrocene
TODO:

feat(build): initial Ferrocene support

---

Cargo.lock
Cargo.toml
deny.toml
examples/blinky/laze.yml
examples/blinky/src/pins.rs
tests/coap-blinky/Cargo.toml
tests/coap-blinky/README.md
tests/coap-blinky/laze.yml
tests/coap-blinky/src/main.rs
tests/coap/Cargo.toml
tests/coap/src/main.rs
tests/laze.yml

This adds a test that takes the RIOT CoAP demo crate (which is also used in the `rust-gcoap` example of RIOT OS), and runs it on top of ariel-os-coap.
I think this is not good example material by the criteria of pedagogics and simplicity, so it's sitting in tests right now; I think that's a good staging area for something that can become an example at some point, but isn't quite there yet.
Note that this explicitly allows using git sources for those modules. Curiously they still live at gitlab.com/etonomy, where riot-wrappers was initially developed; those modules were not moved in with github.com/riot-os yet. They probably should be, but RIOT reviewers there didn't complain; whenever that module moves, our reference will follow.

feat: Share code with RIOT OS

---

book/src/COC_reporting.md
book/src/CODE_OF_CONDUCT.md
book/src/SUMMARY.md
book/src/appendices.md

This merges the COC reporting page with the main COC one so it doesn't take two lines in the book sidebar.
In addition, this moves the Coding Conventions out of the Appendices chapter, which is removed.

docs(book): reorganize the developer guide section

---

.github/workflows/build.yml
Cargo.lock
book/src/support_matrix.html
doc/support_matrix.yml
laze-project.yml
src/ariel-os-boards/Cargo.toml
src/ariel-os-boards/espressif-esp32-devkitc/Cargo.toml
src/ariel-os-boards/espressif-esp32-devkitc/src/lib.rs
src/ariel-os-boards/espressif-esp32-s3-devkitc-1/Cargo.toml
src/ariel-os-boards/espressif-esp32-s3-devkitc-1/src/lib.rs
src/ariel-os-boards/src/lib.rs

Some of them were using the *module* name instead of the board name.
There should be no remaining occurrences of "wroom" (case insensitive) in the repo, including in the file/directory names.
---
This is suboptimal as multiple module variants can exist per devkit board, but this is out of scope of this PR.

fix(boards): rename the ESP32 boards

---

Cargo.lock
_typos.toml
ariel-os-cargo.toml
deny.toml
src/ariel-os-coap/src/lib.rs
src/lib/coapcore/Cargo.toml
src/lib/coapcore/src/ace.rs
src/lib/coapcore/src/error.rs
src/lib/coapcore/src/iana.rs
src/lib/coapcore/src/lib.rs
src/lib/coapcore/src/scope.rs
src/lib/coapcore/src/seccfg.rs
src/lib/coapcore/src/seccontext.rs

The ACE EDHOC profile is a useful addition to coapcore as it allows having EDHOC (and thus forward secrecy) with ACE tokens.
<del>This first iteration of it uses signed CWTs instead of symmetrically encrypted CWTs – these may not be the logical first step building things up (as they are mainly useful thinking of group audiences), but it is what I can test first.</del>
[edit:] It supports both signed and encrypted CWTs. (Things Just Worked once the other case was added 🥰).
This builds on #690.
* This d_epends on https://github.com/twittner/minicbor/pull/9 -- consequently it adds a patch.crates-io. Let's see how responsive upstream is; the alternative is a rather awkward manual parsing of the map.
* Practical use d_epends on https://github.com/openwsn-berkeley/lakers/pull/331 (the old …

feat(coap): add ACE EDHOC profile

---

examples/coap-client/src/main.rs
examples/coap-server/client.diag
src/ariel-os-coap/src/lib.rs
src/ariel-os-coap/src/udp_nal/mod.rs
tests/coap/client.diag
tests/coap/src/main.rs

There were two places where we had IP addresses hardcoded:
* in the ariel-os-coap server (due to https://github.com/smoltcp-rs/smoltcp/issues/1037 for which there is now a workaround)
* in the credentials files (but wildcards work there as well)
Blocks: https://github.com/ariel-os/ariel-os/pull/715 (subtly: that PR would go through, but the examples described in the README would not work any more)
Note that no changes to the docs are required at this time; #715 will update READMEs en masse.

coap: prepare for DHCP

---

Cargo.toml
src/ariel-os-bench/Cargo.toml
src/ariel-os-boards/Cargo.toml
src/ariel-os-boards/nrf52840dk/Cargo.toml
src/ariel-os-boards/nrf52dk/Cargo.toml
src/ariel-os-boards/nrf5340dk/Cargo.toml
src/ariel-os-buildinfo/Cargo.toml
src/ariel-os-coap/Cargo.toml
src/ariel-os-debug-log/Cargo.toml
src/ariel-os-debug/Cargo.toml
src/ariel-os-embassy-common/Cargo.toml
src/ariel-os-esp/Cargo.toml
src/ariel-os-identity/Cargo.toml
src/ariel-os-macros/Cargo.toml
src/ariel-os-nrf/Cargo.toml
src/ariel-os-random/Cargo.toml
src/ariel-os-rp/Cargo.toml
src/ariel-os-runqueue/Cargo.toml
src/ariel-os-stm32/Cargo.toml
src/ariel-os-utils/Cargo.toml
src/ariel-os/Cargo.toml

We've discussed that this was the better course of action for now, as at least some crates may need to be versioned separately. It would always be possible to enable inheritance again for some of the crates later if needed. 
This sets the version number in every crate to `0.1.0`.
The version numbers of the crates in `src/lib` seem ok:
- `coapcore` is [published on crates.io](https://crates.io/crates/coapcore) with version number `0.0.0`
- `rbi` is [published on crates.io](https://crates.io/crates/rbi) with version number `0.1.1`
- `ringbuffer` is unpublished but already has the default number we are using (`0.1.0`)
Depends on #726.

chore: specify versions in each crates instead of inheriting for now

---

examples/coap-client/laze.yml
examples/coap-server/README.md
examples/coap-server/laze.yml
src/ariel-os-coap/src/lib.rs
tests/coap-blinky/README.md
tests/coap-blinky/laze.yml
tests/coap/README.md
tests/coap/laze.yml

This closes 3 issues which @ROMemories and I found during testing:
* don't install aiocoap with all features (avoid requiring setuptools; all other dependencies have binary wheels for the platforms)
* increase stack size (got stack overflow, granted not in the default setup, but it's hard to debug, so why take risks)
* put blinky's LED on unauthenticated list (README uses it unauthenticated; proper fix that does away with many of the demo settings is in the works)

coap: fixes for tests and examples

---

book/src/networking.md
examples/README.md
examples/coap-client/Cargo.toml
examples/coap-client/src/main.rs
examples/coap-server/Cargo.toml
examples/coap-server/src/main.rs
examples/http-client/Cargo.toml
examples/http-client/src/main.rs
examples/http-server/Cargo.toml
examples/http-server/src/main.rs
examples/tcp-echo/Cargo.toml
examples/tcp-echo/src/main.rs
examples/udp-echo/Cargo.toml
examples/udp-echo/src/main.rs
laze-project.yml
src/ariel-os-embassy/Cargo.toml
src/ariel-os-embassy/src/net.rs
src/ariel-os-macros/Cargo.toml
src/ariel-os-macros/src/config.rs
src/ariel-os/Cargo.toml
tests/coap-blinky/Cargo.toml
tests/coap-blinky/src/main.rs
tests/coap/Cargo.toml
tests/coap/src/main.rs

This PR:
- makes DHCP the current default
- enables choosing the previous static configuration via laze module `network-config-static`
Part of #502.

feat: improve network configuration

---

Cargo.lock
Cargo.toml
deny.toml

#718 required patching the upstream crate, which was swiftly accepted so we used the upstream repo directly. The new version of that crate has now been released and this uses the <crates.io> version instead.
Follows #718.

chore(deps): use upstream `const-str` as the new version was released

---

book/src/support_matrix.html
doc/gen_support_matrix_html.rs
doc/support_matrix.yml

This adds two columns for the technical name of boards and chips. Maybe that makes the table a bit busy visually, but at least users can easily find the names they're looking for without having to look at Ariel OS's `laze-project.yml` as mentioned in the current Quick Start section, and we can revisit the visual design later when that table grows in size.
This also centers the support matrix, which looks better on wide-enough viewports.
Generate the book with:
```
(cd book && mdbook build . --open)
```

docs(support-matrix): print the technical name of boards and chips

---

.github/workflows/build-deploy-docs.yml

With #743, coapcore documentation became unavailable. While not part of the API which ariel-os exposes a public, this is a public API of an in-tree crate.
This restores the regression of "this API should be documented somewhere" in one of two possible ways: by building it as part of our docs.
The alternative is to build it separately and host it … somewhere else around here.
Regression introduced in #743.

ci(rustdoc): build documentation for coapcore

---

.github/workflows/build.yml

This PR disables building the codebase on main branch push.
Currently, every PR gets built at least **three** times: at least once before it can be merged, then once in the merge_queue rebased on main, than after pushing to main. The last two should be identical.
The way caching works in Github actions, the final master build updates the caches for all consecutive builds (which otherwise gets updated at nightly build time). Let's see if missing this is noticable.

ci: don't build on main branch push

---

src/ariel-os-embassy/src/lib.rs
src/ariel-os-macros/src/task.rs
src/ariel-os-macros/src/utils.rs
src/ariel-os/src/lib.rs

Internal crates with rather lose coupling [may want to](https://github.com/ariel-os/ariel-os/pull/755) run autostart locally rather than hooking in a big task starting routine.
This PR enables that.
Commits are cherry-picked from https://github.com/ariel-os/ariel-os/pull/755, where there is a use case that tests them.

refactor(macros): enable internal autostart

---

Cargo.lock
examples/coap-client/Cargo.toml
examples/coap-client/laze.yml
examples/coap-client/src/main.rs
examples/coap-server/Cargo.toml
examples/coap-server/laze.yml
laze-project.yml
src/ariel-os-coap/Cargo.toml
src/ariel-os-coap/src/lib.rs
src/ariel-os-embassy/src/sendcell.rs
src/ariel-os/Cargo.toml
tests/coap-blinky/Cargo.toml
tests/coap-blinky/laze.yml
tests/coap/Cargo.toml
tests/coap/laze.yml

This is a first step for modelling ariel-os's `coap` feature in laze. Reasons:
* Examples currently need to manually select random and network (yuck)
* We'll want to do more later (eg. run an CoAP "main loop" automatically if client and not server is selected, making the coap-client easier)
* Will I go beyond what is in the first few commits in this PR, or in a separate one? (Next steps are auto-starting the server and setting server policy and even identity through this.)
* A: Yes to auto-starting the server (because that corresponds to the initial comments around the laze entries), no to more (because some of that may need discussion).
**Remaining things to do**: model server policy (even if it's just a "pick the demo stuff"), provide public function that people should build their …

feat(coap): model in laze and autostart

---

Cargo.lock
src/ariel-os-embassy/Cargo.toml
src/ariel-os-embassy/src/lib.rs
src/ariel-os/Cargo.toml

The network stack was previously using a hard-coded seed.
This seed is used internally by `embassy_net` and by [smoltcp](https://docs.rs/smoltcp/latest/smoltcp/iface/struct.Config.html#structfield.random_seed) to avoid collisions between random network numbers (TCP ports/sequence numbers).
This only uses an RNG for seeding if support for one is already being compiled, and defaults to the hard-coded seed otherwise. We may revisit this in the future.
Use a network-enabled example (e.g., `tcp-echo`), and enable `debug`-level logging with `-DLOG=debug`. The seed used is printed (it is not a cryptography secret). Run the example without modifications, it should print the hard-coded seed:
```
DEBUG Network stack seed: 0x4d2
```
Then, enable the `random` laze module in that example, and run the …

feat(net): use an RNG to seed the network stack, when already enabled

---

book/src/support_matrix.html
doc/support_matrix.yml
src/ariel-os-hal/src/lib.rs

Typo fix for STM32WB55 and STM32H7 in the documentation, Rust book and one comment in the hal lib.
Previously : STM32W55..., STM32F7...
Now : STM32WB55..., STM32H7...
These are typo fix related to the docs only.
There is no PR related to these commits.
I plan to add other STM32 support, such as WBA55 for which I ran some examples on a board (hello world, blinky, etc).
Should I open an issue to track this activity or can I commit directly through PR ?
Please refer to the above description as there is not so many changes.

Docs : fix typo for STM32 WB55 and H7 in Doc, Rust book, and HAL comment

---

examples/blinky/laze.yml
examples/blinky/src/pins.rs

Add new feature : support of STM32WBA55 Nucleo board for blinky example.
Out of the 3 Leds available, the blinky example will use PB4, connected to Led 1 (Blue led).
It is the 2nd example supported, with the basic hello-world.
N/A.
N/A.
Tested on Nucleo WBA55CG board.

feat: add STM32WBA55 Nucleo to blinky example

---

laze-project.yml

Make the conflict a property of `executor-single-thread` instead of `sw/threading`.

refactor: move the conflict with threading into `executor-single-thread`

---

.github/workflows/main.yml
Cargo.lock
Cargo.toml
examples/alloc/Cargo.toml
examples/alloc/README.md
examples/alloc/laze.yml
examples/alloc/src/main.rs
examples/laze.yml
laze-project.yml
src/ariel-os-alloc/Cargo.toml
src/ariel-os-alloc/laze.yml
src/ariel-os-alloc/src/lib.rs
src/ariel-os-esp/Cargo.toml
src/ariel-os-esp/src/lib.rs
src/ariel-os-rt/Cargo.toml
src/ariel-os-rt/build.rs
src/ariel-os-rt/eheap.x
src/ariel-os-rt/src/lib.rs
src/ariel-os/Cargo.toml
src/laze.yml

This PR integrates `embedded-alloc` on Cortex-M, and exposes `esp-alloc` on esp, allowing use of the `alloc` crate in applications.
~~draft b/c I want to see what CI says, not using all available memory but only a fixed-size buffer.~~
This is using `rtlf` through the `embedded-alloc` crate, so with some default configuration of an TLSF allocator (on Cortex-M).
We might want to directly use rtlf to get more control over the TLSF settings. Or allow the linked-list allocator.
On esp, we could also use the TLSF allocator (replacing `esp-alloc`, which does use the linked-list one). Not sure if esp doesn't require special placement in RAM for some things (esp-wifi buffers for DMA or similar), though.

feat(alloc): initial `embedded-alloc` integration

---

src/ariel-os-alloc/src/lib.rs

Previous default was a little large for the plain esp32: [nightly build fail](https://github.com/ariel-os/ariel-os/actions/runs/13255340409).

fix(alloc): reduce esp default heap size

---

book/src/support_matrix.html
doc/support_matrix.yml
laze-project.yml
src/ariel-os-hal/Cargo.toml
src/ariel-os-stm32/Cargo.toml
src/ariel-os-stm32/src/lib.rs
src/ariel-os-stm32/src/storage.rs
src/ariel-os-storage/build.rs
src/ariel-os-storage/src/lib.rs

This adds partial support for flash-backed persistent storage to the currently supported STM32 MCUs, which only support blocking drivers. This makes `ariel_os::storage::remove()` unavailable on that MCU family, as flash drivers do not implement `MultiwriteNorFlash`. We may want to revisit how we handle this limitation.
This only supports homogeneous flash organization (therefore precluding support for STM32F401RE); support for heterogeneous organization can be addressed in the future.
- The `storage` example works as expected on STM32H755ZI, STM32WB55RG.

feat(stm32): add partial support for persistent storage

---

src/ariel-os-coap/src/lib.rs
src/lib/coapcore/src/ace.rs
src/lib/coapcore/src/generalclaims.rs
src/lib/coapcore/src/helpers.rs
src/lib/coapcore/src/lib.rs
src/lib/coapcore/src/oluru.rs
src/lib/coapcore/src/scope.rs
src/lib/coapcore/src/seccfg.rs
src/lib/coapcore/src/seccontext.rs
src/lib/coapcore/src/time.rs

Issued ACE tokens often have limited lifetime; this adds the APIs to coapcore to evaluate that aspect.
As it required touching some signatures and pub'nesses, the PR also contains changes to reduce and harmonize the public surface before coapcore's API can stabilized for a 0.1 release.
Currently we don't have "wall time" in Ariel OS (but even if we had, we'd need it trusted).
For this first iteration, Ariel OS just uses the zero-sized "we don't know the time" configuration. Once we start using configuration storage more actively, we can progress from "we don't know anything" to "this can't be valid because we've seen a way newer token" on to [full raytime](https://datatracker.ietf.org/doc/draft-amsuess-t2trg-raytime/).

feat(coapcore): evaluate tokens' lifetime

---

laze-project.yml

The debug logging facade should only be enabled when a debug console is there to print on.
Previously the following would fail to link:
```sh
laze -C examples/log/ build -d debug-console -b nrf52840dk size
```
and would require to explicitly disable `debug-logging-facade` as well:
```sh
laze -C examples/log/ build -d debug-console -d debug-logging-facade -b nrf52840dk size
```
With this PR `debug-logging-facade` is only enabled when `debug-console` is enabled instead of always, so the first command works as expected.

fix(debug-console): enable the debug logging facade only with a console

---

laze-project.yml
src/ariel-os-rt/build.rs
src/ariel-os-rt/keep-stack-sizes.x

Rust and LLVM can export some information about the stack sizes by
* rustc emitting them into some section, and
* the linker (as guided by the linker script) keeping them without emitting them into the binary
This is not used by any tools yet, but emits information usable, for example, by a [small script listed in #804](https://github.com/ariel-os/ariel-os/issues/804#issuecomment-2655105100).
Contributes to #804 by setting some groundwork.
* I've copied linker script verbatim from the docs, and set the appropriate SPDX / reuse comments.
* This adds a nightly-only flag unconditionally; once we approach building on stable, we can make it conditional (but no point in doing that now).
* I don't think there's considerable cost to it; it's just a few hundred bytes added to the ELF.
- n/a I have …

chore: add -Z emit-stack-sizes and keep them through linking

---

src/ariel-os-coap/src/lib.rs

During testing (and even on unmodified main before and after #752), I've run into stack overflows with the CoAP examples. I didn't explore deeper into whether it was a nightly update or some unrelated commit that broke things.
This commit just tunes down two huge buffers whose size was copy-pasted from embassy-net examples -- it's not final tuning, but they work.
Curiously, those wind up as part of the stack size (stack uses of `embassy_executor::raw::TaskStorage<F>::poll`), even though their lifetime spans an await points (and they should thus be part of the state enum). By reducing the buffer size by less than 3000 byte per direction, 4x that amount is freed from the stack.
Deeper investigation is ongoing in https://github.com/ariel-os/ariel-os/issues/804
I've successfully run all CoAP …

fix(coap): tune down UDP buffers

---

Cargo.lock
examples/coap-server/laze.yml
laze-project.yml
src/ariel-os-coap/Cargo.toml
src/ariel-os-coap/src/lib.rs
src/ariel-os/Cargo.toml
src/lib/coapcore/src/seccfg.rs
src/lib/coapcore/src/seccontext.rs
tests/coap-blinky/laze.yml
tests/coap/README.md
tests/coap/laze.yml

Right now, all our examples use the demo keys, and we can't provision own keys, and can't run completely nosec.
This introduces laze (really cargo) features in which ariel-os-coap decides how to set up security, with the examples' config remaining "pick the demo keys" (but this time, explicitly).
With some coapcore internal changes (well they change its API, but not in a way ariel-os-coap notices), the nosec mode builds with considerably less flash usage.
Next steps from here are introducing more building blocks (like "flash my moral equivalent of ~/.ssh/id_ecdh.pub as the root key instead of a key file we ship" or "there is provisioning like in #453 so take those keys"), and those can extend both the -demokeys and can become part of a -default setup, but I'd take those gradually from …

feat(coap): laze based configuration

---

book/src/getting_started.md
laze-project.yml

I tried to build something locally for all boards, and got "error: toolchain 'esp' is not installable" -- so I did what all good users do and went to the book's installation instructions.
The `laze build install-toolchain` command scared me, for I prefer knowing what gets done before I do it -- installing through rustup is fine, and that's what it does, but the docs didn't tell me, so that is fixed here.
A note in the laze-project.yml file ensures that this doesn't change without updating the note.
The note also mentions that ESP32 is *not* installed -- that doesn't help me with my original problem, and apparently we don't have docs for that. If there is some easy third party instruction we can link, I'd add that, otherwise I suggest we merge this here and then work on extra docs to get …

docs(book): install-toolchain only goes through rustup and doesn't do ESP

---

src/ariel-os-esp/src/i2c/controller/mod.rs
src/ariel-os-esp/src/i2c/mod.rs
src/ariel-os-esp/src/spi/main/mod.rs
src/ariel-os-esp/src/spi/mod.rs

This should fix our nightly build failure of the I2C controller and SPI main tests.

feat(esp32): add untested support for I2C controller and SPI main

---

Cargo.lock
laze-project.yml
src/ariel-os-rt/Cargo.toml
src/ariel-os-rt/build.rs
src/ariel-os-rt/isr_stack.ld.in
src/ariel-os-rt/src/lib.rs

Previously, riscv (or the esp variants we're supporting) still used the end of memory as initial stack pointer. This PR brings them in line with Cortex-M, where the isr stack is placed at the beginning of RAM.

feat(riscv): support configuring isr stacksize on riscv

---

Cargo.lock
src/lib/coapcore/Cargo.toml

Updting libOSCORE enables being selective about symbols to be shipped by libOSCORE, which is relevant for ESP builds.
It does not yet enable libOSCORE builds because they will need concrete settings (something like `CFLAGS="-mlongcalls" CC=xtensa-esp32-elf-gcc`, and maybe more controlled sourcing of the export-esp.sh environment) in CI.

chore(coapcore): update libOSCORE

---

src/ariel-os-storage/src/lib.rs

This is a minimal improvement over the key-value pair inserted by Ariel OS in the storage on initialization by changing the key to a name clearly from Ariel and a unit type value.
We can probably do better than this by storing some metadata about the storage itself.

feat(storage)!: change ariel init marker in storage

---

src/ariel-os/Cargo.toml

The `sw/storage` laze module must be used instead, as documented in the book.
Could have been part of #737.

docs: hide the `storage` Cargo feature from users

---

Cargo.lock
Cargo.toml
ariel-os-cargo.toml
doc/support_matrix.yml
laze-project.yml
src/ariel-os-embassy-common/Cargo.toml
src/ariel-os-embassy-common/src/executor_thread.rs
src/ariel-os-embassy-common/src/lib.rs
src/ariel-os-embassy/Cargo.toml
src/ariel-os-embassy/src/lib.rs
src/ariel-os-esp/Cargo.toml
src/ariel-os-esp/src/lib.rs
src/ariel-os-esp/src/preempt.rs
src/ariel-os-hal/Cargo.toml

This PR hooks up the Ariel scheduler to esp-wifi, enabling use of threading together with WiFi on esp.
Unfortunately there's still an issue on riscv, but this works fine on xtensa.
This piggy-backs an update to our esp fork to use `optfield` for `OptionalPeripherals` like our embassy fork has been doing for a while.
Alternative to #300.

feat(esp): solve esp XOR wifi for xtensa

---

src/ariel-os-storage/src/postcard_value.rs
src/lib/coapcore/src/error.rs

Trivial fixes of links that lit up red when building docs with `--document-private-items` in the hunt for "why is trait X implemented for Y".
By doc building now passing

docs: fix broken links on internal items

---

.github/workflows/build.yml
book/src/getting_started.md
examples/coap-client/laze.yml
examples/coap-server/laze.yml
laze-project.yml
src/ariel-os-coap/Cargo.toml
src/ariel-os/Cargo.toml
src/lib/coapcore/Cargo.toml
tests/coap-blinky/laze.yml
tests/coap/laze.yml

This combines #825, #824 and a commit that removes the blockers for the tests/examples and xtensa.
This will need a rebase when both dependencies are in.
* <del>Will it blend?</del> It even loses the taste of stale workarounds and inaccessible platforms after blending.

chore: source extensa environment on demand, unblocking coap

---

laze-project.yml

After #826, running `cargo … run` broke; #841 fixed that by introducing a fallback `true` in the position of CARGO_PRESHELL as a hot fix (aiming to restore functionality).
That #841 had open ToDos: cleanup, and finding out what exactly happened.
What happened was that when CARGO_PRESHELL is undefined, it is left for the shell to expand; strace gives:
```
[pid 3509585] execve("/usr/bin/sh", ["sh", "-x", "-c", "cd examples/blinky && ${CARGO_PRESHELL} OPENOCD_ARGS=\"-f board/"...], 0x7ffdfb8bce40 /* 55 vars */) = 0
```
This PR cleans up after that hot fix by
* documenting CARGO_PRESHELL
* making it into a list variable (with an empty list default and ` && ` suffix)
thus reducing the visual clutter of having `&& true` as part of every shell command. Scalability to multiple CARGO_PRESHELL …

chore: make CARGO_PRESHELL a list variable

---

book/src/getting_started.md
laze-project.yml

Docs were incomplete w/rt ESP installation: Support for updating espup through espup is added to the build scripts, and documented.
This does *not* act on the "source this thing" line; would it make sense to do that in the same PR, given that we are now taking some responsibility (at least in the sense of guiding the user) toward setting this up?
(I think that selectively sourcing espup's exports is generally a good idea, especially as it allows the user to keep their LLVM environment variables clean, and thus keep them from messing with othe)
Follow-up for #812
Blocked by https://github.com/ariel-os/ariel-os/pull/826

chore: run espup through laze and document it

---

Cargo.lock
_typos.toml
ariel-os-cargo.toml
src/lib/coapcore/Cargo.toml

We depended on a branch which I had on minicbor.
This reduces the number of patch.crates-io lines, and allows me to delete the branch in the upstream repo.
Also, this allows me to finally get that typo out of our system again.
As a downside, this probably increases the number of minicbor versions, but that's not addressed by not doing this, but by updating dependencies elsewhere.
Applies https://github.com/twittner/minicbor/pull/9

chore: update minicbor to move off fork branch

---

.github/workflows/main.yml

This is a first step in automatically checking our links in PRs. The goal of this is *not* to check for external 404s in a scheduled manner, only to check internal, relative links—*including fragments/anchors*—especially in the book, in each PR.
The goal is to give us assurance that our internal links are not broken and that we don't have to hold ourselves back from cross-linking as much as we want so as to make the docs as clear and useful as possible (from fear of typos or of our links becoming outdated).
[lychee](https://github.com/lycheeverse/lychee) has been chosen as the link checker because:
- It seems feature-full enough that we should be able to configure it to make it work in our complex multi-output PRs/future workflows.
- It's popular (2.4 k GH stars at the time of writing).
- …

ci(lint): add basic checking of internal links in PRs

---

laze-project.yml

laze v0.1.33 just dropped, with a new way to change working directory for tasks. no more `cd ${appdir} && ...`.

feat(build): make use of `workdir` in laze files

---

Cargo.lock
src/ariel-os-identity/Cargo.toml
src/ariel-os-identity/src/lib.rs

This makes `ariel-os-identity` depend on `ariel-os-hal` directly instead of depending on `ariel-os-embassy`. This avoids future cyclic dependencies.

refactor(identity): depend on `ariel-os-hal` directly

---

Cargo.toml

Fixes a soundness bug and adds support for Rust edition 2024.
[Changelog](https://github.com/dtolnay/linkme/releases#:~:text=0.3.31)
The lockfile has no changes as it was already using the newest version.

fix(dep): bump `linkme` to 0.3.31

---

Cargo.toml

Something must have changed, but the cargo script that generates our support matrix suddenly thought it is part of the workspace.
cargo suggests either adding an empty `[workspace]` to the offending crate's manifest, or add its folder to the main workspace' `exclude`. The former doesn't work for "embedded manifests", so this PR implements the second.
Fixes #866.

docs: exclude `doc/` from workspace

---

.github/workflows/main.yml

The `mdbook-cmdrun` preprocessor, which is used to render the table in the book, cannot make the mdbook run fail in case of non-zero exit code, so we check this separately in the lint step.
[Relevant issue on `mdbook-cmdrun`](https://github.com/FauconFan/mdbook-cmdrun/issues/18)
This is why the need for #867 wasn't detected as part of #861.

ci(support-matrix): check the generation exit code

---

Cargo.lock
src/ariel-os-embassy/Cargo.toml
src/ariel-os-embassy/src/lib.rs
src/ariel-os-embassy/src/net.rs

This seed is used internally by `embassy_net` to randomize port numbers and is passed to `smoltcp` as [`random_seed`](https://docs.rs/smoltcp/latest/smoltcp/iface/struct.Config.html#structfield.random_seed) which also uses it randomize initial TCP sequence numbers.
That seed doesn't need to be cryptographically secure but there are still [mild security considerations](https://github.com/smoltcp-rs/smoltcp/pull/465#discussion_r726278895), as a *blind* attacker could spoof packets if these were predictable.
This PR aims to improve on what #770 introduced:
- If an RNG is present *and already enabled by the application*, we use it to obtain a seed that is unique and different on each reboot.
- Otherwise, if the device provides a hardware-backed device ID, unique by definition, we use the …

feat(network): seed `embassy_net` from the device ID when no RNG

---

book/src/networking.md

Documentation for the main laze module was missing from #677.

docs(networking): document the previously missing `network` laze module

---

Cargo.toml
src/ariel-os-embassy-common/src/spi/main/mod.rs
src/ariel-os-embassy/src/delegate.rs
src/ariel-os-embassy/src/gpio.rs
src/ariel-os-embassy/src/i2c/controller/mod.rs
src/ariel-os-embassy/src/spi/main/mod.rs
src/ariel-os-esp/src/i2c/controller/mod.rs
src/ariel-os-esp/src/lib.rs
src/ariel-os-nrf/src/i2c/controller/mod.rs
src/ariel-os-nrf/src/lib.rs
src/ariel-os-nrf/src/spi/main/mod.rs
src/ariel-os-rp/src/i2c/controller/mod.rs
src/ariel-os-rp/src/lib.rs
src/ariel-os-stm32/src/i2c/controller/mod.rs
src/ariel-os-stm32/src/lib.rs
src/ariel-os-threads/src/lib.rs
src/ariel-os-threads/src/sync/channel.rs
src/ariel-os-threads/src/sync/lock.rs
src/lib/coapcore/src/lib.rs

This PR adds missing [`#[must_use]` attributes](https://doc.rust-lang.org/reference/attributes/diagnostics.html#the-must_use-attribute), and enables the relevant lints at workspace level; these will be removed when we enabled `pedantic`, as these lints are already part of the `pedantic` group.
This is extracted from #279 to make it easier to review.

fix(lints): warn about possibly missing `#[must_use]` attributes

---

laze-project.yml
src/ariel-os-boards/st-nucleo-h755zi-q/Cargo.toml
src/ariel-os-boards/st-nucleo-wb55/Cargo.toml
src/ariel-os-boards/st-nucleo-wba55/Cargo.toml
src/ariel-os-stm32/Cargo.toml
src/ariel-os-stm32/src/hwrng.rs
src/ariel-os-stm32/src/lib.rs

This replaces Cargo features on our SMT32 HAL crate with laze capabilities to remove the need for board crates for selecting these.
This is extracted from #852 to make it easier to review.
Possibly compile the `random` and `udp-echo` examples on st-nucleo-h755zi-q and st-nucleo-wb55, but this is already done by CI.

refactor(stm32): replace Cargo features with laze capabilities

---

laze-project.yml
src/ariel-os-coap/build.rs

Follow-up to fix broken new tests from #814: When the PEERS_YML variable was switched late in the review process to use a Laze variable instead, I only re-tested it with an explicit override in place and not without one.
```sh
$ cd tests/coap
$ laze build -b particle-xenon -D LOG=trace -s coap-server-config-storage
$ cd ../../
$ laze -C tests/coap build -b particle-xenon -D LOG=trace -s coap-server-config-storage
$ laze -C tests/coap build -b particle-xenon -D LOG=trace -s coap-server-config-storage -D PEERS_YML=${PWD}/tests/coap/peers.yml
```
Look at whether laze can help with the confusion that `-D some-file` meaning the same thing no matter which directory this is being called from. (Generally arguments are understood relative to the working directory of the program that is being …

fix(coap): use correct default peers.yml path

---

src/ariel-os-coap/src/lib.rs
src/ariel-os-embassy/src/cell.rs
src/ariel-os-embassy/src/delegate.rs
src/ariel-os-embassy/src/lib.rs
src/ariel-os-embassy/src/net.rs

Renames `SendCell` to `SameExecutorCell`, and the `ariel_os_embassy::sendcell` module to `cell` as discussed a few weeks ago.
This is not a breaking change as neither the `ariel_os_embassy::cell` module (formerly `sendcell`) nor the `SameExecutorCell` cell (formerly `SendCell`) are documented (on purpose).

refactor: rename `SendCell` to `SameExecutorCell`

---

src/lib/coapcore/src/ace.rs
src/lib/coapcore/src/helpers.rs
src/lib/coapcore/src/lib.rs
src/lib/coapcore/src/oluru.rs
src/lib/coapcore/src/scope.rs
src/lib/coapcore/src/seccfg.rs
src/lib/coapcore/src/seccontext.rs
src/lib/coapcore/src/time.rs

In https://github.com/ariel-os/ariel-os/pull/886#discussion_r1979639409 the coapcore crate was exempted from the pedantic lints. While I disagree with many of them, having a big exception hover here is not great either. (And I have to admit that a few of those even improve the code).
Blocked by https://github.com/ariel-os/ariel-os/pull/865 as that is bound to produce conflicts once I fix "documentation missing" errors.

fix(coapcore): address various lints

---

.github/workflows/main.yml

Even easy PRs regularly send me to many context switches because first there is something cargo-doc complains about, I fix that, force push because otherwise the squash checks show up read, then that passes and something is not perfectly rustformatted because I applied something from a suggestion, again a few minutes later taplo is unhappy with a line not being wrapped, and eventually things stall again over a typo.
This moves most checks into parallel tasks, that don't just run in parallel, but more importantly should also all run to completion even when one of them fails (which previously stopped the later steps).
* Did I catch all running prerequisites?
* Did I miss any "cancel this bunch any fails" configuration?

ci: split lint steps

---

.github/workflows/build.yml
.github/workflows/main.yml

This is pinning laze to 0.1.x so when it might release a breaking change, our CI doesn't break.

ci: pin laze version to 0.1.x

---

book/src/figures/ariel-hexacube-orange-rounded.svg

Prevents issues where the logo is not accurate when the viewer is missing the fonts on the local computer
follow-up to #901 
Test by viewing the new logo on a device with limited fonts, such as an android based device.

docs(logo): Use paths and not text in logo

---

book/src/getting_started.md

This PR adds instructions for getting started with Ariel-OS on macOS. I built the `hello-world` example for all available boards and found that `gcc-arm-none-eabi` and `gcc-riscv64-unknown-elf` were not required, so I removed them from the macOS install command. 
Additionally, I made minor adjustments to the `rustup` installation commands since it was listed twice—once in step 1 and again in step 2. I also believe the recommended installation method is via the official website.
#906

docs(book): Add macOS to getting started

---

laze-project.yml

This reorders the Arm-related modules (e.g., `thumbv*`, `nrf*`, `stm32*`) in lexicographical order.
This also fixes a minor modeling issue in one of the nrf52 modules regarding the `PROBE_RS_CHIP` variable.
An intermediate `nrf53` module is also introduced.
This prepares for #882 which introduces `cortex-m*` modules.
This PR is definitely better reviewed commit by commit.

refactor(laze): reorder and fix Arm-related modules

---

examples/coap-client/laze.yml
examples/coap-server/laze.yml
examples/http-client/laze.yml
examples/http-server/laze.yml
examples/tcp-echo/laze.yml
examples/udp-echo/laze.yml
laze-project.yml
src/ariel-os-embassy-common/src/executor_thread.rs
src/ariel-os-embassy/src/lib.rs
src/ariel-os-rt/Cargo.toml
src/ariel-os-rt/src/lib.rs
src/ariel-os/Cargo.toml

This is my try at making the executor stack size configuration a bit more flexible, and more to the point.
E.g., our examples increase the `CONFIG_ISR_STACKSIZE`, but probably mean to increase the executor stack size.
Marking as draft, IMO we need some way of actually measuring the stack size to work on this properly.

feat(rt): more flexible stacksize configuration

---

laze-project.yml
src/ariel-os-stm32/src/lib.rs
src/ariel-os-stm32/src/usb.rs

This accommodates STM32 MCUs which use a `USB` interrupt instead of a `USB_LP` interrupt (e.g, the [STM32L433CC is one such MCU](https://docs.embassy.dev/embassy-stm32/git/stm32l433cc/interrupt/typelevel/index.html)).
This renames the existing `stm32-usb` laze capability to `stm32-usb-lp`; I'm of the opinion that this is not a breaking change as we weren't documenting this capability.
This is not intended to be as complete as #911, support for other USB interrupts will be introduced later.

feat(stm32): add support for non-`USB_LP` USB drivers

---

src/ariel-os-stm32/src/hwrng.rs

This introduces laze capabilities for what I believe is the entirety of the currently existing STM32 HWRNG/TRNG interrupts. These were obtained by grepping the JSON files from [stm32-data-generated](https://github.com/embassy-rs/stm32-data-generated/tree/main/data/chips) for `interrupt": "[^"]*RNG` and then manually checking in the JSON files that these interrupts were indeed used for the peripheral of name "RNG".
The new interrupts are for STM32 MCUs we do not currently support, but this is preliminary work to make it easier to support all of them later.
Similar to #889.

feat(stm32): introduce laze capabilities for all HWRNG interrupts

---

laze-project.yml
src/ariel-os-rt/Cargo.toml

This exposes `cortex-m*` modules introduced in #882 as `cfg` flags, and use this in `ariel-os-rt` to enable `critical-section`-emulated CAS operations on Cortex-M0+.

refactor(laze): expose `cortex-m*` modules as `cfg` flags

---

.github/workflows/main.yml

Running the `cargo-test` job twice (the first time to initialize the cache, the second time to test it), this brings its execution time from about 4 min 30 s down to 3 min 15 s. Installing the apt dependencies takes about 1 min 20 s and compiling liboscore takes 40 s.
Depends on #846.
Is it worth it?

ci(cargo-test): enable `rust-cache` for the `cargo-test` job

---

src/ariel-os-macros/src/task.rs

Uses a full path to the `ariel-os` crate instead of expecting the `UsbBuilderHook` to be in scope.

fix(task-macro): avoid the need for importing `UsbBuilderHook`

---

examples/usb-keyboard/src/main.rs
examples/usb-serial/src/main.rs
src/ariel-os-macros/src/task.rs
src/ariel-os-macros/tests/ui/task/missing_autostart_param_for_hook.rs
src/ariel-os-macros/tests/ui/task/missing_autostart_param_for_hook.stderr
src/ariel-os-macros/tests/ui/task/misspelled_hook_name.rs
src/ariel-os-macros/tests/ui/task/misspelled_hook_name.stderr

Following #918, this removes the imports of `UsbBuilderHook` as they are no longer needed.

refactor: remove unneeded `UsbBuilderHook` imports

---

Cargo.lock
examples/benchmark/Cargo.toml
examples/benchmark/laze.yml
examples/storage/Cargo.toml
examples/storage/laze.yml
examples/testing/Cargo.toml
examples/testing/laze.yml
examples/threading/Cargo.toml
examples/threading/laze.yml
examples/usb-serial/Cargo.toml
examples/usb-serial/laze.yml

This renames the examples the most likely to cause confusion because their laze module name is close to another documented laze module (e.g., `storage` and `sw/storage`).

docs(examples): rename examples with confusing laze module names

---

src/ariel-os-coap/build.rs
src/ariel-os-coap/src/stored.rs
tests/coap/README.md
tests/coap/peers.yml

Users can't utilize all the coapcore facilities from ariel-os-coap yet; this one addresses giving authorizations to an unauthenticated user.
Note that this doesn't necessarily mean "insecure": Such a client could be given read-only access to a resource, and while any client can choose to go insecure, they can also start EDHOC with a KCCS, verify the server's identity, and it's about just as confidential as HTTPS (nobody other than the client and server knows what is going on precisely).
Closes: #900
* Go to tests/coap, and follow the README step by step.
* Should we make it easy to pull in "whatever Ariel OS thinks should be allowed" more easily? That's best answered when we actually do have OS provided services.
* Should we add a way to express "do anything but just read-only"? Probably …

feat(coap): express unauthenticated credentials

---

src/ariel-os-embassy/src/lib.rs
src/ariel-os-storage/src/lib.rs

This reduces the size of the startup task ~~on non-RP MCUs~~, which is statically allocated and therefore ends up in the `bss` section, while only running at startup.
The following table summaries the change in `bss` size of the `storage` example:
| Board              | Old `bss` size | New `bss` size | Change       |
| --------           | -------------: | -------------: | -----------: |
| nrf52833dk         | 5140           | 4220           | -920 (17 %)  |
| nrf52840dk         | 5140           | 4220           | -920 (17 %)  |
| nrf5340dk          | 5124           | 4204           | -920 (17 %)  |
| rpi-pico-w         | 6012           | 4780           | -1232 (20 %) |
| st-nucleo-h755zi-q | 5752           | 4832           | -920 (16 %)  |
| st-nucleo-wb55     | 5288           | 4368 …

perf(storage): block on storage init to spare RAM

---

examples/coap-server/src/main.rs
tests/coap-blinky/src/main.rs

Removes needless `use` items.
The need for those went away when `.with_wkc()` was moved into ariel_os::coap.
* Why didn't linting catch those? Maybe things are not so strict for examples.

fix(coap): remove needless use of ReportingHandlerBuilder

---

examples/coap-client/laze.yml
examples/coap-server/laze.yml
laze-project.yml
tests/coap-blinky/laze.yml
tests/coap/laze.yml

The individual examples don't do anything on their own that makes the stack size exceed the default. This also eases writing own applications.
(Also, some of those were still on an older idiom to set that size; happened to not cause trouble with the run-tested boards).
The CoAP tests and exampels still build, --verbose shows the stack size in the cargo environment, and they don't crash on requests. (the clien example of course still errs out)
(Tested on st-nucleo-wb55 with on `{examples,tests}/*coap*`)
This helps the CoAP tutorial.

refactor(coap): move stack size into module

---

examples/threading-multicore/README.md
examples/threading-multicore/src/main.rs

Works around scheduler behavior when another higher-priority thread is active (e.g., executor thread).
Fixes #934.

fix(examples): increase unpinned thread priority in threading-multicore

---

.github/workflows/build.yml

This adds a step to our main build plan that removes some unneeded build tooling that comes preinstalled on the github workers. This gives us ~13gb extra space to fill.
The `rm ...` takes over a minute when run in foreground, so it run in the background.
Looking at CI times with a sample size of 1 for this change, this does not seem to increase total build time.

ci: free up space

---

examples/benchmark/laze.yml
laze-project.yml
tests/benchmarks/bench_sched_flags/laze.yml
tests/benchmarks/bench_sched_yield/laze.yml

Right now, each capability declares the list of contexts (i.e., MCUs, boards) on which it is provided. However, this means that adding support for new MCUs/boards involves modifying the existing definitions of these capabilities, which wouldn't work for out-of-tree board definitions, which we want to support.
This PR therefore instead makes each MCU/board context list the capabilities it provides, instead of the other way around.
This is also related to #640.
Depends on #838.

refactor(laze): invert how capabilities are provided

---

src/ariel-os-stm32/src/usb.rs

Introduces new laze capabilities for what I believe is every *low-priority* USB interrupts.
These were obtained by grepping the JSON files from [stm32-data-generated](https://github.com/embassy-rs/stm32-data-generated/tree/main/data/chips) for `interrupt": "[^"]*USB` and then manually checking in the JSON files that these interrupts were indeed used for the peripheral of name "USB" for the LP (low-priority) signal.
High-priority and wake-up interrupts are out of scope of this PR, which excludes the following matches:
- `USB_FS_WKUP`
- `USB_HP`
- `USB_HP_CAN1_TX`
- `USB_HP_CAN_TX`
- `USBWakeUp`
Builds on #889.

feat(stm32): add support for low-priority USB interrupts

---

laze-project.yml

The `rpi-pico-w` should inherit from `rp2040` directly instead of inheriting from `rpi-pico` because the capabilities of the `rpi-pico-w` are not a superset of those of the `rpi-pico`. For instance the GPIO25 is not connected to the onboard LED, which made the `blinky` example not work.
Depends on #848.

 fix(boards): fix the context `rpi-pico-w` inherits from 

---

src/ariel-os-rp/src/picotool.rs

Fixes build on rpi-pico2 that was [broken](https://github.com/ariel-os/ariel-os/actions/runs/14141849571/job/39624309023#step:15:1095) by #584.

fix(rp): mark `link_section` as `unsafe`

---

doc/support_matrix.yml
examples/blinky/laze.yml
examples/blinky/src/pins.rs
examples/gpio/laze.yml
examples/gpio/src/pins.rs
examples/http-server/laze.yml
examples/http-server/src/pins.rs
laze-project.yml
src/ariel-os-nrf/Cargo.toml
src/ariel-os-nrf/build.rs
src/ariel-os-nrf/src/i2c/controller/mod.rs
src/ariel-os-nrf/src/i2c/mod.rs
src/ariel-os-nrf/src/identity.rs
src/ariel-os-nrf/src/lib.rs
src/ariel-os-nrf/src/spi/main/mod.rs
src/ariel-os-nrf/src/spi/mod.rs
src/ariel-os-storage/build.rs
tests/coap-blinky/laze.yml
tests/gpio-interrupt-nrf/src/main.rs
tests/gpio/src/pins.rs
tests/i2c-controller/laze.yml
tests/i2c-controller/src/pins.rs
tests/spi-loopback/laze.yml
tests/spi-loopback/src/pins.rs
tests/spi-main/laze.yml
tests/spi-main/src/pins.rs

This adds basic (i.e., only ports features common to other boards, not what makes that board fancy) support for the nRF9160 MCU and its development kit.
Successfully tested in hardware the following:
- `examples/blinky`
- `examples/gpio`
- `examples/power`
- `examples/storage`
- `examples/threading-channel`
- `examples/theading-mutex`
- `tests/gpio-interrupt-nrf`
- `tests/i2c-controller`
- `tests/threading-mutex`
- `tests/spi-loopback`
- `tests/spi-main`
- `tests/threading-dynamic-prios`
Closes #840.

feat(nrf): add basic support for nRF9160

---

src/ariel-os-threads/src/arch/cortex_m.rs
src/ariel-os-threads/src/lib.rs

This replaces use of naked functions and `naked_asm` with stable `global_asm!()`.
One down for #298.

feat(threads): don't use `feature(naked_functions)`

---

book/src/adding-board-support.md
laze-project.yml

This drops the package type and temperature range from the `PROBE_RS_CHIP` values specified in STM32 laze contexts, which are passed to probe-rs as `--chip ${PROBE_RS_CHIP}`. This still works because probe-rs actually prefix-matches the chip names.
Removing these will allow to greatly simplify the laze contexts for STM32 MCUs and the `ariel-os-stm32-mapping` crate recently added in #928.
Successfully tested on st-nucleo-c031c6, st-nucleo-h755zi-q, and st-nucleo-wb55.

chore(stm32): drop unneeded info from probe-rs chip names

---

doc/support_matrix.yml
laze-project.yml
src/ariel-os-rp/src/cyw43.rs
tests/spi-main/laze.yml

Support for the Raspberry Pi Pico 2 (non-W) was added in #435, this adds support for the W variant, which features the same CYW43/Infineon chip as the Pico (1) W, wired the same way, which allows us to simply reuse what we already have for that one.
Successfully tested:
- `tests/i2c-controller/`
- `tests/spi-main`
- `examples/http-client` using Wi-Fi
Closes #940.
Depends on #848.
Depends on #944.

feat(boards): add support for the Raspberry Pi Pico 2 W

---

doc/support_matrix.yml
src/ariel-os-stm32/src/i2c/controller/mod.rs
src/ariel-os-stm32/src/i2c/mod.rs
tests/i2c-controller/laze.yml
tests/i2c-controller/src/pins.rs

This fixes and completes support for I2C in controller mode on STM32C0 which was bootstrapped in #838.
Tested `tests/i2c-controller` successfully on st-nucleo-c031c6. 
Depends on #961.

 feat(stm32c0): complete support for I2C in controller mode

---

doc/support_matrix.yml
tests/spi-loopback/src/pins.rs
tests/spi-main/laze.yml
tests/spi-main/src/pins.rs

This tests and completes support for SPI main on STM32C0.
Tested `tests/spi-loopback` and `tests/spi-main` successfully on st-nucleo-c031c6. 
Depends on #962.

 feat(stm32c0): complete support for SPI in main mode

---

book/src/adding-board-support.md
laze-project.yml

This moves the definitions of `CONFIG_SWI` to the board laze contexts where they belong, as already documented in the book.
Depends on #959.

refactor(stm32): move the SWI selection to the boards, from the MCUs

---

src/ariel-os-debug-log/src/lib.rs

This removes the need for the `macro_metavar_expr` unstable feature, which was previously used to avoid "feature flairs" on log macros. This uses a module-based trick instead.
Successfully tested the `log` example with `defmt` selected and with `log` selected (one at a time).
Check that docs of these log macros haven't changed, i.e., that they still don't have "feature flairs" on them (which would say `defmt` or `log` otherwise).
Needed by #951.

refactor(debug-log): drop use of unstable `macro_metavar_expr` feature

---

book/src/adding-board-support.md

Drops an extraneous `CONFIG_SWI` in the porting guide, following #960.

docs(porting-guide): drop an extraneous `CONFIG_SWI`

---

laze-project.yml

`defmt 1.0` contains the fix needed for sccache getting changes to defmts log variable, so we don't need to disable it anymore:
Changelog:
https://github.com/knurling-rs/defmt/blob/main/CHANGELOG.md#defmt-v100-2025-04-01
PR that fixed this:
- https://github.com/knurling-rs/defmt/pull/938
Depends on #969.

chore(build): re-enable sccache

---

doc/support_matrix.yml
examples/blinky/laze.yml
examples/blinky/src/pins.rs
examples/gpio/laze.yml
examples/gpio/src/pins.rs
laze-project.yml
src/ariel-os-nrf/Cargo.toml
src/ariel-os-nrf/build.rs
src/ariel-os-nrf/src/i2c/controller/mod.rs
src/ariel-os-nrf/src/i2c/mod.rs
src/ariel-os-nrf/src/identity.rs
src/ariel-os-nrf/src/lib.rs
src/ariel-os-nrf/src/spi/main/mod.rs
src/ariel-os-nrf/src/spi/mod.rs
src/ariel-os-storage/build.rs
tests/gpio-interrupt-nrf/src/main.rs
tests/i2c-controller/laze.yml
tests/i2c-controller/src/main.rs
tests/i2c-controller/src/pins.rs
tests/spi-main/laze.yml
tests/spi-main/src/main.rs
tests/spi-main/src/pins.rs

This adds support for the nRF9151 MCU and the Nordic Thingy:91 X board.
This is not a duplicate of #929, which is for the older, non-X variant.
Successfully tested in hardware:
- `examples/gpio`
- `examples/storage`
- `examples/threading`
- `tests/i2c-controller` (using an on-board sensor)
- `tests/spi-main` (using an on-board sensor)
There is no user USB support on the nRF9151, and we don't yet support other network links, so couldn't test networking.
Additionally, `laze build -g -b nordic-thingy-91-x-nrf9151` completes successfully.

feat(boards): add support for the Nordic Thingy:91 X

---

doc/support_matrix.yml
examples/blinky/laze.yml
examples/blinky/src/pins.rs
examples/gpio/laze.yml
examples/gpio/src/pins.rs
examples/http-server/laze.yml
examples/http-server/src/pins.rs
laze-project.yml
tests/coap-blinky/laze.yml

This renames that board as it is comprised of two target MCUs, and that laze builder only targets the onboard nRF9160 MCU, not the companion nRF52840.
Running the following succeeds:
```sh
laze build -g -b nrf9160dk-nrf9160
```

refactor(boards)!: rename `nrf9160dk` to `nrf9160dk-nrf9160`

---

laze-project.yml

... otherwise, OOT applications in a subdir do `build/import/foo/../../ariel-os-cargo.toml` instead of `../../build/import/foo/ariel-os-cargo.toml`.
This worked before for OOT applications in the root folder (like, our ariel-os-hello), as `${relroot}` is `./` in that case.
I tested that the *current* `ariel-os-hello` but pointing to this PR's head still works.
Fixes #973.

fix(laze): change order of `root`/`relroot` for Ariel Cargo config

---

doc/support_matrix.yml
laze-project.yml

This adds initial support for the Espressif ESP32-C3-LCDkit. This does *not* add support for the onboard display.
Successfully tested in hardware:
- `examples/gpio`
- `examples/random`
- `examples/log` with defmt
- `examples/http-client`
- `tests/i2c-controller`
- `tests/spi-main`
- `tests/spi-loopback`
Logging with `log` is not supported, but this is out-of-scope.

feat(boards): add initial support for Espressif ESP32-C3-LCDkit

---

examples/blinky/src/pins.rs
examples/gpio/src/pins.rs
laze-project.yml

This adds support for the [FireBeetle 2 ESP32-C6](https://web.archive.org/web/20250214091848/https://wiki.dfrobot.com/SKU_DFR1075_FireBeetle_2_Board_ESP32_C6). This doesn't update the support matrix as that board is untested for now.

feat(boards): add support for the FireBeetle 2 ESP32-C6

---

.github/workflows/build-deploy-docs.yml
examples/http-server/laze.yml
laze-project.yml
src/ariel-os-debug-log/src/lib.rs
src/ariel-os-embassy-common/src/lib.rs
src/ariel-os-embassy/src/delegate.rs
src/ariel-os-embassy/src/lib.rs
src/ariel-os-esp/src/lib.rs
src/ariel-os-nrf/src/lib.rs
src/ariel-os-rp/src/lib.rs
src/ariel-os-stm32/src/lib.rs
src/ariel-os-threads/src/lib.rs
src/ariel-os-threads/src/sync/mutex.rs
src/ariel-os/src/lib.rs

This PR adds stable Rust support. It is ~~WIP~~ a first iteration.
- nightly is still default
- CI only builds nightly
- `examples/http-server` is using `type_alias_impl_trait` and thus conflicts `stable`.
unstable tracking list in #298.
Depends on #950.

feat: enable building on stable Rust

---

examples/blinky/src/pins.rs
examples/gpio/src/pins.rs

Follow-up to #983, fixes the nightly scheduled build.
Successfully tested with:
```sh
CONFIG_WIFI_NETWORK=<ssid> CONFIG_WIFI_PASSWORD=<pwd> laze build -g -b dfrobot-firebeetle2-esp32-c6
```
(to check the new board) and
```sh
CONFIG_WIFI_NETWORK=<ssid> CONFIG_WIFI_PASSWORD=<pwd> laze build -g -b espressif-esp32-c6-devkitc-1
```
(to check that the existing board still compiles).

docs(dfrobot-firebeetle2-esp32-c6): fix pin definitions

---

book/book.toml

See https://github.com/szabgab/public-mdbooks/issues/10

chore(book): remove the unused and deprecated `multilingual` field

---

examples/blinky/laze.yml
examples/blinky/src/pins.rs
examples/tcp-echo/laze.yml
laze-project.yml
src/ariel-os-embassy/Cargo.toml
src/ariel-os-embassy/src/eth.rs
src/ariel-os-embassy/src/lib.rs
src/ariel-os-hal/Cargo.toml
src/ariel-os-stm32/Cargo.toml
src/ariel-os-stm32/src/eth.rs
src/ariel-os-stm32/src/lib.rs
src/ariel-os/Cargo.toml

This PR add the ability of providing network from the embedded PHY of the Nucleo-144 board family
Each nucleo board have a different way to connect the PHY depending on the STM32 family used.
How do we properly abstract the pin definition of the ethernet PHY ?

feat(network): Add ethernet from nucleo-144 board family

---

laze-project.yml

... tested with `http-client` ...

chore(stm32): enable `has_eth_stm32` for the `st-nucleo-h755zi-q`

---

examples/coap-client/README.md
examples/coap-server/README.md
tests/coap-blinky/README.md
tests/coap/README.md

Fix linking to the [networking](https://github.com/ariel-os/ariel-os/tree/main/examples#networking) section in tests and examples READMEs.

docs: fix paths to the networking setup instructions

---

doc/support_matrix.yml
examples/blinky/laze.yml
examples/blinky/src/pins.rs
examples/gpio/laze.yml
examples/gpio/src/pins.rs
laze-project.yml
src/ariel-os-stm32/src/i2c/controller/mod.rs
src/ariel-os-stm32/src/i2c/mod.rs
src/ariel-os-stm32/src/spi/main/mod.rs
src/ariel-os-stm32/src/spi/mod.rs
tests/spi-loopback/laze.yml
tests/spi-loopback/src/pins.rs

This adds support for the STM32F411RE  MCU and the NUCLEO-F411RE board. 
Successfully tested in hardware:
+ `examples/blinky`
+ `examples/log`
+ `examples/gpio`
+ `examples/hello-world`
+ `tests/spi-loopback`
+ `tests/gpio-interrupt-stm32`
Some things are untestet (e.g. `tests/i2c_controller`) as I don't have the sensor.
Running the following also succeeds:
```bash
laze build -gm -b stm32u083c-dk test
laze build -g -b stm32u083c-dk
```

feat(boards): add support for the ST NUCLEO-F411RE

---

examples/blinky/src/main.rs
examples/gpio/src/main.rs
examples/power/src/main.rs
examples/thread-async-interop/src/main.rs
examples/usb-keyboard/src/main.rs

This replaces usage of `Timer::after(Duration::from_*())` with `Timer::after_*()` to avoid the need for importing `Duration`, and make these statements a bit shorter.

docs: use `Timer::after_millis()` to avoid the need for `Duration`

---

Cargo.lock
tests/i2c-controller/Cargo.toml
tests/i2c-controller/src/main.rs

This expands the `i2c-controller` test to use the onboard STTS22H temperature sensor on the STM32U083C-DK, which was not added as part of #986.
This PR is best reviewed commit by commit: the first one only refactors the test to use `cfg-if`, before expanding it in the second commit.
Successfully tested in hardware on STM32U083C-DK, and on ST-NUCLEO-C031C6 with an external LIS3DH (just to check the refactoring).

 test(i2c-controller): support the sensor on the STM32U083C-DK

---

Cargo.lock
src/ariel-os-debug/Cargo.toml
src/ariel-os-debug/src/lib.rs

This adds support for logging with `log` on architectures that do not provide atomics (e.g., Cortex-M0+ (ARMv6-M), RISC-V without the (A) extension).
Tested successfully with:
```sh
laze -C examples/log/ build -s log -b <board> run
```
where `<board>` is:
- espressif-esp32-c3-lcdkit (RISC-V without the (A) extension)
- rpi-pico-w (Cortex-M0+)
- st-nucleo-c031c6 (Cortex-M0+)
- st-nucleo-wb55 (Cortex-M4f, just to check it still works otherwise)

fix(log): add support for `log` on architectures without atomics

---

src/ariel-os-esp/src/gpio.rs
src/ariel-os-esp/src/i2c/controller/mod.rs
src/ariel-os-esp/src/lib.rs
src/ariel-os-esp/src/spi/main/mod.rs
src/ariel-os-rt/src/lib.rs

Enables the pedantic group in `ariel-os-esp` and refactors to make Clippy happy.
Similar PRs for the other HALs should follow.
Works towards #948.

refactor(esp): make Clippy pedantic happy

---

Cargo.lock
src/ariel-os-alloc/Cargo.toml
src/ariel-os-bench/Cargo.toml
src/ariel-os-boards/Cargo.toml
src/ariel-os-buildinfo/Cargo.toml
src/ariel-os-coap/Cargo.toml
src/ariel-os-debug-log/Cargo.toml
src/ariel-os-debug/Cargo.toml
src/ariel-os-embassy-common/Cargo.toml
src/ariel-os-embassy/Cargo.toml
src/ariel-os-esp/Cargo.toml
src/ariel-os-hal/Cargo.toml
src/ariel-os-identity/Cargo.toml
src/ariel-os-macros/Cargo.toml
src/ariel-os-nrf/Cargo.toml
src/ariel-os-power/Cargo.toml
src/ariel-os-random/Cargo.toml
src/ariel-os-rp/Cargo.toml
src/ariel-os-rt/Cargo.toml
src/ariel-os-runqueue/Cargo.toml
src/ariel-os-stm32-mapping/Cargo.toml
src/ariel-os-stm32/Cargo.toml
src/ariel-os-storage/Cargo.toml
src/ariel-os-threads/Cargo.toml
src/ariel-os-utils/Cargo.toml
src/ariel-os/Cargo.toml

This prepares for the v0.2.0 release by bumping the version numbers of all `ariel-os*` crates. It leaves the crates in `src/lib/` alone.
Works towards #1011.

chore(release): bump all `ariel-os*` crates to v0.2.0

---

laze-project.yml

This increases the stacksize requirements for stm32 ethernet.
Tested `tcp-echo`, `udp-echo`, `http-server`, `http-client` with both thread and interrupt executors.

fix(stm32): increase eth-stm32 executor stacksize requirement

---

examples/coap-client/src/main.rs
examples/device-metadata/src/main.rs
examples/storage/src/main.rs
examples/threading-channel/src/main.rs
examples/threading-event/src/main.rs
examples/usb-serial/src/main.rs
src/ariel-os-debug-log/src/lib.rs
src/ariel-os-storage/src/lib.rs
tests/i2c-controller/src/main.rs
tests/spi-loopback/src/main.rs
tests/spi-main/src/main.rs

This adds checks to defmt builds to avoid defmt-isms (such as formatting a range or slice with {:x}, or formatting results in {}) don't creep up unchecked, and adds the tools to smooth over inconsistencies between the languages.
```
laze build -g -b st-nucleo-wb55 -D LOG=debug -s log -d defmt
```
previously failed. Once this PR is through, not only should that not fail any more, but any case that does break should just as well break the developer's build that doesn't select log over defmt.
Contributes to #625 (doesn't fix it completely, that'd require checking also the currently unused log levels, and doing the same exercise also in the other direction; both is harder in that it'll require extra checking to see whether that doesn't introduce needless defmt interning).
A good test is `laze …

fix: ensure defmt log statements also work with log

---

src/ariel-os-hal/src/lib.rs

Pull request #961 removed some unneeded info from the context identifiers. This commit updates the documentation page of the ariel-os-hal crate to reflect these changes.
This follows #961 that removes the unneeded information from the context names.

docs(hal): reflect laze name change in ariel-os-hal

---

src/ariel-os-hal/src/dummy/storage.rs
src/ariel-os-storage/src/lib.rs

Small refactoring of the `init` function in [ariel-os-storage/src/lib.rs](https://github.com/ariel-os/ariel-os/blob/92d3aeac74ba33b3d9ed3dd575ae91a3a227678f/src/ariel-os-storage/src/lib.rs#L93-L101) to use an `if` statement instead of a `match` with an empty branch.

refactor(storage): use `if` in place of `match` with an empty branch

---

examples/coap-client/Cargo.toml
examples/coap-server/Cargo.toml
examples/http-client/Cargo.toml
examples/http-server/Cargo.toml
examples/tcp-echo/Cargo.toml
examples/udp-echo/Cargo.toml
tests/coap-blinky/Cargo.toml
tests/coap/Cargo.toml

Removes unused `heapless` dependencies in the `coap`, `http` and `tcp/udp echos` examples and in the `coap` tests.

refactor: remove unused heapless dependencies in some examples and tests

---

src/ariel-os-rp/src/gpio.rs
src/ariel-os-rp/src/i2c/controller/mod.rs
src/ariel-os-rp/src/lib.rs
src/ariel-os-rp/src/spi/main/mod.rs

Enables the pedantic group in ariel-os-esp and refactors to make Clippy happy.
Works towards https://github.com/ariel-os/ariel-os/pull/948.

refactor(rp): make Clippy pedantic happy

---

Cargo.toml
book/src/coding-conventions.md
src/ariel-os-alloc/src/lib.rs
src/ariel-os-bench/src/lib.rs
src/ariel-os-buildinfo/src/lib.rs
src/ariel-os-coap/build.rs
src/ariel-os-coap/src/lib.rs
src/ariel-os-debug-log/src/lib.rs
src/ariel-os-debug/src/lib.rs
src/ariel-os-embassy-common/src/lib.rs
src/ariel-os-embassy/src/asynch.rs
src/ariel-os-embassy/src/lib.rs
src/ariel-os-esp/src/lib.rs
src/ariel-os-hal/src/lib.rs
src/ariel-os-identity/src/lib.rs
src/ariel-os-macros/src/lib.rs
src/ariel-os-nrf/build.rs
src/ariel-os-nrf/src/lib.rs
src/ariel-os-power/src/lib.rs
src/ariel-os-random/src/lib.rs
src/ariel-os-rp/src/lib.rs
src/ariel-os-runqueue/src/lib.rs
src/ariel-os-runqueue/src/runqueue.rs
src/ariel-os-stm32/src/lib.rs
src/ariel-os-storage/src/lib.rs
src/ariel-os-threads/src/lib.rs
src/ariel-os-threads/src/sync/event.rs
src/ariel-os-threads/src/sync/mutex.rs
src/lib/coapcore/src/lib.rs

This fixes the few remaining warnings of Clippy pedantic, and sets Clippy's `pedantic` lint group to `warn` at workspace level, so that it issues warnings when developing locally but fails CI (because we make these warnings errors in CI with `-- --deny warnings`).
The attributes denying `clippy::pedantic` in each crates are removed, as they are now unnecessary.
I checked that every crate from `src/` is properly inheriting lints from the workspace.
- This PR is better reviewed commit by commit.
- CI runs Clippy, failing on warnings; it can however be useful to check locally that the pedantic lints are still properly triggered, for instance by commenting out one of the `#[must_use]` attribute:
https://github.com/ariel-os/ariel-os/blob/6d67089b91f9dcbcc0a8c51416191d4cb2c9d161/src/ariel-os-emb …

chore: enable Clippy pedantic at workspace level

---

laze-project.yml

This allows setting `PROFILE=dev`, nudging the LINK rule to then use `debug` as target folder.
Try with `laze build -b ... -DPROFILE=dev ...`.
Closes #1039.

feat(build): support "dev" profile

---

Cargo.lock
src/ariel-os-stm32/Cargo.toml
src/ariel-os-stm32/build.rs

This uses `stm32-metadata` to provide per-MCU `cfg` based on actual peripherals of each mcu.
Needed to make sth like #1040 work.

feat(stm32): provide stm32 peripheral `cfg` metadata

---

laze-project.yml

b/c dependency resolution ordering reasons, it wasn't possible to build `examples/http-client` for xtensa boards.
This PR
- makes all three toolchain-providing modules (esp, stable, nightly) provide_unique `cargo-toolchain` (implicitly conflicting with each other)
- make esp set `--cfg nightly`
- make the ariel-os context try `?xtensa` before `?stable`.
- actually limits `xtensa` to be available only in the `esp32` and `esp32s3` contexts

fix(build): model `xtensa` being `nightly`

---

Cargo.lock
laze-project.yml
src/ariel-os-alloc/Cargo.toml
src/ariel-os-alloc/src/lib.rs

This PR gives apps/modules the option to specify how much heap they'll need, similar to how we configure stack sizes.
On Cortex-M the leftover memory is used for heap in any case, and this is just a compile time check that requirements are met. On esp we can't take all leftover memory (yet), so this helps to specify that e.g., esp-wifi needs at least 72k of heap.

feat: make heap requirements configurable

---

src/ariel-os-stm32/Cargo.toml

#1045 enabled the default features for `stm32-metapac` for the build dependency of `ariel-os-stm32`, which caused the PAC to be compiled for the host system. That was not intended, and at least broke linking on OSX.

fix(stm32): select correct `stm32-metapac` features

---

laze-project.yml
src/ariel-os-rt/build.rs
src/ariel-os-rt/isr_stack.ld.in
src/ariel-os-rt/src/lib.rs

This PR makes `xtensa` use the same ISR stack machinery as `cortex-m` and `risc-v`.
I went with a default ISR stacksize of 32k, as it had a lot more (all leftover memory, so >100k). We can tune that as soon as we can measure (#977).
This now also shows the used stacksize (with `-DLOG=debug`):
```
Running `probe-rs run --protocol=jtag --chip esp32s3 --preverify ../../build/bin/espressif-esp32-s3-devkitc-1/cargo/xtensa-esp32s3-none-elf/release/http-c
lient`                                                                         
Finished in 8.40s
DEBUG ariel_os_rt::startup()                                                   
DEBUG ariel_os_rt: ISR_STACKSIZE=65536
...
```
Depends on #1037.
Cut out of #977.

feat(xtensa): take control of `xtensa` ISR stacksize

---

doc/support_matrix.yml
examples/blinky/laze.yml
examples/blinky/src/pins.rs
examples/gpio/laze.yml
examples/gpio/src/pins.rs
laze-project.yml
src/ariel-os-stm32/src/i2c/controller/mod.rs
src/ariel-os-stm32/src/i2c/mod.rs
src/ariel-os-stm32/src/lib.rs
src/ariel-os-stm32/src/spi/main/mod.rs
src/ariel-os-stm32/src/spi/mod.rs
src/ariel-os-storage/build.rs
tests/coap-blinky/laze.yml
tests/i2c-controller/laze.yml
tests/i2c-controller/src/pins.rs
tests/spi-loopback/laze.yml
tests/spi-loopback/src/pins.rs
tests/spi-main/laze.yml
tests/spi-main/src/pins.rs

This PR adds support to the ST B-L475E-IOT01A board and its STM32L475VG MCU 
~~Do we support USB for this board ? The clock would need to be generated by the MSI (calibrated using the LSE)~~
USB will be supported on this board, I was confused on how to change `MSIPLLEN` but embassy does it automatically. 
Successfully tested on hardware through the IoT-LAB platform: 
- `examples/gpio`
- `examples/log`
- `examples/random`
- `examples/storage`
- `examples/usb-serial`
- `tests/gpio-interrupt-stm32`
I also ran some other tests that didn't pass because it needs some external hardware connected, the errors I got were because the hardware was not connected: 
- `tests/i2c-controller`
- `tests/spi-loopback`
- `tests/spi-main`
Finally I ran `examples/http-server` and got the network interface to …

feat(boards): add support for ST B-L475E-IOT01A

---

examples/udp-echo/src/main.rs

Shrink the buffers used in the UDP echo example, and add the reasoning for their sizing, as it is not currently documented upstream.
This is a first step in being able to compile the networking examples for MCUs with little RAM.

docs(udp-example): use smaller buffers

---

Cargo.lock
ariel-os-cargo.toml

Gets rid of this:
```
warning: Patch `esp-storage v0.4.0 (https://github.com/ariel-os/esp-hal?branch=v0.23.1%2Bariel-os-threads#aa8d1995)` was not used in the crate graph.
Check that the patched package version and available features are compatible
with the dependency requirements. If the patch has a different version from                    
what is locked in the Cargo.lock file, run `cargo update` to use the new                       
version. This may also occur with an optional dependency that is not enabled.                  
```
We can re-add when wiring up storage on the ESPs.

chore(build): drop currently not used `esp-storage` patch

---

examples/threading-channel/laze.yml
examples/threading-event/laze.yml
examples/threading/src/main.rs
laze-project.yml
tests/benchmarks/bench_sched_flags/laze.yml
tests/benchmarks/bench_sched_yield/laze.yml
tests/threading-dynamic-prios/laze.yml
tests/threading-lock/laze.yml
tests/threading-mutex/laze.yml

This PR adds a module bundling tiny RAM requirements.
I started this for #1050, in combination with this ram-tiny, the st-nucleo-f042k6 builds fine.
As we currently don't have a way to filter builds by actually available / used RAM, this is just an arbitrary set of `small ram settings`.
E.g., when not using log but defmt, the stack requirements go way down.
Or, currently there's no network stack / driver combo that works with little ram devices.

feat(build): introduce `ram-tiny` laze module

---

examples/log/src/main.rs
src/ariel-os-debug-log/src/lib.rs
src/ariel-os-debug/src/lib.rs

We were not using that (internally) at all. It required us to keep the extra rtt channel in the defmt case. Without that we instantly save 1Kib RAM, which is absolutely necessary for the smaller MCUs.
This is a breaking change obviously.

feat(debug)!: drop support for print

---

doc/support_matrix.yml
examples/blinky/laze.yml
examples/blinky/src/pins.rs
examples/gpio/laze.yml
examples/gpio/src/pins.rs
laze-project.yml
src/ariel-os-rt/Cargo.toml
src/ariel-os-stm32/src/gpio.rs

This adds support for Cortex-M0 MCUs, the STM32F042K6 MCU in particular and the associated Nucleo-32 board

feat: add support stm32f042k6 mcu and nucleo board

---

.github/pull_request_template.md
CONTRIBUTING.md

As discussed this morning, this adds the DCO text to the CONTRIBUTING.md.
I've added both the explanation and the configuration to enable it permanently to the text.
From what I can find, GitHub squash commits include the Sign-offs, though the commit message probably gets a bit more cluttered.
After this, we can enabled the [dco app](https://github.com/apps/dco) to enforce this for contributions.
- http://developercertificate.org/
- https://github.com/apps/dco
None

 docs: Add DCO requirement to CONTRIBUTING.md 

---

Cargo.lock
Cargo.toml

This bumps `featurecomb` and `cortex-m-rt` with the goal of improving build times:
- `featurecomb` got rid of a dependency which happened to be in the critical path of compilation of Ariel OS. 
- `cortex-m-rt` depends on `cortex-m-rt-macros`, which was our last (transitive) dependency that brought `syn` *v1* into our tree, which resulted in both `syn` v1 and v2 being compiled.
- Build times can be plotted using `cargo build --timings`. For a clean build of a fresh clone of `ariel-os-hello`, this brings improvements in compile times of about 9–14%.
- @kaspar030 [`cortex-m-rt` v0.7.5](https://github.com/rust-embedded/cortex-m/blob/master/cortex-m-rt/CHANGELOG.md#v075) introduced an (optional?) `_stack_end` symbol. Can you check whether/how that interacts with the one in `ariel-os-rt`? …

chore(deps): bump selected dependencies to improve compile times

---

src/ariel-os-stm32/src/lib.rs

This adds a default clock configuration to the STM32F042K6 chip which works better than the default, with the OotB defaults e.g. I2C doesn't work.

feat(stm32): Add a somewhat sane clock configuration for STM32F042K6

---

doc/support_matrix.yml

Support for the Nucleo STM32WBA55 board was added in #782 and #783. This PR adds this board to the support matrix.
Closes #785.
Depends on #1057.

docs(stm32): add STM32WBA55CG to the support matrix

---

doc/support_matrix.yml
examples/blinky/laze.yml
examples/blinky/src/main.rs
examples/blinky/src/pins.rs
examples/gpio/laze.yml
examples/gpio/src/main.rs
examples/gpio/src/pins.rs
laze-project.yml
src/ariel-os-nrf/Cargo.toml
src/ariel-os-nrf/build.rs
src/ariel-os-nrf/src/lib.rs
tests/gpio-interrupt-nrf/src/main.rs
tests/gpio/src/pins.rs

This adds support for the venerable BBC micro:bit v1.
None
None

feat(nrf): Add support for BBC micro:bit v1

---

examples/README.md

The link to the examples readme was missing in #1071, this PR adds it.
follow-up to #1071

docs(README): add missing `i2c-scanner`

---

.github/workflows/build.yml

The initial goal of this was to require specific labels on PR that would allow us to specify whether to run the `Build` CI workflow, and if so, for which set of boards.
Now, the goal is simply to make the Build workflow fail quickly if no `ci-build:*` label is attached, and to collect information which would help us actually deploy the initial idea later, with minimal breakage.
This is intended to support the following scenarios when running for PRs:
- No `ci-build:*` labels: fail job
- `ci-build:small`: build with restricted build set
- ~`ci-build:large`: build with full build set (at least for now)~ (removed from this initial PR)
- ~`ci-build:skip`: skip building~ (removed from this initial PR)
- Two or more `ci-build:*` labels: fail job
**Runs for the merge queue and on main must take …

ci(build): restrict build runs based on PR labels

---

.github/workflows/main.yml
Cargo.lock
Cargo.toml
deny.toml
laze-project.yml
src/ariel-os-embassy-common/Cargo.toml
src/ariel-os-embassy-common/src/ble.rs
src/ariel-os-embassy-common/src/lib.rs
src/ariel-os-embassy/Cargo.toml
src/ariel-os-embassy/src/ble.rs
src/ariel-os-embassy/src/lib.rs
src/ariel-os-hal/Cargo.toml
src/ariel-os-hal/src/dummy/ble.rs
src/ariel-os-hal/src/dummy/mod.rs
src/ariel-os-macros/src/config.rs
src/ariel-os/Cargo.toml

This PR adds the public interface to access the TrouBLE stack, an example is provided to show how to use it
This is a step towards #560. 
Does the book page about BLE need to be in this PR or should it be a separate one ? 
At this time the public API lacks some features:
- A way to customize the MTU, though 27 is probably fine.

feat(ble): add public interface for BLE functionality

---

src/ariel-os/Cargo.toml

Users must use the laze module of the same name instead.
This is needed for #915, as we need to be able to separately choose to provide *static* configuration for IPv4 and/or IPv6.
BREAKING CHANGE: this removes a Cargo feature from the documentation.
Should likely have been part of #737.

docs(config)!: remove the `network-config-static` feature from the docs

---

Cargo.lock
ariel-os-cargo.toml

Fixes a non-deterministic issue when using the TRNG on an RP235x, introduced when adding support for that TRNG in #1077. The issue was present upstream, but fixed since our last fork update. This backports the fix from https://github.com/embassy-rs/embassy/pull/4139 in our Embassy fork (one single commit), and use that new fork branch for `embassy-rp`.
There were some conflicts when cherry-picking the fix, as Embassy has reworked how they handle peripherals in the meantime (`Peripheral` → `Peri`).
Without this fix, the `random` example *sometimes* panics at startup on rpi-pico2(-w), with the following error (happens abount once every three runs in my testing, YMMV):
```
[ERROR] panicked at 'RNG not busy, but ehr is not valid!'
```
With this fix, that example does not panic anymore (tested …

fix(rp235x): fix non-deterministic panics at startup when using the TRNG

---

laze-project.yml
src/ariel-os-nrf/src/hwrng.rs

This adds hwrng support for the nrf5340-net core. I don't have the hardware to test it out.
It seems that the nrf5340 app core doesn't have a (regular) random number generator available.
No errors when building with `laze build -g -b nrf5340dk-net` and `laze build -g -b nrf5340dk`   
~~Depends on #1072~~

feat(nrf53-net): add hwrng support

---

Cargo.toml

In 2.1.1 the `nightly` feature of `static_cell` changed to require a nightly toolchain to compile, making it fail on stable.
We don't use features behind the `nightly` feature anymore, this PR removes the dependency.

fix(deps): disable static cell `nightly` feature

---

laze-project.yml

This wires up passing through task arguments in our laze tasks.
This worked before laze 0.1.36 b/c any extra args were implicitly passed through, which was an undocumented laze feature. Current laze 0.1.37 now has proper (but still undocumented :innocent:) handlilng for this, allowing multi-cmd tasks to only pass through the extra args where desired.
This requires updating laze to at least version 0.1.37.
Try with e.g., `laze build -b nrf52840dk size`, then the same but appending `-A` to change the output mode of `size`.

feat(build): pass through task arguments where useful

---

Cargo.lock
src/lib/coapcore/Cargo.toml
src/lib/coapcore/src/ace.rs
src/lib/coapcore/src/seccfg.rs
src/lib/coapcore/src/seccontext.rs

In https://github.com/ariel-os/ariel-os/pull/1111, we fixed an issue.
The proper fix is https://github.com/t-moe/defmt-or-log/pull/8, which gets pulled in by this PR -- but as an unmergable draft until that PR is merged (and possibly released).

feat(coapcore): Use defmt_or_log's enhanced hex and CBOR outputs

---

book/book.toml
book/src/SUMMARY.md
book/src/build-system.md
book/src/vscode-configuration.md
laze-project.yml
scripts/vscode.rs

This generates a vscode configuration file targeting the selected board allowing to have linting using the rust-analyzer extension.
This is meant to be used on projects using the official Ariel OS `cargo generate` template. To generate the VSCode configuration use the `vscode-config` task with only one board selected, for example:
```sh
laze build -b rpi-pico vscode-config
```
Most of the rust-analyzer features works (including go to definition, inlay hints, documentation on hover and lint result).
I tested on some code examples (`hello-world`,`tcp-echo` and `random`) and on at least one board/builder of each vendor. User documentation in the book and configuration for developing in the Ariel repository itself will come in separate PRs.
This is a step required to have a good user …

feat(build): add vscode configuration generator

---

laze-project.yml

This makes sure the `has_nrf_ble` laze module introduced in #1074 can only be enabled on `nrf`, instead of being enabled by any laze module that merely selects it.
When combined with #1088, this reduces the number of tasks ran by laze with:
```
laze -C examples/ble-scanner build -m
```
from 24 to 8.

fix(nrf-ble): restrict the `has_nrf_ble` laze module to `nrf`

---

Cargo.lock
doc/support_matrix.yml
examples/blinky/laze.yml
examples/blinky/src/pins.rs
examples/gpio/laze.yml
examples/gpio/src/pins.rs
examples/i2c-scanner/laze.yml
examples/i2c-scanner/src/pins.rs
laze-project.yml
src/ariel-os-stm32/Cargo.toml
src/ariel-os-stm32/src/i2c/controller/mod.rs
src/ariel-os-stm32/src/i2c/mod.rs
src/ariel-os-stm32/src/lib.rs
src/ariel-os-stm32/src/spi/main/mod.rs
src/ariel-os-stm32/src/spi/mod.rs
src/ariel-os-stm32/src/usb.rs
src/ariel-os-storage/build.rs
src/ariel-os-utils/src/env.rs
tests/spi-loopback/laze.yml
tests/spi-loopback/src/pins.rs
tests/spi-main/laze.yml
tests/spi-main/src/main.rs
tests/spi-main/src/pins.rs

This adds initial support for the stm32u585ai, and the STEVAL-MKBOXPRO board.
~~Marking as draft as this was blind-ported.~~
~~Compiling~~ Tested working so far:
This PR is not tackling drivers for now.

feat(stm32): add initial stm32u585 / steval-mkboxpro support

---

src/ariel-os-threads/src/arch/cortex_m.rs

Fixes two warnings introduced by #1097:
```
Compiling ariel-os-threads v0.2.0 (/home/kaspar/src/own/rust/ariel-os/src/ariel-os-threads)                                                                 
warning: unused import: `cfg_if::cfg_if`                                                                                                                       
--> src/ariel-os-threads/src/arch/cortex_m.rs:2:5                                                                                                             
|                                                                                                                                                            
2 | use cfg_if::cfg_if; …
```

fix(threads): fix some warnings in cortex-m non-hardfault case

---

.github/workflows/main.yml
src/ariel-os-debug-log/src/lib.rs

Enable the `defmt` Cargo feature in the main Clippy action, and fix some lints it found in the `ariel-os-debug-log` crate.

fix(ci): enable `defmt` Cargo feature in main Clippy action

---

.github/workflows/build.yml

This follows #843 and actually acts on the value obtained by the `should-skip` CI workflow step, based on the cache hit and whether the `ci-build:skip` label is attached on the PR. Stacked PRs #1130 and #1134 helped test that that value was indeed correctly obtained, even in the case of stacked PRs (at least for CI runs before merging).
This PR actually implements skipping the main steps of the `Build` CI workflow, to make CI much faster when only updating the documentation.
Look at the logs of CI runs of #1130 and #1134 and check the `result` value of the step named "Whether to skip next steps". Only the one labeled with `ci-build:skip` should be `true`.
Follows #843.

ci(build): skip the Build when the `ci-build:skip` label is attached

---

src/ariel-os-threads/src/arch/cortex_m.rs
src/ariel-os-threads/src/arch/mod.rs
src/ariel-os-threads/src/arch/riscv.rs
src/ariel-os-threads/src/arch/xtensa.rs
src/ariel-os-threads/src/lib.rs

Use function pointers in API and move cast to register sized integer into arches.
Also, make `arg` an Option.
https://doc.rust-lang.org/stable/core/primitive.fn.html#casting-to-and-from-integers
https://doc.rust-lang.org/stable/core/ptr/index.html#provenance
#647

refactor(threads): use pointer for thread function

---

book/src/getting-started.md

Using `--locked` for installing `espup` is now the [recommended way](https://github.com/esp-rs/espup/pull/488), and installation currently fails without it.
**Note:** this PR doubles as a test for the `ci-build:skip` PR label, so do *not* merge it for now.
Depends on #1135.

docs(book): update the installation command for `espup`

---

src/ariel-os-hal/src/dummy/identity.rs
src/ariel-os-hal/src/dummy/mod.rs
src/ariel-os-hal/src/dummy/peripheral.rs

This PR splits some of the `ariel-os-hal::dummy` modules in seperate files.
Will be used to selectively use them by #647.
Signed-off-by: Kaspar Schleiser <kaspar@schleiser.de># Description

refactor(hal): split dummy module

---

src/ariel-os-macros/src/config.rs

Fixes a misspelling in a non-rustdoc-checked module name. It is currently commented out, but will be made user-visible when BLE is officially supported.

docs(config-macro): correct `reexports` module name

---

book/src/getting-started.md

There is no support for the ESP-IDF app descriptor yet. Pinning the espflash to a version before the app descriptor check was enabled.
This doesn't fix the underlying issue, newer esp bootloaders require the app descriptor. Boards with a more recent bootloader on them might no longer boot our builds.
Identified by #1149
See also #1150

docs(book): pin espflash to 3.3.0

---

src/ariel-os-debug/src/lib.rs

Seems like the log backend didn't actually compare to the configured log level.

fix(debug): actually compare log level in `log` backend

---

src/ariel-os-embassy-common/src/executor_swi.rs

This is a follow up to #1105 which did not actually allow the Clippy lint. The fix is to put the `#[expect]` above the `macro_rules!`.

fix(lint): allow `crate_in_macro_def` Clippy lint

---

Cargo.lock
Cargo.toml
laze-project.yml
src/ariel-os-nrf/Cargo.toml
src/ariel-os-nrf/src/ble.rs
src/ariel-os-nrf/src/irqs.rs

This PR adds BLE support for the nrf5340 MCU, the BLE stack needs to run on the network core.
To avoid the need to upgrade embassy, I made a fork in [ariel-os/nrf-sdc, branch nrf-sdc-nrf53-backport](https://github.com/ariel-os/nrf-sdc/tree/nrf-sdc-nrf53-backport) where I selected the commits relevant to the support of the nRF5340 and adapted it to the previous embassy peripheral model.
- Depends on #1072
- Depends on #1074 
- Depends on #1102
- Linked to #560   
How does the review process for a fork work ?

feat(ble): support BLE on nrf5340 network core

---

src/ariel-os-threads/src/lib.rs

#647 broke the scheduler in single-core mode by using a wrong comparison and insufficient clippy fallback.

fix(threads): fix `current_tid()`

---

.github/workflows/build.yml

This relies on the set of builders from `LAZE_BUILDERS` to determine whether installing the Xtensa toolchain is needed. Installing it takes a least one minute in CI, for each job, and sometimes takes much longer due to network fluctuations, so this should improve the performance and reliability of the CI a bit.
This PR is much better reviewed commit by commit.
Made possible by #1158.

ci(build): install the Xtensa toolchain only when needed

---

Cargo.lock
ariel-os-cargo.toml

This avoids cargo doing requests to check for updates on the branch.
Checked using: 
```sh 
CARGO_HOME=/tmp/foo cargo fetch                                                                                                                                                                                                                     
CARGO_HOME=/tmp/foo CARGO_NET_OFFLINE=true laze build -g -b nrf52840dk
```
This would error out when using the branch attribute, now the build step doesn't need to connect to the internet.
I get a weird error when trying the same for `espressif-esp32-s3-devkitc-1`:
```
error: no matching package named `rustc-literal-escaper` found
location searched: crates.io index
required by package `proc_macro v0.0.0 …
```

fix(deps): use revision instead of branch

---

.cargo/config.toml

This allows to reduce the time and space needed when cloning dependencies, notably the submodules of nrf-sdc.
Fixes #1155.
This is an unstable feature, with the [documentation here](https://doc.rust-lang.org/cargo/reference/unstable.html#git) but I don't see tradeoffs listed.
When changing revision: 
> Even with the presence of Cargo.lock or specifying a commit { rev = "…" }, gitoxide and libgit2 are still smart enough to shallow fetch without unshallowing the existing repository.

feat(build): shallow clone git dependencies

---

src/ariel-os-coap/src/lib.rs

This instantiates an `[::]:5683` `SocketAddr` directly instead of parsing a string at runtime, with the aim of reducing the binary size.
Measuring using the following command:
```sh
CONFIG_WIFI_NETWORK=<ssid> CONFIG_WIFI_PASSWORD=<pwd> laze -C tests/coap build -b rpi-pico-w size
```
this shaves around 800 bytes of text:
```
text    data     bss     dec     hex filename
539932       8   67804  607744   94600 build/bin/rpi-pico-w/test-coap/test-coap.elf
```
down from:
```
text    data     bss     dec     hex filename
540760       8   67804  608572   9493c build/bin/rpi-pico-w/test-coap/test-coap.elf
```
This is very likely because this was the only occurrence of the std's parsing logic in the whole binary.
@chrysn Can you make sure this still works as expected? I'm not too sure which …

refactor(coap): avoid parsing a string to create a listening address

---

src/ariel-os-esp/src/lib.rs

This PR adds the missing GPIO pins in the list for the esp32-s3. According to the technical reference manual, section 6.4.1 the pins are numbered from 0 to 21 and 26 to 48.
Issue noticed in #1199

fix(esp32s3): complete the list of GPIO pins

---

.github/workflows/main.yml

Now that [`taiki-e/install-action` supports `taplo-cli` directly](https://github.com/taiki-e/install-action/blob/main/TOOLS.md), we can avoid relying on it falling back on using `cargo-binstall`.
The correct name for `taiki-e/install-action` [is however `taplo`, not `taplo-cli`](https://github.com/taiki-e/install-action/issues/1100).

ci(lint): install `taplo-cli` without relying on `cargo-binstall`

---

Cargo.toml

This PR allows the `collapsible_if` Clippy lint which triggered new lint errors due to the new `if let` chains introduced in 1.89. We allow this lint since we do not want to bump the MSRV to 1.89 yet.

fix(clippy): allow the `collapsible_if` lint

---

.github/workflows/build.yml

Fixes an issue with the `check-labels` job introduced in #843 which could arise when the PR has more commits than the pagination limit of GitHub's API (30 commits). It would then incorrectly succeed, which would result in the `Build` workflow running for the entire set of builders, as the build would then not be restricted.

ci(build): fix `check-labels` succeeding on PRs with many commits

---

src/ariel-os/Cargo.toml

The `defmt` Cargo feature needs to be propagated to the `ariel-os-sensors` crate, otherwise its types are not printable with `defmt`.
---
`ci-build:skip` is enough because there is currently no implementors and Clippy and rustdoc make sure the rest is fine.
Extracted from #1191.

fix(sensors): enable `defmt` on `ariel-os-sensors` when needed

---

laze-project.yml

Following #1176 which focused too much on the `tcp-echo` example, the HTTP examples are still not able to link properly because of lack of RAM. This disables networking on that chip again, as a temporary measure, until we decide how to only disable the HTTP examples on that chip.

fix(stm32u083mc): disable networking again to accommodate HTTP examples

---

.github/renovate.json

This PR reconfigures renovate to add `renovate` labels to every PR raised by Renovate. It also removes the `ci-build:native` rule for actions because in the case that other packages (i.e. dev dependencies) need to be pinned this leads to the PR having two build labels which fails the CI

chore: reconfigure renovate

---

.github/workflows/matrix-bot.yml

From what I understand from this [SO exchange](https://stackoverflow.com/a/59588725) this is how to restrict the bot from warning us about PRs with the label `renovate`. 
See also #1248 which makes the renovate bot add the aforementioned labels to every PR it raises

chore: prevent matrix bot from reporting renovate PRs

---

src/ariel-os-macros/src/define_count_adjusted_sensor_enums.rs
src/ariel-os-sensors/src/registry.rs

These iterators are constructed from arrays, so it makes sense to guarantee that they impl `ExactSizeIterator` so that consumers can rely on it.
This is not a breaking change as these items are not yet documented.
With #1219 in, the `ariel-os-sensors` crate's documentation can be generated with:
```sh
cargo +nightly doc -p ariel-os-sensors
```
---
`ci-build:skip` is enough because there is currently no implementors and Clippy and rustdoc make sure the rest is fine. 
Mostly extracted from #1191.

refactor(sensors): make appropriate iterators `ExactSizeIterator`s

---

Cargo.toml

This removes the `konst` dependency from the workspace manifest, as it is now unused since #1271.
`ci-build:skip` is enough as Clippy already checks the dependency graph and that the only remaining occurrences of the string `konst` in the codebase are in the demo SVG.
Closes #1286.

chore(deps): remove `konst` from the workspace manifest as it is unused

---

Cargo.lock
src/ariel-os-coap/Cargo.toml

This removes the `embassy-futures` dependency from `ariel-os-coap`, which seems unused (grepping for `embassy_futures` returns no matches). It seems I did not bother checking whether it was used in #793.

chore(ariel-os-coap): remove the unused `embassy-futures` dependency

---

Cargo.lock
src/ariel-os-embassy-common/Cargo.toml
src/ariel-os-embassy-common/src/i2c/controller/mod.rs
src/ariel-os-embassy-common/src/lib.rs

This leverages `embassy_time::with_timeout()` to replace a construct using `embassy_futures`'s `select()` combined with a `Timer` to implement I2C communication timeouts. This makes the implementation a bit simpler and easier to parse, and allows removing `embassy_futures` as a dependency of the internal `ariel-os-embassy-common`.
The happy path can be tested on an stm32u083c-dk or an bbc-microbit-v2 (as they both have an onboard I2C sensor) with the `tests/i2c-controller` test, and the failing/timeout path on an nrf52840dk with that same test (as it does *not* have any I2C device on board): it should panic with an `I2c(NoAcknowledge(Unknown))` error.

refactor(i2c): replace `embassy-futures`'s `select` with `with_timeout`

---

.github/workflows/main.yml

This PR moves the `cargo-manifest-check` out of the `lint` job into a new `cargo-manifest-check` job that is run after the `lint` job.
Follow up to #1235.

refactor(ci): move `cargo-manifest-check` out of the `lint` CI job

---

Cargo.lock
src/ariel-os-embassy/Cargo.toml

This PR propagates the `defmt` Cargo feature to `trouble-host` when enabled, to make debugging easier in some cases.
Successfully tested on nrf52840dk, `trouble-host` log lines start with `[host]`. We might want to tune its log level down, but this can be done later (if not already resolved by updating to `trouble-host` v0.2 in #1307).

fix(ble): propagate the `defmt` feature to `trouble-host` when enabled

---

doc/gen_support_matrix_html.rs

This pr changes the validation and functionality mapping by collecting all errors into one if there are any errors during the process. This has the advantage that all errors are printed during a single execution instead of only one at a time.
So far it is still split into validation errors and board mapping errors, printing only validation errors if there are some, and omitting any board mapping errors.
The goal is to make the generator a bit more user friendly and prevent CI whack-a-mole when adding a new feature
The generated output should not have changed
None

 feat(support-matrix): collect all errors instead of one 

---

Cargo.lock
src/ariel-os-coap/Cargo.toml
src/ariel-os-coap/build.rs

This replaces `serde_yml`, an LLM-"maintained", unsound fork of the unmaintained `serde_yaml`, for which a [security advisory has been issued last week](https://rustsec.org/advisories/RUSTSEC-2025-0068.html).
I plan to add a `cargo-deny`'s ban as a follow-up so it doesn't creep in in the future. #1344
I only tested that the `coap-client` example compiles properly. @chrysn can you do more through testing if needed?

fix(coap): use unmaintained `serde_yaml` instead of unsound `serde_yml`

---

src/ariel-os-embassy/src/lib.rs

This re-exports `with_timeout()` as implementing timeouts is very common and otherwise users need to rely on `embassy-futures`'s `select()`. By exposing this we only commit to its API, not the fact that it is currently an `embassy-time` re-export, thanks to #1321.
Browse the rendered docs and make sure none of the types newly exposed (including as function parameters and return types) refer to types from `ariel_os::reexports`.

feat(time): provide a `with_timeout()` helper by re-exporting Embassy's

---

src/ariel-os-sensors/Cargo.toml
src/ariel-os-sensors/laze.yml
src/laze.yml

This makes host tests actually run for the `ariel-os-sensors` crate.
Using `ci-build:skip` as that still allows host tests to run in CI.
To test this, introduce a syntax error in the doc test in `src/ariel-os-sensors/src/sample.rs` for instance, and then run the following command, which runs the host tests for every properly set-up crate:
```sh
laze build --builders host --multiple-tasks --global test
```

test(sensors): make host tests run for `ariel-os-sensors` as well

---

src/ariel-os/src/lib.rs

Fix a small typo in the resource section
Spotted by @ROMemories in #1352 
None

doc(api): fix typo in resource section

---

examples/http-client/laze.yml
examples/http-server/laze.yml
laze-project.yml

This introduces a `ram-small` laze module, similar to `ram-tiny` (#1053), for MCUs having more RAM than `ram-tiny` but still not enough to do HTTP or CoAP.

refactor: introduce the `ram-small` module for MCUs unable to do HTTP

---

.github/workflows/main.yml

The [generated `Cargo.toml` from #1282](https://github.com/ariel-os/ariel-os/pull/1282/files#diff-1a22d55f98c7cc4e31569d42dd1b6c424ecb496bb35584d341d6d2dce3da6dcb) contains `^[package.rust-version]\nworkspace = true\n`, which fails the simple `^rust-version` check.
This PR simply relaxes the check to just look for `rust-version`.

ci: relax `rust-version` key check

---

src/ariel-os-macros/src/define_count_adjusted_sensor_enums.rs

Following #1355, this makes these types structs instead of enums, to give us more flexibility in the future if we wanted to transparently swap their implementations. The existing enums are kept but moved into the one field these structs now contain.
Compiling #1363 with the following command should help show this works:
```sh
laze -C examples/sensors-debug/ build -b stm32u083c-dk
```
Depends on #1355.

refactor(sensors): make `Sensors` and `ReadingChannels` structs instead

---

book/src/networking.md
laze-project.yml

This renames laze modules that are actually IPv4-only to make room for the IPv6 modules that will be introduced by #915. This only renames laze modules for now and leaves Cargo features untouched.
This is not a breaking change as old modules are kept and only deprecated.
Check for forgotten occurrences in the codebase.
Test the `udp-echo` example (or any other network example):
```sh
laze -C examples/udp-echo/ build -s network-config-dhcp -b nrf52840dk
```
and pass `--disable network-config-dhcpv4` and `--disable network-config-dhcp` to it, possibly testing in hardware and/or checking the size of the binary to verify these are actually equivalent. The same can be done for `--select` to verify these indeed behave as aliases.
Extracted from #915.

refactor(network): clarify the names of IPv4-only laze modules

---

book/src/introduction.md

This adds a set of urls to other helpful resources almost identical to what we have in the [api documentations](https://ariel-os.github.io/ariel-os/dev/docs/api/ariel_os/). I've kept the format and the set of resources identical, swapping the link to the book with the link to the api documentation.
Line 15 through 12 is identical to what we have in [the api docs](https://github.com/ariel-os/ariel-os/blob/main/src/ariel-os/src/lib.rs#L8-L15).

docs(book): add urls to other doc resources

---

doc/gen_support_matrix_html.rs
doc/schema.rs

This PR moves the schema definition structs for the `gen_support_matrix_html.rs` script in an external module.

refactor(docs): move support matrix schema in external module

---

src/ariel-os-stm32/src/lib.rs

This is just a small refactor to make future changes to the way the RCC configuration is provided easier, and in particular so that these changes do not constantly result in conflicts as we land support for other STM32 MCUs. Now is a good time to do this as we do not have any in-flight PRs that add support for STM32 MCUs (except for #1183, which I will handle).
Successfully tested the `random` example (which is known to require proper clock configuration) on the stm32u083c-dk.
The aforementioned future changes are in #1389.

refactor(stm32): move the RCC config to a dedicated pure function

---

doc/support_matrix.yml
examples/gpio/src/pins.rs
laze-project.yml
src/ariel-os-stm32/src/i2c/controller/mod.rs
src/ariel-os-stm32/src/i2c/mod.rs
src/ariel-os-stm32/src/lib.rs
src/ariel-os-stm32/src/spi/main/mod.rs
src/ariel-os-stm32/src/spi/mod.rs
src/ariel-os-storage/build.rs
tests/i2c-controller/src/pins.rs
tests/spi-loopback/src/pins.rs
tests/spi-main/src/pins.rs

This adds support for the STM32U073KC MCU: the STM32U073 is the same as the STM32U083 we already support, the only difference being it does not have an AES accelerator. Adding support for it is useful because it is slightly cheaper and, maybe more importantly for now, is more stocked by PCBA manufacturers.
There is no official development kit with that MCU (the closest one is the STM32U083C-DK which we do support), so this does not add a board in the support matrix (nor to the CI), only the MCU. How we render support for MCUs without a board is part of #1182.

feat(stm32): add support for the STM32U073KC

---

book/src/boards/bbc-microbit-v1.md
book/src/boards/bbc-microbit-v2.md
book/src/boards/espressif-esp32-c3-lcdkit.md
book/src/boards/espressif-esp32-c6-devkitc-1.md
book/src/boards/espressif-esp32-s3-devkitc-1.md
book/src/boards/heltec-wifi-lora-32-v3.md
book/src/boards/nordic-thingy-91-x-nrf9151.md
book/src/boards/nrf52840dk.md
book/src/boards/nrf52dk.md
book/src/boards/nrf5340dk.md
book/src/boards/nrf9160dk-nrf9160.md
book/src/boards/rpi-pico-w.md
book/src/boards/rpi-pico.md
book/src/boards/rpi-pico2-w.md
book/src/boards/rpi-pico2.md
book/src/boards/seeedstudio-lora-e5-mini.md
book/src/boards/st-b-l475e-iot01a.md
book/src/boards/st-nucleo-c031c6.md
book/src/boards/st-nucleo-f042k6.md
book/src/boards/st-nucleo-f401re.md
book/src/boards/st-nucleo-f411re.md
book/src/boards/st-nucleo-h755zi-q.md
book/src/boards/st-nucleo-wb55.md
book/src/boards/st-nucleo-wba55.md
book/src/boards/st-steval-mkboxpro.md
book/src/boards/stm32u083c-dk.md
book/templates/board-page.md.tmpl

This PR rewrite the support matrix table found in the board pages in Markdown to make it easier to use Markdown features, such as footnotes.
The rendered output should be the same.
Extracted from #1403.

docs(gen-book): rewrite board page support matrix table in Markdown
